### PR TITLE
change nullptr to a int ptr for qt 5.15.2 bug

### LINKED ISSUE #526: `ign gazebo` results in a seg fault (QT issue)
Running `ign gazebo` results in a seg fault:

<details>
<summary> Log </summary>

  ```
/usr/lib/ruby/ignition/cmdgazebo4.rb:426: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0007 p:---- s:0058 e:000057 CFUNC  :call
c:0006 p:0016 s:0053 e:000052 METHOD /usr/lib/ruby/ignition/cmdgazebo4.rb:426
c:0005 p:0060 s:0047 e:000046 BLOCK  /usr/lib/ruby/ignition/cmdgazebo4.rb:456 [FINISH]
c:0004 p:---- s:0044 e:000043 CFUNC  :fork
c:0003 p:0654 s:0040 e:000039 METHOD /usr/lib/ruby/ignition/cmdgazebo4.rb:452
c:0002 p:0615 s:0019 E:0007a8 EVAL   /usr/bin/ign:267 [FINISH]
c:0001 p:0000 s:0003 E:0018a0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/bin/ign:267:in `<main>'
/usr/lib/ruby/ignition/cmdgazebo4.rb:452:in `execute'
/usr/lib/ruby/ignition/cmdgazebo4.rb:452:in `fork'
/usr/lib/ruby/ignition/cmdgazebo4.rb:456:in `block in execute'
/usr/lib/ruby/ignition/cmdgazebo4.rb:426:in `runGui'
/usr/lib/ruby/ignition/cmdgazebo4.rb:426:in `call'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f3cf49c50f5 RBP: 0x00007f3cc5113950 RSP: 0x00007f3cc51138e0
 RAX: 0x0000000000000008 RBX: 0x0000000000000010 RCX: 0x00007f3b63a6d9ca
 RDX: 0x0000557de0fb0ef0 RDI: 0x00007f3c909c07c0 RSI: 0x00007f3c909c1e80
  R8: 0x00007f3c909c1e80  R9: 0x0000000000000005 R10: 0x0000000000000015
 R11: 0x0000000000000000 R12: 0x00007f3c909c07b0 R13: 0x0000000000000000
 R14: 0x00007f3cc5113d00 R15: 0x0000557de040a140 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/usr/lib/libruby.so.2.7(0x7f3cfa104c04) [0x7f3cfa104c04]
/usr/lib/libruby.so.2.7(0x7f3cf9f6f019) [0x7f3cf9f6f019]
/usr/lib/libruby.so.2.7(0x7f3cfa07fb3a) [0x7f3cfa07fb3a]
/usr/lib/libc.so.6(__restore_rt+0x0) [0x7f3cf9d3f6a0]
/usr/lib/libQt5Quick.so.5(_ZNK12QQuickWindow29createTextureFromNativeObjectENS_16NativeObjectTypeEPKviRK5QSize6QFlagsINS_19CreateTextureOptionEE+0xf5) [0x7f3cf49c50f5]
/usr/lib/ign-gazebo-4/plugins/gui/libGzScene3D.so(_ZN8ignition6gazebo2v411TextureNodeC1EP12QQuickWindow+0xa3) [0x7f3cec477273]
/usr/lib/ign-gazebo-4/plugins/gui/libGzScene3D.so(_ZN8ignition6gazebo2v416RenderWindowItem15updatePaintNodeEP7QSGNodePN10QQuickItem19UpdatePaintNodeDataE+0xb4) [0x7f3cec4779d4]
/usr/lib/libQt5Quick.so.5(_ZN19QQuickWindowPrivate15updateDirtyNodeEP10QQuickItem+0x858) [0x7f3cf49c70f8]
/usr/lib/libQt5Quick.so.5(_ZN19QQuickWindowPrivate16updateDirtyNodesEv+0x8c) [0x7f3cf49c79ac]
/usr/lib/libQt5Quick.so.5(_ZN19QQuickWindowPrivate14syncSceneGraphEv+0xa1) [0x7f3cf49c9311]
/usr/lib/libQt5Quick.so.5(0x7f3cf4968c00) [0x7f3cf4968c00]
/usr/lib/libQt5Quick.so.5(0x7f3cf496ab68) [0x7f3cf496ab68]
/usr/lib/libQt5Quick.so.5(0x7f3cf496b897) [0x7f3cf496b897]
/usr/lib/libQt5Core.so.5(0x7f3cf569af0f) [0x7f3cf569af0f]
/usr/lib/libpthread.so.0(start_thread+0xe9) [0x7f3cf9ccf3e9]
/usr/lib/libc.so.6(clone+0x43) [0x7f3cf9e02293]

-- Other runtime information -----------------------------------------------

* Loaded script: /usr/bin/ign

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 ruby2_keywords.rb
    5 /usr/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
    6 /usr/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
    7 /usr/lib/ruby/2.7.0/x86_64-linux/rbconfig.rb
    8 /usr/lib/ruby/2.7.0/rubygems/compatibility.rb
    9 /usr/lib/ruby/2.7.0/rubygems/defaults.rb
   10 /usr/lib/ruby/2.7.0/rubygems/deprecate.rb
   11 /usr/lib/ruby/2.7.0/rubygems/errors.rb
   12 /usr/lib/ruby/2.7.0/rubygems/version.rb
   13 /usr/lib/ruby/2.7.0/rubygems/requirement.rb
   14 /usr/lib/ruby/2.7.0/rubygems/platform.rb
   15 /usr/lib/ruby/2.7.0/rubygems/basic_specification.rb
   16 /usr/lib/ruby/2.7.0/rubygems/stub_specification.rb
   17 /usr/lib/ruby/2.7.0/rubygems/util.rb
   18 /usr/lib/ruby/2.7.0/rubygems/text.rb
   19 /usr/lib/ruby/2.7.0/rubygems/user_interaction.rb
   20 /usr/lib/ruby/2.7.0/rubygems/specification_policy.rb
   21 /usr/lib/ruby/2.7.0/rubygems/util/list.rb
   22 /usr/lib/ruby/2.7.0/rubygems/specification.rb
   23 /usr/lib/ruby/2.7.0/rubygems/exceptions.rb
   24 /usr/lib/ruby/2.7.0/rubygems/bundler_version_finder.rb
   25 /usr/lib/ruby/2.7.0/rubygems/dependency.rb
   26 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_gem.rb
   27 /usr/lib/ruby/2.7.0/x86_64-linux/monitor.so
   28 /usr/lib/ruby/2.7.0/monitor.rb
   29 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb
   30 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_warn.rb
   31 /usr/lib/ruby/2.7.0/rubygems.rb
   32 /usr/lib/ruby/2.7.0/rubygems/path_support.rb
   33 /usr/lib/ruby/2.7.0/did_you_mean/version.rb
   34 /usr/lib/ruby/2.7.0/did_you_mean/core_ext/name_error.rb
   35 /usr/lib/ruby/2.7.0/did_you_mean/levenshtein.rb
   36 /usr/lib/ruby/2.7.0/did_you_mean/jaro_winkler.rb
   37 /usr/lib/ruby/2.7.0/did_you_mean/spell_checker.rb
   38 /usr/lib/ruby/2.7.0/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   39 /usr/lib/ruby/2.7.0/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   40 /usr/lib/ruby/2.7.0/did_you_mean/spell_checkers/name_error_checkers.rb
   41 /usr/lib/ruby/2.7.0/did_you_mean/spell_checkers/method_name_checker.rb
   42 /usr/lib/ruby/2.7.0/did_you_mean/spell_checkers/key_error_checker.rb
   43 /usr/lib/ruby/2.7.0/did_you_mean/spell_checkers/null_checker.rb
   44 /usr/lib/ruby/2.7.0/did_you_mean/formatters/plain_formatter.rb
   45 /usr/lib/ruby/2.7.0/did_you_mean/tree_spell_checker.rb
   46 /usr/lib/ruby/2.7.0/did_you_mean.rb
   47 /usr/lib/ruby/2.7.0/optparse.rb
   48 /usr/lib/ruby/2.7.0/psych/versions.rb
   49 /usr/lib/ruby/2.7.0/psych/exception.rb
   50 /usr/lib/ruby/2.7.0/psych/syntax_error.rb
   51 /usr/lib/ruby/2.7.0/x86_64-linux/psych.so
   52 /usr/lib/ruby/2.7.0/x86_64-linux/stringio.so
   53 /usr/lib/ruby/2.7.0/psych/omap.rb
   54 /usr/lib/ruby/2.7.0/psych/set.rb
   55 /usr/lib/ruby/2.7.0/psych/class_loader.rb
   56 /usr/lib/ruby/2.7.0/x86_64-linux/strscan.so
   57 /usr/lib/ruby/2.7.0/psych/scalar_scanner.rb
   58 /usr/lib/ruby/2.7.0/psych/nodes/node.rb
   59 /usr/lib/ruby/2.7.0/psych/nodes/stream.rb
   60 /usr/lib/ruby/2.7.0/psych/nodes/document.rb
   61 /usr/lib/ruby/2.7.0/psych/nodes/sequence.rb
   62 /usr/lib/ruby/2.7.0/psych/nodes/scalar.rb
   63 /usr/lib/ruby/2.7.0/psych/nodes/mapping.rb
   64 /usr/lib/ruby/2.7.0/psych/nodes/alias.rb
   65 /usr/lib/ruby/2.7.0/psych/nodes.rb
   66 /usr/lib/ruby/2.7.0/psych/streaming.rb
   67 /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb
   68 /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb
   69 /usr/lib/ruby/2.7.0/psych/visitors/emitter.rb
   70 /usr/lib/ruby/2.7.0/psych/handler.rb
   71 /usr/lib/ruby/2.7.0/psych/tree_builder.rb
   72 /usr/lib/ruby/2.7.0/psych/visitors/yaml_tree.rb
   73 /usr/lib/ruby/2.7.0/psych/json/ruby_events.rb
   74 /usr/lib/ruby/2.7.0/psych/visitors/json_tree.rb
   75 /usr/lib/ruby/2.7.0/psych/visitors/depth_first.rb
   76 /usr/lib/ruby/2.7.0/psych/visitors.rb
   77 /usr/lib/ruby/2.7.0/psych/parser.rb
   78 /usr/lib/ruby/2.7.0/psych/coder.rb
   79 /usr/lib/ruby/2.7.0/psych/core_ext.rb
   80 /usr/lib/ruby/2.7.0/psych/stream.rb
   81 /usr/lib/ruby/2.7.0/psych/json/yaml_events.rb
   82 /usr/lib/ruby/2.7.0/psych/json/tree_builder.rb
   83 /usr/lib/ruby/2.7.0/psych/json/stream.rb
   84 /usr/lib/ruby/2.7.0/psych/handlers/document_stream.rb
   85 /usr/lib/ruby/2.7.0/psych.rb
   86 /usr/lib/ruby/2.7.0/yaml.rb
   87 /usr/lib/ruby/2.7.0/x86_64-linux/fiddle.so
   88 /usr/lib/ruby/2.7.0/fiddle/function.rb
   89 /usr/lib/ruby/2.7.0/fiddle/closure.rb
   90 /usr/lib/ruby/2.7.0/fiddle.rb
   91 /usr/lib/ruby/2.7.0/fiddle/value.rb
   92 /usr/lib/ruby/2.7.0/fiddle/pack.rb
   93 /usr/lib/ruby/2.7.0/fiddle/struct.rb
   94 /usr/lib/ruby/2.7.0/fiddle/cparser.rb
   95 /usr/lib/ruby/2.7.0/fiddle/import.rb
   96 /usr/lib/ruby/2.7.0/x86_64-linux/cgi/escape.so
   97 /usr/lib/ruby/2.7.0/cgi/util.rb
   98 /usr/lib/ruby/2.7.0/erb.rb
   99 /usr/lib/ruby/ignition/cmdgazebo4.rb

* Process memory map:

40bae000-40c5d000 rw-p 00000000 00:00 0 
40f26000-40fd5000 rw-p 00000000 00:00 0 
41328000-4132a000 r-xs 00000000 00:01 11548                              /memfd:/.glXXXXXX (deleted)
557ddeec7000-557ddeec8000 r--p 00000000 103:04 6208442                   /usr/bin/ruby
557ddeec8000-557ddeec9000 r-xp 00001000 103:04 6208442                   /usr/bin/ruby
557ddeec9000-557ddeeca000 r--p 00002000 103:04 6208442                   /usr/bin/ruby
557ddeeca000-557ddeecb000 r--p 00002000 103:04 6208442                   /usr/bin/ruby
557ddeecb000-557ddeecc000 rw-p 00003000 103:04 6208442                   /usr/bin/ruby
557ddfb7e000-557de0347000 rw-p 00000000 00:00 0                          [heap]
557de0347000-557de1f26000 rw-p 00000000 00:00 0                          [heap]
7f3c84000000-7f3c8411c000 rw-p 00000000 00:00 0 
7f3c8411c000-7f3c88000000 ---p 00000000 00:00 0 
7f3c88000000-7f3c88021000 rw-p 00000000 00:00 0 
7f3c88021000-7f3c8c000000 ---p 00000000 00:00 0 
7f3c8c000000-7f3c8c021000 rw-p 00000000 00:00 0 
7f3c8c021000-7f3c90000000 ---p 00000000 00:00 0 
7f3c90000000-7f3c90bfc000 rw-p 00000000 00:00 0 
7f3c90bfc000-7f3c94000000 ---p 00000000 00:00 0 
7f3c94000000-7f3c94021000 rw-p 00000000 00:00 0 
7f3c94021000-7f3c98000000 ---p 00000000 00:00 0 
7f3c98000000-7f3c98021000 rw-p 00000000 00:00 0 
7f3c98021000-7f3c9c000000 ---p 00000000 00:00 0 
7f3c9c000000-7f3c9c021000 rw-p 00000000 00:00 0 
7f3c9c021000-7f3ca0000000 ---p 00000000 00:00 0 
7f3ca0000000-7f3ca0021000 rw-p 00000000 00:00 0 
7f3ca0021000-7f3ca4000000 ---p 00000000 00:00 0 
7f3ca4000000-7f3ca4021000 rw-p 00000000 00:00 0 
7f3ca4021000-7f3ca8000000 ---p 00000000 00:00 0 
7f3ca8000000-7f3ca8021000 rw-p 00000000 00:00 0 
7f3ca8021000-7f3cac000000 ---p 00000000 00:00 0 
7f3cac000000-7f3cac021000 rw-p 00000000 00:00 0 
7f3cac021000-7f3cb0000000 ---p 00000000 00:00 0 
7f3cb0000000-7f3cb0021000 rw-p 00000000 00:00 0 
7f3cb0021000-7f3cb4000000 ---p 00000000 00:00 0 
7f3cb4000000-7f3cb4021000 rw-p 00000000 00:00 0 
7f3cb4021000-7f3cb8000000 ---p 00000000 00:00 0 
7f3cb8416000-7f3cb8966000 r--s 00000000 103:04 6184954                   /usr/lib/libQt5Core.so.5.15.2
7f3cb8966000-7f3cb8ea6000 r--s 00000000 103:04 6192156                   /usr/lib/libQt5Quick.so.5.15.2
7f3cb8ea6000-7f3cb90b6000 r--s 00000000 103:04 6163879                   /usr/lib/libc-2.32.so
7f3cb90b6000-7f3cb93fb000 r--s 00000000 103:04 6208497                   /usr/lib/libruby.so.2.7.2
7f3cb93fb000-7f3cb93fc000 ---p 00000000 00:00 0 
7f3cb93fc000-7f3cb9bfc000 rw-p 00000000 00:00 0 
7f3cb9bfc000-7f3cb9dfc000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cb9dfc000-7f3cb9ffc000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cb9ffc000-7f3cb9ffd000 ---p 00000000 00:00 0 
7f3cb9ffd000-7f3cba7fd000 rw-p 00000000 00:00 0 
7f3cba7fd000-7f3cba7fe000 ---p 00000000 00:00 0 
7f3cba7fe000-7f3cbaffe000 rw-p 00000000 00:00 0 
7f3cbaffe000-7f3cbafff000 ---p 00000000 00:00 0 
7f3cbafff000-7f3cbb7ff000 rw-p 00000000 00:00 0 
7f3cbb7ff000-7f3cbb800000 ---p 00000000 00:00 0 
7f3cbb800000-7f3cbc000000 rw-p 00000000 00:00 0 
7f3cbc000000-7f3cbc021000 rw-p 00000000 00:00 0 
7f3cbc021000-7f3cc0000000 ---p 00000000 00:00 0 
7f3cc0050000-7f3cc00e0000 r--s 00000000 103:04 6554875                   /usr/lib/ign-gazebo-4/plugins/gui/libGzScene3D.so
7f3cc00e0000-7f3cc01e0000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc01e0000-7f3cc01e1000 ---p 00000000 00:00 0 
7f3cc01e1000-7f3cc09e1000 rw-p 00000000 00:00 0 
7f3cc09e1000-7f3cc09e2000 ---p 00000000 00:00 0 
7f3cc09e2000-7f3cc11e2000 rw-p 00000000 00:00 0 
7f3cc11e2000-7f3cc11e3000 ---p 00000000 00:00 0 
7f3cc11e3000-7f3cc19e3000 rw-p 00000000 00:00 0 
7f3cc19e3000-7f3cc19e4000 ---p 00000000 00:00 0 
7f3cc19e4000-7f3cc21e4000 rw-p 00000000 00:00 0 
7f3cc21e4000-7f3cc21e5000 ---p 00000000 00:00 0 
7f3cc21e5000-7f3cc29e5000 rw-p 00000000 00:00 0 
7f3cc29e5000-7f3cc29e6000 ---p 00000000 00:00 0 
7f3cc29e6000-7f3cc31e6000 rw-p 00000000 00:00 0 
7f3cc31e6000-7f3cc31e7000 ---p 00000000 00:00 0 
7f3cc31e7000-7f3cc39e7000 rw-p 00000000 00:00 0 
7f3cc39e7000-7f3cc39e8000 ---p 00000000 00:00 0 
7f3cc39e8000-7f3cc41e8000 rw-p 00000000 00:00 0 
7f3cc422a000-7f3cc422e000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc422e000-7f3cc4241000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4241000-7f3cc4242000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cc4242000-7f3cc4244000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4244000-7f3cc4245000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cc4245000-7f3cc4285000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4285000-7f3cc42a5000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc42a5000-7f3cc42a6000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cc42a6000-7f3cc42e6000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc42e6000-7f3cc4306000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4306000-7f3cc4307000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cc4307000-7f3cc4347000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4347000-7f3cc4367000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4367000-7f3cc4368000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4368000-7f3cc4568000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4568000-7f3cc456b000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc456b000-7f3cc4618000 r--p 00000000 103:04 7349741                   /usr/share/fonts/TTF/DejaVuSans-Bold.ttf
7f3cc4618000-7f3cc46d1000 r--p 00000000 103:04 7419920                   /usr/share/fonts/TTF/DejaVuSans.ttf
7f3cc46d1000-7f3cc46d5000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc46d5000-7f3cc47d5000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc47d5000-7f3cc47e8000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc47e8000-7f3cc47e9000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cc47e9000-7f3cc47eb000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc47eb000-7f3cc47ec000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cc47ec000-7f3cc482c000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc482c000-7f3cc484c000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc484c000-7f3cc484d000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cc484d000-7f3cc488d000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc488d000-7f3cc48ad000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc48ad000-7f3cc48ae000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cc48ae000-7f3cc48ee000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4909000-7f3cc490d000 r--s 00000000 103:04 6208442                   /usr/bin/ruby
7f3cc490d000-7f3cc490e000 r-xp 00000000 00:01 10332                      /memfd:JITCode:QtQml (deleted)
7f3cc490e000-7f3cc490f000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc490f000-7f3cc4910000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4910000-7f3cc4911000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc4911000-7f3cc4913000 r--s 00000000 103:04 7148705                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/50969d1866bddaebb7faf948a0606293fb709f11.qmlc
7f3cc4913000-7f3cc4914000 r--s 00000000 103:04 7148664                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/8f9bcdf10b59027cfe62305e520906197f3ae6e7.qmlc
7f3cc4914000-7f3cc4915000 ---p 00000000 00:00 0 
7f3cc4915000-7f3cc5115000 rw-p 00000000 00:00 0 
7f3cc5115000-7f3cc5118000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cc5118000-7f3cc511a000 rw-s 00000000 00:01 11548                      /memfd:/.glXXXXXX (deleted)
7f3cc511a000-7f3cc511b000 r-xp 00000000 00:01 11547                      /memfd:JITCode:QtQml (deleted)
7f3cc511b000-7f3cc511c000 r-xp 00000000 00:01 11546                      /memfd:JITCode:QtQml (deleted)
7f3cc511c000-7f3cc511d000 rw-p 00000000 00:01 11545                      /memfd:unknown-usage:QtQml (deleted)
7f3cc511d000-7f3cc511e000 rw-p 00000000 00:01 11544                      /memfd:unknown-usage:QtQml (deleted)
7f3cc511e000-7f3cc511f000 rw-p 00000000 00:01 11543                      /memfd:unknown-usage:QtQml (deleted)
7f3cc511f000-7f3cc5120000 rw-p 00000000 00:01 11542                      /memfd:unknown-usage:QtQml (deleted)
7f3cc5120000-7f3cc5121000 rw-p 00000000 00:01 11541                      /memfd:unknown-usage:QtQml (deleted)
7f3cc5121000-7f3cc5122000 rw-p 00000000 00:01 11540                      /memfd:unknown-usage:QtQml (deleted)
7f3cc5122000-7f3cc5123000 rw-p 00000000 00:01 11539                      /memfd:unknown-usage:QtQml (deleted)
7f3cc5123000-7f3cc5124000 r-xp 00000000 00:01 11538                      /memfd:JITCode:QtQml (deleted)
7f3cc5124000-7f3cc5125000 r-xp 00000000 00:01 11537                      /memfd:JITCode:QtQml (deleted)
7f3cc5125000-7f3cc5126000 r-xp 00000000 00:01 11536                      /memfd:JITCode:QtQml (deleted)
7f3cc5126000-7f3cc5127000 rw-p 00000000 00:01 11535                      /memfd:unknown-usage:QtQml (deleted)
7f3cc5127000-7f3cc5128000 r--s 00000000 103:04 2492853                   /usr/lib/qt/qml/QtQuick/Controls/Styles/Desktop/FocusFrameStyle.qmlc
7f3cc5128000-7f3cc5129000 rw-p 00000000 00:01 11534                      /memfd:unknown-usage:QtQml (deleted)
7f3cc5129000-7f3cc512b000 r--s 00000000 103:04 2492681                   /usr/lib/qt/qml/QtQuick/Controls/Private/TableViewItemDelegateLoader.qmlc
7f3cc512b000-7f3cc512e000 r--s 00000000 103:04 2492693                   /usr/lib/qt/qml/QtQuick/Controls/Private/TreeViewItemDelegateLoader.qmlc
7f3cc512e000-7f3cc5135000 r--s 00000000 103:04 2492927                   /usr/lib/qt/qml/QtQuick/Controls/TreeView.qmlc
7f3cc5135000-7f3cc5142000 r--s 00000000 103:04 2490661                   /usr/lib/qt/qml/QtQuick/Controls/Private/BasicTableView.qmlc
7f3cc5142000-7f3cc514b000 r--s 00000000 103:04 2492768                   /usr/lib/qt/qml/QtQuick/Controls/Styles/Base/ScrollViewStyle.qmlc
7f3cc514b000-7f3cc514e000 r--s 00000000 103:04 2492721                   /usr/lib/qt/qml/QtQuick/Controls/Styles/Base/BasicTableViewStyle.qmlc
7f3cc514e000-7f3cc5150000 r--s 00000000 103:04 2492797                   /usr/lib/qt/qml/QtQuick/Controls/Styles/Base/TreeViewStyle.qmlc
7f3cc5150000-7f3cc5151000 r--s 00000000 103:04 2492914                   /usr/lib/qt/qml/QtQuick/Controls/TableViewColumn.qmlc
7f3cc5151000-7f3cc5153000 r--p 00000000 103:04 2359315                   /usr/lib/qt/qml/QtQml/Models.2/libmodelsplugin.so
7f3cc5153000-7f3cc5154000 r-xp 00002000 103:04 2359315                   /usr/lib/qt/qml/QtQml/Models.2/libmodelsplugin.so
7f3cc5154000-7f3cc5155000 r--p 00003000 103:04 2359315                   /usr/lib/qt/qml/QtQml/Models.2/libmodelsplugin.so
7f3cc5155000-7f3cc5156000 r--p 00003000 103:04 2359315                   /usr/lib/qt/qml/QtQml/Models.2/libmodelsplugin.so
7f3cc5156000-7f3cc5157000 rw-p 00004000 103:04 2359315                   /usr/lib/qt/qml/QtQml/Models.2/libmodelsplugin.so
7f3cc5157000-7f3cc515d000 r--s 00000000 103:04 7148662                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/40ae917579fc91a18d47cea875bd657cd9252bee.qmlc
7f3cc515d000-7f3cc5191000 r--p 00000000 103:04 6554873                   /usr/lib/ign-gazebo-4/plugins/gui/libEntityTree.so
7f3cc5191000-7f3cc51c9000 r-xp 00034000 103:04 6554873                   /usr/lib/ign-gazebo-4/plugins/gui/libEntityTree.so
7f3cc51c9000-7f3cc51de000 r--p 0006c000 103:04 6554873                   /usr/lib/ign-gazebo-4/plugins/gui/libEntityTree.so
7f3cc51de000-7f3cc51e2000 r--p 00080000 103:04 6554873                   /usr/lib/ign-gazebo-4/plugins/gui/libEntityTree.so
7f3cc51e2000-7f3cc51e3000 rw-p 00084000 103:04 6554873                   /usr/lib/ign-gazebo-4/plugins/gui/libEntityTree.so
7f3cc51e3000-7f3cc51e4000 rw-p 00000000 00:01 11533                      /memfd:unknown-usage:QtQml (deleted)
7f3cc51e4000-7f3cc51e5000 rw-p 00000000 00:01 11532                      /memfd:unknown-usage:QtQml (deleted)
7f3cc51e5000-7f3cc51e6000 rw-p 00000000 00:01 11531                      /memfd:unknown-usage:QtQml (deleted)
7f3cc51e6000-7f3cc51e7000 rw-p 00000000 00:01 11530                      /memfd:unknown-usage:QtQml (deleted)
7f3cc51e7000-7f3cc51e8000 rw-p 00000000 00:01 11529                      /memfd:unknown-usage:QtQml (deleted)
7f3cc51e8000-7f3cc51e9000 rw-p 00000000 00:01 11528                      /memfd:unknown-usage:QtQml (deleted)
7f3cc51e9000-7f3cc51ea000 r-xp 00000000 00:01 11527                      /memfd:JITCode:QtQml (deleted)
7f3cc51ea000-7f3cc51eb000 rw-p 00000000 00:01 8330                       /memfd:unknown-usage:QtQml (deleted)
7f3cc51eb000-7f3cc51ed000 r--s 00000000 103:04 7148660                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/972d7dfa3bd1414da68c24d1bbb5fcdcf86cab93.qmlc
7f3cc51ed000-7f3cc51f2000 r--s 00000000 103:04 7148661                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/b130e4ca3e2261c7e2c7801384b568fb96817d44.qmlc
7f3cc51f2000-7f3cc5252000 r--p 00000000 103:04 6554872                   /usr/lib/ign-gazebo-4/plugins/gui/libComponentInspector.so
7f3cc5252000-7f3cc52b4000 r-xp 00060000 103:04 6554872                   /usr/lib/ign-gazebo-4/plugins/gui/libComponentInspector.so
7f3cc52b4000-7f3cc52da000 r--p 000c2000 103:04 6554872                   /usr/lib/ign-gazebo-4/plugins/gui/libComponentInspector.so
7f3cc52da000-7f3cc52db000 ---p 000e8000 103:04 6554872                   /usr/lib/ign-gazebo-4/plugins/gui/libComponentInspector.so
7f3cc52db000-7f3cc52e1000 r--p 000e8000 103:04 6554872                   /usr/lib/ign-gazebo-4/plugins/gui/libComponentInspector.so
7f3cc52e1000-7f3cc52e2000 rw-p 000ee000 103:04 6554872                   /usr/lib/ign-gazebo-4/plugins/gui/libComponentInspector.so
7f3cc52e2000-7f3cc52e3000 rw-p 00000000 00:00 0 
7f3cc52e3000-7f3cc52e4000 r-xp 00000000 00:01 8329                       /memfd:JITCode:QtQml (deleted)
7f3cc52e4000-7f3cc52e5000 rw-p 00000000 00:01 8328                       /memfd:unknown-usage:QtQml (deleted)
7f3cc52e5000-7f3cc52e6000 rw-p 00000000 00:01 8327                       /memfd:unknown-usage:QtQml (deleted)
7f3cc52e6000-7f3cc52e7000 rw-p 00000000 00:01 8326                       /memfd:unknown-usage:QtQml (deleted)
7f3cc52e7000-7f3cc52e8000 rw-p 00000000 00:01 8325                       /memfd:unknown-usage:QtQml (deleted)
7f3cc52e8000-7f3cc52e9000 rw-p 00000000 00:01 8324                       /memfd:unknown-usage:QtQml (deleted)
7f3cc52e9000-7f3cc52ea000 rw-p 00000000 00:01 8323                       /memfd:unknown-usage:QtQml (deleted)
7f3cc52ea000-7f3cc52eb000 rw-p 00000000 00:01 8322                       /memfd:unknown-usage:QtQml (deleted)
7f3cc52eb000-7f3cc52ed000 r--s 00000000 103:04 7148647                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/488ebed6ac9239d16e8c8ae03b698671c3c3dafa.qmlc
7f3cc52ed000-7f3cc52fb000 r--p 00000000 103:04 6554879                   /usr/lib/ign-gazebo-4/plugins/gui/libShapes.so
7f3cc52fb000-7f3cc5311000 r-xp 0000e000 103:04 6554879                   /usr/lib/ign-gazebo-4/plugins/gui/libShapes.so
7f3cc5311000-7f3cc5318000 r--p 00024000 103:04 6554879                   /usr/lib/ign-gazebo-4/plugins/gui/libShapes.so
7f3cc5318000-7f3cc5319000 ---p 0002b000 103:04 6554879                   /usr/lib/ign-gazebo-4/plugins/gui/libShapes.so
7f3cc5319000-7f3cc531a000 r--p 0002b000 103:04 6554879                   /usr/lib/ign-gazebo-4/plugins/gui/libShapes.so
7f3cc531a000-7f3cc531b000 rw-p 0002c000 103:04 6554879                   /usr/lib/ign-gazebo-4/plugins/gui/libShapes.so
7f3cc531b000-7f3cc531c000 r-xp 00000000 00:01 8321                       /memfd:JITCode:QtQml (deleted)
7f3cc531c000-7f3cc531d000 r-xp 00000000 00:01 8320                       /memfd:JITCode:QtQml (deleted)
7f3cc531d000-7f3cc531e000 r-xp 00000000 00:01 8319                       /memfd:JITCode:QtQml (deleted)
7f3cc531e000-7f3cc531f000 rw-p 00000000 00:01 8318                       /memfd:unknown-usage:QtQml (deleted)
7f3cc531f000-7f3cc5320000 rw-p 00000000 00:01 8317                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5320000-7f3cc5321000 rw-p 00000000 00:01 8316                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5321000-7f3cc5322000 rw-p 00000000 00:01 8315                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5322000-7f3cc5323000 r-xp 00000000 00:01 8314                       /memfd:JITCode:QtQml (deleted)
7f3cc5323000-7f3cc5324000 r-xp 00000000 00:01 8313                       /memfd:JITCode:QtQml (deleted)
7f3cc5324000-7f3cc5325000 r-xp 00000000 00:01 8312                       /memfd:JITCode:QtQml (deleted)
7f3cc5325000-7f3cc5326000 r-xp 00000000 00:01 8311                       /memfd:JITCode:QtQml (deleted)
7f3cc5326000-7f3cc5327000 rw-p 00000000 00:01 8310                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5327000-7f3cc5328000 rw-p 00000000 00:01 8309                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5328000-7f3cc5329000 r-xp 00000000 00:01 8308                       /memfd:JITCode:QtQml (deleted)
7f3cc5329000-7f3cc532a000 rw-p 00000000 00:01 8307                       /memfd:unknown-usage:QtQml (deleted)
7f3cc532a000-7f3cc532b000 rw-p 00000000 00:01 8306                       /memfd:unknown-usage:QtQml (deleted)
7f3cc532b000-7f3cc532c000 rw-p 00000000 00:01 8305                       /memfd:unknown-usage:QtQml (deleted)
7f3cc532c000-7f3cc532d000 rw-p 00000000 00:01 8304                       /memfd:unknown-usage:QtQml (deleted)
7f3cc532d000-7f3cc532e000 r--s 00000000 103:04 7148659                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/70cff114ca970e3cc25b95d920c6bf0e2958498d.qmlc
7f3cc532e000-7f3cc5337000 r--s 00000000 103:04 7148654                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/5caf98264fd15dd15b88f4f8cf6501703ca0048f.qmlc
7f3cc5337000-7f3cc5350000 r--p 00000000 103:04 6554880                   /usr/lib/ign-gazebo-4/plugins/gui/libTransformControl.so
7f3cc5350000-7f3cc536f000 r-xp 00019000 103:04 6554880                   /usr/lib/ign-gazebo-4/plugins/gui/libTransformControl.so
7f3cc536f000-7f3cc537e000 r--p 00038000 103:04 6554880                   /usr/lib/ign-gazebo-4/plugins/gui/libTransformControl.so
7f3cc537e000-7f3cc537f000 ---p 00047000 103:04 6554880                   /usr/lib/ign-gazebo-4/plugins/gui/libTransformControl.so
7f3cc537f000-7f3cc5381000 r--p 00047000 103:04 6554880                   /usr/lib/ign-gazebo-4/plugins/gui/libTransformControl.so
7f3cc5381000-7f3cc5382000 rw-p 00049000 103:04 6554880                   /usr/lib/ign-gazebo-4/plugins/gui/libTransformControl.so
7f3cc5382000-7f3cc5383000 r-xp 00000000 00:01 8303                       /memfd:JITCode:QtQml (deleted)
7f3cc5383000-7f3cc5384000 r-xp 00000000 00:01 8302                       /memfd:JITCode:QtQml (deleted)
7f3cc5384000-7f3cc5385000 r-xp 00000000 00:01 8301                       /memfd:JITCode:QtQml (deleted)
7f3cc5385000-7f3cc5387000 r-xp 00000000 00:01 8300                       /memfd:JITCode:QtQml (deleted)
7f3cc5387000-7f3cc5388000 r-xp 00000000 00:01 8299                       /memfd:JITCode:QtQml (deleted)
7f3cc5388000-7f3cc5389000 r-xp 00000000 00:01 8298                       /memfd:JITCode:QtQml (deleted)
7f3cc5389000-7f3cc538a000 r-xp 00000000 00:01 8297                       /memfd:JITCode:QtQml (deleted)
7f3cc538a000-7f3cc538b000 r-xp 00000000 00:01 8296                       /memfd:JITCode:QtQml (deleted)
7f3cc538b000-7f3cc538c000 rw-p 00000000 00:01 8295                       /memfd:unknown-usage:QtQml (deleted)
7f3cc538c000-7f3cc538d000 rw-p 00000000 00:01 8294                       /memfd:unknown-usage:QtQml (deleted)
7f3cc538d000-7f3cc538e000 rw-p 00000000 00:01 8293                       /memfd:unknown-usage:QtQml (deleted)
7f3cc538e000-7f3cc538f000 rw-p 00000000 00:01 8292                       /memfd:unknown-usage:QtQml (deleted)
7f3cc538f000-7f3cc5390000 r-xp 00000000 00:01 8291                       /memfd:JITCode:QtQml (deleted)
7f3cc5390000-7f3cc5391000 rw-p 00000000 00:01 8290                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5391000-7f3cc5392000 rw-p 00000000 00:01 8289                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5392000-7f3cc5393000 rw-p 00000000 00:01 8288                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5393000-7f3cc5395000 r--s 00000000 103:04 7148657                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/701e4caa2cac0e225d5c11b5da5c5a4ed7ee128e.qmlc
7f3cc5395000-7f3cc539b000 r--s 00000000 103:04 7148640                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/a53a39f93417887b65f8457aef21f7c6ec8a194a.qmlc
7f3cc539b000-7f3cc53ad000 r--p 00000000 103:04 6554676                   /usr/lib/ign-gui-4/plugins/libWorldStats.so
7f3cc53ad000-7f3cc53c8000 r-xp 00012000 103:04 6554676                   /usr/lib/ign-gui-4/plugins/libWorldStats.so
7f3cc53c8000-7f3cc53d0000 r--p 0002d000 103:04 6554676                   /usr/lib/ign-gui-4/plugins/libWorldStats.so
7f3cc53d0000-7f3cc53d2000 r--p 00034000 103:04 6554676                   /usr/lib/ign-gui-4/plugins/libWorldStats.so
7f3cc53d2000-7f3cc53d3000 rw-p 00036000 103:04 6554676                   /usr/lib/ign-gui-4/plugins/libWorldStats.so
7f3cc53d3000-7f3cc53d4000 r-xp 00000000 00:01 8287                       /memfd:JITCode:QtQml (deleted)
7f3cc53d4000-7f3cc53d5000 r-xp 00000000 00:01 8286                       /memfd:JITCode:QtQml (deleted)
7f3cc53d5000-7f3cc53d6000 r-xp 00000000 00:01 8285                       /memfd:JITCode:QtQml (deleted)
7f3cc53d6000-7f3cc53d7000 r-xp 00000000 00:01 8284                       /memfd:JITCode:QtQml (deleted)
7f3cc53d7000-7f3cc53d8000 r-xp 00000000 00:01 8283                       /memfd:JITCode:QtQml (deleted)
7f3cc53d8000-7f3cc53d9000 r-xp 00000000 00:01 8282                       /memfd:JITCode:QtQml (deleted)
7f3cc53d9000-7f3cc53da000 r-xp 00000000 00:01 8281                       /memfd:JITCode:QtQml (deleted)
7f3cc53da000-7f3cc53db000 rw-p 00000000 00:01 8280                       /memfd:unknown-usage:QtQml (deleted)
7f3cc53db000-7f3cc53dc000 r-xp 00000000 00:01 8279                       /memfd:JITCode:QtQml (deleted)
7f3cc53dc000-7f3cc53dd000 rw-p 00000000 00:01 8278                       /memfd:unknown-usage:QtQml (deleted)
7f3cc53dd000-7f3cc53de000 rw-p 00000000 00:01 8277                       /memfd:unknown-usage:QtQml (deleted)
7f3cc53de000-7f3cc53df000 rw-p 00000000 00:01 8276                       /memfd:unknown-usage:QtQml (deleted)
7f3cc53df000-7f3cc53e0000 rw-p 00000000 00:01 8275                       /memfd:unknown-usage:QtQml (deleted)
7f3cc53e0000-7f3cc53e1000 rw-p 00000000 00:01 8274                       /memfd:unknown-usage:QtQml (deleted)
7f3cc53e1000-7f3cc53e2000 r-xp 00000000 00:01 8273                       /memfd:JITCode:QtQml (deleted)
7f3cc53e2000-7f3cc53e3000 rw-p 00000000 00:01 8272                       /memfd:unknown-usage:QtQml (deleted)
7f3cc53e3000-7f3cc53e4000 rw-p 00000000 00:01 8271                       /memfd:unknown-usage:QtQml (deleted)
7f3cc53e4000-7f3cc53e7000 r--s 00000000 103:04 7148643                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/5630e716b5258a054252fd0ff80e05b836693f20.qmlc
7f3cc53e7000-7f3cc53ea000 r--s 00000000 103:04 7148655                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/009da2c2e7501ab5df4022c5dcfc14f503d4ae71.qmlc
7f3cc53ea000-7f3cc53ee000 r--s 00000000 103:04 7148653                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/9bb9e5306fcdb065f711cabd15d59083d227888e.qmlc
7f3cc53ee000-7f3cc5402000 r--p 00000000 103:04 6554675                   /usr/lib/ign-gui-4/plugins/libWorldControl.so
7f3cc5402000-7f3cc5421000 r-xp 00014000 103:04 6554675                   /usr/lib/ign-gui-4/plugins/libWorldControl.so
7f3cc5421000-7f3cc542a000 r--p 00033000 103:04 6554675                   /usr/lib/ign-gui-4/plugins/libWorldControl.so
7f3cc542a000-7f3cc542b000 ---p 0003c000 103:04 6554675                   /usr/lib/ign-gui-4/plugins/libWorldControl.so
7f3cc542b000-7f3cc542d000 r--p 0003c000 103:04 6554675                   /usr/lib/ign-gui-4/plugins/libWorldControl.so
7f3cc542d000-7f3cc542e000 rw-p 0003e000 103:04 6554675                   /usr/lib/ign-gui-4/plugins/libWorldControl.so
7f3cc542e000-7f3cc542f000 r-xp 00000000 00:01 8270                       /memfd:JITCode:QtQml (deleted)
7f3cc542f000-7f3cc5430000 r-xp 00000000 00:01 8269                       /memfd:JITCode:QtQml (deleted)
7f3cc5430000-7f3cc5431000 r-xp 00000000 00:01 8268                       /memfd:JITCode:QtQml (deleted)
7f3cc5431000-7f3cc5432000 r--s 00000000 103:04 7210319                   /usr/share/icons/hicolor/icon-theme.cache
7f3cc5432000-7f3cc5433000 rw-p 00000000 00:01 8267                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5433000-7f3cc5434000 r-xp 00000000 00:01 8266                       /memfd:JITCode:QtQml (deleted)
7f3cc5434000-7f3cc5435000 r-xp 00000000 00:01 8265                       /memfd:JITCode:QtQml (deleted)
7f3cc5435000-7f3cc5436000 r-xp 00000000 00:01 8264                       /memfd:JITCode:QtQml (deleted)
7f3cc5436000-7f3cc5437000 r-xp 00000000 00:01 8263                       /memfd:JITCode:QtQml (deleted)
7f3cc5437000-7f3cc5438000 r-xp 00000000 00:01 8262                       /memfd:JITCode:QtQml (deleted)
7f3cc5438000-7f3cc5439000 rw-p 00000000 00:01 8261                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5439000-7f3cc543a000 r-xp 00000000 00:01 8260                       /memfd:JITCode:QtQml (deleted)
7f3cc543a000-7f3cc543b000 r-xp 00000000 00:01 8259                       /memfd:JITCode:QtQml (deleted)
7f3cc543b000-7f3cc543c000 rw-p 00000000 00:01 8258                       /memfd:unknown-usage:QtQml (deleted)
7f3cc543c000-7f3cc543d000 r-xp 00000000 00:01 8257                       /memfd:JITCode:QtQml (deleted)
7f3cc543d000-7f3cc543e000 rw-p 00000000 00:01 8256                       /memfd:unknown-usage:QtQml (deleted)
7f3cc543e000-7f3cc543f000 r-xp 00000000 00:01 8255                       /memfd:JITCode:QtQml (deleted)
7f3cc543f000-7f3cc5441000 r--s 00000000 103:04 2492658                   /usr/lib/qt/qml/QtQuick/Controls/Private/MenuContentScroller.qmlc
7f3cc5441000-7f3cc5446000 r--s 00000000 103:04 2492664                   /usr/lib/qt/qml/QtQuick/Controls/Private/ScrollBar.qmlc
7f3cc5446000-7f3cc544c000 r--s 00000000 103:04 2492666                   /usr/lib/qt/qml/QtQuick/Controls/Private/ScrollViewHelper.qmlc
7f3cc544c000-7f3cc544d000 r--s 00000000 103:04 2492652                   /usr/lib/qt/qml/QtQuick/Controls/Private/FocusFrame.qmlc
7f3cc544d000-7f3cc5453000 r--s 00000000 103:04 2492703                   /usr/lib/qt/qml/QtQuick/Controls/ScrollView.qmlc
7f3cc5453000-7f3cc5459000 r--s 00000000 103:04 2490667                   /usr/lib/qt/qml/QtQuick/Controls/Private/ColumnMenuContent.qmlc
7f3cc5459000-7f3cc545b000 r--p 00000000 103:04 2359318                   /usr/lib/qt/qml/QtQml/libqmlplugin.so
7f3cc545b000-7f3cc545c000 r-xp 00002000 103:04 2359318                   /usr/lib/qt/qml/QtQml/libqmlplugin.so
7f3cc545c000-7f3cc545d000 r--p 00003000 103:04 2359318                   /usr/lib/qt/qml/QtQml/libqmlplugin.so
7f3cc545d000-7f3cc545e000 r--p 00003000 103:04 2359318                   /usr/lib/qt/qml/QtQml/libqmlplugin.so
7f3cc545e000-7f3cc545f000 rw-p 00004000 103:04 2359318                   /usr/lib/qt/qml/QtQml/libqmlplugin.so
7f3cc545f000-7f3cc5466000 r--s 00000000 103:04 2492656                   /usr/lib/qt/qml/QtQuick/Controls/Private/MenuContentItem.qmlc
7f3cc5466000-7f3cc5468000 r--s 00000000 103:04 2490529                   /usr/lib/qt/qml/QtQuick/Controls/Menu.qmlc
7f3cc5468000-7f3cc546c000 r--s 00000000 103:04 2492644                   /usr/lib/qt/qml/QtQuick/Controls/Private/EditMenu_base.qmlc
7f3cc546c000-7f3cc546d000 r-xp 00000000 00:01 8254                       /memfd:JITCode:QtQml (deleted)
7f3cc546d000-7f3cc546e000 r-xp 00000000 00:01 8253                       /memfd:JITCode:QtQml (deleted)
7f3cc546e000-7f3cc546f000 r-xp 00000000 00:01 8252                       /memfd:JITCode:QtQml (deleted)
7f3cc546f000-7f3cc5470000 r-xp 00000000 00:01 8251                       /memfd:JITCode:QtQml (deleted)
7f3cc5470000-7f3cc5471000 r-xp 00000000 00:01 8250                       /memfd:JITCode:QtQml (deleted)
7f3cc5471000-7f3cc5472000 r-xp 00000000 00:01 8249                       /memfd:JITCode:QtQml (deleted)
7f3cc5472000-7f3cc5473000 r-xp 00000000 00:01 8248                       /memfd:JITCode:QtQml (deleted)
7f3cc5473000-7f3cc5474000 r-xp 00000000 00:01 8247                       /memfd:JITCode:QtQml (deleted)
7f3cc5474000-7f3cc5475000 r-xp 00000000 00:01 8246                       /memfd:JITCode:QtQml (deleted)
7f3cc5475000-7f3cc5476000 rw-p 00000000 00:01 8245                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5476000-7f3cc5477000 rw-p 00000000 00:01 8244                       /memfd:unknown-usage:QtQml (deleted)
7f3cc5477000-7f3cc5478000 r-xp 00000000 00:01 8243                       /memfd:JITCode:QtQml (deleted)
7f3cc5478000-7f3cc547a000 r--s 00000000 103:04 7148649                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/93c5179e4c385fd3c491009a4568888d24f7a261.qmlc
7f3cc547a000-7f3cc547c000 r--s 00000000 103:04 7148650                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/bd331da573d3d92d526df73386f8012fa903d391.qmlc
7f3cc547c000-7f3cc547e000 r--s 00000000 103:04 2492685                   /usr/lib/qt/qml/QtQuick/Controls/Private/TextHandle.qmlc
7f3cc547e000-7f3cc5480000 r--s 00000000 103:04 2492642                   /usr/lib/qt/qml/QtQuick/Controls/Private/EditMenu.qmlc
7f3cc5480000-7f3cc5485000 r--s 00000000 103:04 2492687                   /usr/lib/qt/qml/QtQuick/Controls/Private/TextInputWithHandles.qmlc
7f3cc5485000-7f3cc5487000 r--s 00000000 103:04 2492640                   /usr/lib/qt/qml/QtQuick/Controls/Private/Control.qmlc
7f3cc5487000-7f3cc548e000 r--s 00000000 103:04 2492707                   /usr/lib/qt/qml/QtQuick/Controls/SpinBox.qmlc
7f3cc548e000-7f3cc548f000 r--s 00000000 103:04 2492674                   /usr/lib/qt/qml/QtQuick/Controls/Private/Style.qmlc
7f3cc548f000-7f3cc5494000 r--s 00000000 103:04 2492772                   /usr/lib/qt/qml/QtQuick/Controls/Styles/Base/SpinBoxStyle.qmlc
7f3cc5494000-7f3cc5495000 r--s 00000000 103:04 7148639                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/137f4566d87be6403a6f5b0a5c76b218be3dad45.qmlc
7f3cc5495000-7f3cc549a000 r--s 00000000 103:04 7148651                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/de8ac8f4aa01277c3c74f7a7fe1beab9c419d870.qmlc
7f3cc549a000-7f3cc549f000 r--s 00000000 103:04 7144778                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/cf8d623f527b0eab66190dd2231fb4671b7c0d90.qmlc
7f3cc549f000-7f3cc54a9000 r--s 00000000 103:04 7148645                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/a3220b3a91a4ae408063eb6408bd1d687fb9a6c2.qmlc
7f3cc54a9000-7f3cc54ae000 r--p 00000000 103:04 6301562                   /usr/lib/qt/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so
7f3cc54ae000-7f3cc54b4000 r-xp 00005000 103:04 6301562                   /usr/lib/qt/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so
7f3cc54b4000-7f3cc54b7000 r--p 0000b000 103:04 6301562                   /usr/lib/qt/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so
7f3cc54b7000-7f3cc54b8000 ---p 0000e000 103:04 6301562                   /usr/lib/qt/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so
7f3cc54b8000-7f3cc54b9000 r--p 0000e000 103:04 6301562                   /usr/lib/qt/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so
7f3cc54b9000-7f3cc54ba000 rw-p 0000f000 103:04 6301562                   /usr/lib/qt/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.so
7f3cc54ba000-7f3cc54ce000 r--p 00000000 103:04 6554869                   /usr/lib/ign-gazebo-4/plugins/gui/IgnGazebo/libEntityContextMenu.so
7f3cc54ce000-7f3cc54e8000 r-xp 00014000 103:04 6554869                   /usr/lib/ign-gazebo-4/plugins/gui/IgnGazebo/libEntityContextMenu.so
7f3cc54e8000-7f3cc54f0000 r--p 0002e000 103:04 6554869                   /usr/lib/ign-gazebo-4/plugins/gui/IgnGazebo/libEntityContextMenu.so
7f3cc54f0000-7f3cc54f2000 r--p 00035000 103:04 6554869                   /usr/lib/ign-gazebo-4/plugins/gui/IgnGazebo/libEntityContextMenu.so
7f3cc54f2000-7f3cc54f3000 rw-p 00037000 103:04 6554869                   /usr/lib/ign-gazebo-4/plugins/gui/IgnGazebo/libEntityContextMenu.so
7f3cc54f3000-7f3cc54f5000 r--p 00000000 103:04 6301544                   /usr/lib/qt/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so
7f3cc54f5000-7f3cc54f6000 r-xp 00002000 103:04 6301544                   /usr/lib/qt/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so
7f3cc54f6000-7f3cc5501000 r--p 00003000 103:04 6301544                   /usr/lib/qt/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so
7f3cc5501000-7f3cc5502000 r--p 0000d000 103:04 6301544                   /usr/lib/qt/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so
7f3cc5502000-7f3cc5503000 rw-p 0000e000 103:04 6301544                   /usr/lib/qt/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so
7f3cc5503000-7f3cc550c000 r--p 00000000 103:04 6205689                   /usr/lib/libgomp.so.1.0.0
7f3cc550c000-7f3cc5536000 r-xp 00009000 103:04 6205689                   /usr/lib/libgomp.so.1.0.0
7f3cc5536000-7f3cc5541000 r--p 00033000 103:04 6205689                   /usr/lib/libgomp.so.1.0.0
7f3cc5541000-7f3cc5542000 ---p 0003e000 103:04 6205689                   /usr/lib/libgomp.so.1.0.0
7f3cc5542000-7f3cc5543000 r--p 0003e000 103:04 6205689                   /usr/lib/libgomp.so.1.0.0
7f3cc5543000-7f3cc5544000 rw-p 0003f000 103:04 6205689                   /usr/lib/libgomp.so.1.0.0
7f3cc5544000-7f3cc554f000 r--p 00000000 103:04 6192470                   /usr/lib/liblcms2.so.2.0.10
7f3cc554f000-7f3cc5587000 r-xp 0000b000 103:04 6192470                   /usr/lib/liblcms2.so.2.0.10
7f3cc5587000-7f3cc559c000 r--p 00043000 103:04 6192470                   /usr/lib/liblcms2.so.2.0.10
7f3cc559c000-7f3cc559e000 r--p 00057000 103:04 6192470                   /usr/lib/liblcms2.so.2.0.10
7f3cc559e000-7f3cc55a1000 rw-p 00059000 103:04 6192470                   /usr/lib/liblcms2.so.2.0.10
7f3cc55a1000-7f3cc55a3000 rw-p 00000000 00:00 0 
7f3cc55a3000-7f3cc55ad000 r--p 00000000 103:04 6192257                   /usr/lib/libjasper.so.4.0.0
7f3cc55ad000-7f3cc55f5000 r-xp 0000a000 103:04 6192257                   /usr/lib/libjasper.so.4.0.0
7f3cc55f5000-7f3cc5601000 r--p 00052000 103:04 6192257                   /usr/lib/libjasper.so.4.0.0
7f3cc5601000-7f3cc5602000 ---p 0005e000 103:04 6192257                   /usr/lib/libjasper.so.4.0.0
7f3cc5602000-7f3cc5605000 r--p 0005e000 103:04 6192257                   /usr/lib/libjasper.so.4.0.0
7f3cc5605000-7f3cc5606000 rw-p 00061000 103:04 6192257                   /usr/lib/libjasper.so.4.0.0
7f3cc5606000-7f3cc5609000 rw-p 00000000 00:00 0 
7f3cc5609000-7f3cc560d000 r--p 00000000 103:04 6192051                   /usr/lib/libIlmThread-2_5.so.25.0.2
7f3cc560d000-7f3cc560f000 r-xp 00004000 103:04 6192051                   /usr/lib/libIlmThread-2_5.so.25.0.2
7f3cc560f000-7f3cc5611000 r--p 00006000 103:04 6192051                   /usr/lib/libIlmThread-2_5.so.25.0.2
7f3cc5611000-7f3cc5612000 r--p 00007000 103:04 6192051                   /usr/lib/libIlmThread-2_5.so.25.0.2
7f3cc5612000-7f3cc5613000 rw-p 00008000 103:04 6192051                   /usr/lib/libIlmThread-2_5.so.25.0.2
7f3cc5613000-7f3cc5619000 r--p 00000000 103:04 6192055                   /usr/lib/libImath-2_5.so.25.0.2
7f3cc5619000-7f3cc5629000 r-xp 00006000 103:04 6192055                   /usr/lib/libImath-2_5.so.25.0.2
7f3cc5629000-7f3cc562b000 r--p 00016000 103:04 6192055                   /usr/lib/libImath-2_5.so.25.0.2
7f3cc562b000-7f3cc562c000 ---p 00018000 103:04 6192055                   /usr/lib/libImath-2_5.so.25.0.2
7f3cc562c000-7f3cc562d000 r--p 00018000 103:04 6192055                   /usr/lib/libImath-2_5.so.25.0.2
7f3cc562d000-7f3cc562e000 rw-p 00019000 103:04 6192055                   /usr/lib/libImath-2_5.so.25.0.2
7f3cc562e000-7f3cc5634000 r--p 00000000 103:04 6200331                   /usr/lib/libjpegxr.so.0.0.0
7f3cc5634000-7f3cc5669000 r-xp 00006000 103:04 6200331                   /usr/lib/libjpegxr.so.0.0.0
7f3cc5669000-7f3cc566f000 r--p 0003b000 103:04 6200331                   /usr/lib/libjpegxr.so.0.0.0
7f3cc566f000-7f3cc5670000 ---p 00041000 103:04 6200331                   /usr/lib/libjpegxr.so.0.0.0
7f3cc5670000-7f3cc5671000 r--p 00041000 103:04 6200331                   /usr/lib/libjpegxr.so.0.0.0
7f3cc5671000-7f3cc5672000 rw-p 00042000 103:04 6200331                   /usr/lib/libjpegxr.so.0.0.0
7f3cc5672000-7f3cc5674000 r--p 00000000 103:04 6163942                   /usr/lib/libmvec-2.32.so
7f3cc5674000-7f3cc5681000 r-xp 00002000 103:04 6163942                   /usr/lib/libmvec-2.32.so
7f3cc5681000-7f3cc569c000 r--p 0000f000 103:04 6163942                   /usr/lib/libmvec-2.32.so
7f3cc569c000-7f3cc569d000 r--p 00029000 103:04 6163942                   /usr/lib/libmvec-2.32.so
7f3cc569d000-7f3cc569e000 rw-p 0002a000 103:04 6163942                   /usr/lib/libmvec-2.32.so
7f3cc569e000-7f3cc56a0000 r--p 00000000 103:04 6202937                   /usr/lib/libogg.so.0.8.4
7f3cc56a0000-7f3cc56a3000 r-xp 00002000 103:04 6202937                   /usr/lib/libogg.so.0.8.4
7f3cc56a3000-7f3cc56a6000 r--p 00005000 103:04 6202937                   /usr/lib/libogg.so.0.8.4
7f3cc56a6000-7f3cc56a7000 ---p 00008000 103:04 6202937                   /usr/lib/libogg.so.0.8.4
7f3cc56a7000-7f3cc56a8000 r--p 00008000 103:04 6202937                   /usr/lib/libogg.so.0.8.4
7f3cc56a8000-7f3cc56a9000 rw-p 00009000 103:04 6202937                   /usr/lib/libogg.so.0.8.4
7f3cc56a9000-7f3cc56ad000 r--p 00000000 103:04 6194015                   /usr/lib/libsoxr.so.0.1.2
7f3cc56ad000-7f3cc56ec000 r-xp 00004000 103:04 6194015                   /usr/lib/libsoxr.so.0.1.2
7f3cc56ec000-7f3cc56f2000 r--p 00043000 103:04 6194015                   /usr/lib/libsoxr.so.0.1.2
7f3cc56f2000-7f3cc56f3000 ---p 00049000 103:04 6194015                   /usr/lib/libsoxr.so.0.1.2
7f3cc56f3000-7f3cc56f5000 r--p 00049000 103:04 6194015                   /usr/lib/libsoxr.so.0.1.2
7f3cc56f5000-7f3cc56f6000 rw-p 0004b000 103:04 6194015                   /usr/lib/libsoxr.so.0.1.2
7f3cc56f6000-7f3cc572b000 rw-p 00000000 00:00 0 
7f3cc572b000-7f3cc5734000 r--p 00000000 103:04 6186560                   /usr/lib/libtiff.so.5.5.0
7f3cc5734000-7f3cc5783000 r-xp 00009000 103:04 6186560                   /usr/lib/libtiff.so.5.5.0
7f3cc5783000-7f3cc57b3000 r--p 00058000 103:04 6186560                   /usr/lib/libtiff.so.5.5.0
7f3cc57b3000-7f3cc57b7000 r--p 00087000 103:04 6186560                   /usr/lib/libtiff.so.5.5.0
7f3cc57b7000-7f3cc57ba000 rw-p 0008b000 103:04 6186560                   /usr/lib/libtiff.so.5.5.0
7f3cc57ba000-7f3cc57bb000 rw-p 00000000 00:00 0 
7f3cc57bb000-7f3cc57d9000 r--p 00000000 103:04 6181795                   /usr/lib/libraw.so.20.0.0
7f3cc57d9000-7f3cc5855000 r-xp 0001e000 103:04 6181795                   /usr/lib/libraw.so.20.0.0
7f3cc5855000-7f3cc5874000 r--p 0009a000 103:04 6181795                   /usr/lib/libraw.so.20.0.0
7f3cc5874000-7f3cc5884000 r--p 000b8000 103:04 6181795                   /usr/lib/libraw.so.20.0.0
7f3cc5884000-7f3cc58c8000 rw-p 000c8000 103:04 6181795                   /usr/lib/libraw.so.20.0.0
7f3cc58c8000-7f3cc5910000 r--p 00000000 103:04 6192014                   /usr/lib/libIex-2_5.so.25.0.2
7f3cc5910000-7f3cc591f000 r-xp 00048000 103:04 6192014                   /usr/lib/libIex-2_5.so.25.0.2
7f3cc591f000-7f3cc592f000 r--p 00057000 103:04 6192014                   /usr/lib/libIex-2_5.so.25.0.2
7f3cc592f000-7f3cc5934000 r--p 00066000 103:04 6192014                   /usr/lib/libIex-2_5.so.25.0.2
7f3cc5934000-7f3cc5935000 rw-p 0006b000 103:04 6192014                   /usr/lib/libIex-2_5.so.25.0.2
7f3cc5935000-7f3cc5936000 r--p 00000000 103:04 6191343                   /usr/lib/libHalf-2_5.so.25.0.2
7f3cc5936000-7f3cc5937000 r-xp 00001000 103:04 6191343                   /usr/lib/libHalf-2_5.so.25.0.2
7f3cc5937000-7f3cc5978000 r--p 00002000 103:04 6191343                   /usr/lib/libHalf-2_5.so.25.0.2
7f3cc5978000-7f3cc5979000 r--p 00042000 103:04 6191343                   /usr/lib/libHalf-2_5.so.25.0.2
7f3cc5979000-7f3cc597a000 rw-p 00043000 103:04 6191343                   /usr/lib/libHalf-2_5.so.25.0.2
7f3cc597a000-7f3cc59b6000 r--p 00000000 103:04 6192043                   /usr/lib/libIlmImf-2_5.so.25.0.2
7f3cc59b6000-7f3cc5a63000 r-xp 0003c000 103:04 6192043                   /usr/lib/libIlmImf-2_5.so.25.0.2
7f3cc5a63000-7f3cc5c6d000 r--p 000e9000 103:04 6192043                   /usr/lib/libIlmImf-2_5.so.25.0.2
7f3cc5c6d000-7f3cc5c72000 r--p 002f2000 103:04 6192043                   /usr/lib/libIlmImf-2_5.so.25.0.2
7f3cc5c72000-7f3cc5c73000 rw-p 002f7000 103:04 6192043                   /usr/lib/libIlmImf-2_5.so.25.0.2
7f3cc5c73000-7f3cc5c74000 rw-p 00000000 00:00 0 
7f3cc5c74000-7f3cc5c7e000 r--p 00000000 103:04 6200334                   /usr/lib/libjxrglue.so.0.0.0
7f3cc5c7e000-7f3cc5c91000 r-xp 0000a000 103:04 6200334                   /usr/lib/libjxrglue.so.0.0.0
7f3cc5c91000-7f3cc5c96000 r--p 0001d000 103:04 6200334                   /usr/lib/libjxrglue.so.0.0.0
7f3cc5c96000-7f3cc5c98000 r--p 00021000 103:04 6200334                   /usr/lib/libjxrglue.so.0.0.0
7f3cc5c98000-7f3cc5c99000 rw-p 00023000 103:04 6200334                   /usr/lib/libjxrglue.so.0.0.0
7f3cc5c99000-7f3cc5c9a000 rw-p 00000000 00:00 0 
7f3cc5c9a000-7f3cc5c9d000 r--p 00000000 103:04 6205391                   /usr/lib/libva.so.2.1000.0
7f3cc5c9d000-7f3cc5cb5000 r-xp 00003000 103:04 6205391                   /usr/lib/libva.so.2.1000.0
7f3cc5cb5000-7f3cc5cc4000 r--p 0001b000 103:04 6205391                   /usr/lib/libva.so.2.1000.0
7f3cc5cc4000-7f3cc5cc5000 ---p 0002a000 103:04 6205391                   /usr/lib/libva.so.2.1000.0
7f3cc5cc5000-7f3cc5cc6000 r--p 0002a000 103:04 6205391                   /usr/lib/libva.so.2.1000.0
7f3cc5cc6000-7f3cc5cc7000 rw-p 0002b000 103:04 6205391                   /usr/lib/libva.so.2.1000.0
7f3cc5cc7000-7f3cc5cc9000 r--p 00000000 103:04 6248698                   /usr/lib/libxvidcore.so.4.3
7f3cc5cc9000-7f3cc5d4f000 r-xp 00002000 103:04 6248698                   /usr/lib/libxvidcore.so.4.3
7f3cc5d4f000-7f3cc5d62000 r--p 00088000 103:04 6248698                   /usr/lib/libxvidcore.so.4.3
7f3cc5d62000-7f3cc5d63000 r--p 0009a000 103:04 6248698                   /usr/lib/libxvidcore.so.4.3
7f3cc5d63000-7f3cc5d6d000 rw-p 0009b000 103:04 6248698                   /usr/lib/libxvidcore.so.4.3
7f3cc5d6d000-7f3cc5dd6000 rw-p 00000000 00:00 0 
7f3cc5dd6000-7f3cc5e3d000 r--p 00000000 103:04 6203383                   /usr/lib/libx265.so.192
7f3cc5e3d000-7f3cc6fc3000 r-xp 00067000 103:04 6203383                   /usr/lib/libx265.so.192
7f3cc6fc3000-7f3cc7046000 r--p 011ed000 103:04 6203383                   /usr/lib/libx265.so.192
7f3cc7046000-7f3cc7047000 ---p 01270000 103:04 6203383                   /usr/lib/libx265.so.192
7f3cc7047000-7f3cc7054000 r--p 01270000 103:04 6203383                   /usr/lib/libx265.so.192
7f3cc7054000-7f3cc7057000 rw-p 0127d000 103:04 6203383                   /usr/lib/libx265.so.192
7f3cc7057000-7f3cc7068000 rw-p 00000000 00:00 0 
7f3cc7068000-7f3cc706d000 r--p 00000000 103:04 6236434                   /usr/lib/libx264.so.160
7f3cc706d000-7f3cc71f3000 r-xp 00005000 103:04 6236434                   /usr/lib/libx264.so.160
7f3cc71f3000-7f3cc722b000 r--p 0018b000 103:04 6236434                   /usr/lib/libx264.so.160
7f3cc722b000-7f3cc722d000 r--p 001c2000 103:04 6236434                   /usr/lib/libx264.so.160
7f3cc722d000-7f3cc722e000 rw-p 001c4000 103:04 6236434                   /usr/lib/libx264.so.160
7f3cc722e000-7f3cc7327000 rw-p 00000000 00:00 0 
7f3cc7327000-7f3cc733b000 r--p 00000000 103:04 6209438                   /usr/lib/libvorbisenc.so.2.0.12
7f3cc733b000-7f3cc733e000 r-xp 00014000 103:04 6209438                   /usr/lib/libvorbisenc.so.2.0.12
7f3cc733e000-7f3cc73b5000 r--p 00017000 103:04 6209438                   /usr/lib/libvorbisenc.so.2.0.12
7f3cc73b5000-7f3cc73d1000 r--p 0008d000 103:04 6209438                   /usr/lib/libvorbisenc.so.2.0.12
7f3cc73d1000-7f3cc73d2000 rw-p 000a9000 103:04 6209438                   /usr/lib/libvorbisenc.so.2.0.12
7f3cc73d2000-7f3cc73d6000 r--p 00000000 103:04 6191816                   /usr/lib/libvorbis.so.0.4.9
7f3cc73d6000-7f3cc73ec000 r-xp 00004000 103:04 6191816                   /usr/lib/libvorbis.so.0.4.9
7f3cc73ec000-7f3cc73fd000 r--p 0001a000 103:04 6191816                   /usr/lib/libvorbis.so.0.4.9
7f3cc73fd000-7f3cc73fe000 ---p 0002b000 103:04 6191816                   /usr/lib/libvorbis.so.0.4.9
7f3cc73fe000-7f3cc73ff000 r--p 0002b000 103:04 6191816                   /usr/lib/libvorbis.so.0.4.9
7f3cc73ff000-7f3cc7400000 rw-p 0002c000 103:04 6191816                   /usr/lib/libvorbis.so.0.4.9
7f3cc7400000-7f3cc7402000 r--p 00000000 103:04 6194032                   /usr/lib/libtheoraenc.so.1.1.2
7f3cc7402000-7f3cc7424000 r-xp 00002000 103:04 6194032                   /usr/lib/libtheoraenc.so.1.1.2
7f3cc7424000-7f3cc7436000 r--p 00024000 103:04 6194032                   /usr/lib/libtheoraenc.so.1.1.2
7f3cc7436000-7f3cc7437000 ---p 00036000 103:04 6194032                   /usr/lib/libtheoraenc.so.1.1.2
7f3cc7437000-7f3cc7438000 r--p 00036000 103:04 6194032                   /usr/lib/libtheoraenc.so.1.1.2
7f3cc7438000-7f3cc7439000 rw-p 00037000 103:04 6194032                   /usr/lib/libtheoraenc.so.1.1.2
7f3cc7439000-7f3cc743c000 r--p 00000000 103:04 6194216                   /usr/lib/libspeex.so.1.5.1
7f3cc743c000-7f3cc744c000 r-xp 00003000 103:04 6194216                   /usr/lib/libspeex.so.1.5.1
7f3cc744c000-7f3cc7452000 r--p 00013000 103:04 6194216                   /usr/lib/libspeex.so.1.5.1
7f3cc7452000-7f3cc7453000 r--p 00018000 103:04 6194216                   /usr/lib/libspeex.so.1.5.1
7f3cc7453000-7f3cc7454000 rw-p 00019000 103:04 6194216                   /usr/lib/libspeex.so.1.5.1
7f3cc7454000-7f3cc7468000 r--p 00000000 103:04 6209786                   /usr/lib/librav1e.so.0.3.4
7f3cc7468000-7f3cc75ed000 r-xp 00014000 103:04 6209786                   /usr/lib/librav1e.so.0.3.4
7f3cc75ed000-7f3cc763b000 r--p 00199000 103:04 6209786                   /usr/lib/librav1e.so.0.3.4
7f3cc763b000-7f3cc763c000 ---p 001e7000 103:04 6209786                   /usr/lib/librav1e.so.0.3.4
7f3cc763c000-7f3cc764e000 r--p 001e7000 103:04 6209786                   /usr/lib/librav1e.so.0.3.4
7f3cc764e000-7f3cc764f000 rw-p 001f9000 103:04 6209786                   /usr/lib/librav1e.so.0.3.4
7f3cc764f000-7f3cc7652000 r--p 00000000 103:04 6194179                   /usr/lib/libopus.so.0.8.0
7f3cc7652000-7f3cc7697000 r-xp 00003000 103:04 6194179                   /usr/lib/libopus.so.0.8.0
7f3cc7697000-7f3cc76aa000 r--p 00048000 103:04 6194179                   /usr/lib/libopus.so.0.8.0
7f3cc76aa000-7f3cc76ab000 ---p 0005b000 103:04 6194179                   /usr/lib/libopus.so.0.8.0
7f3cc76ab000-7f3cc76ac000 r--p 0005b000 103:04 6194179                   /usr/lib/libopus.so.0.8.0
7f3cc76ac000-7f3cc76ad000 rw-p 0005c000 103:04 6194179                   /usr/lib/libopus.so.0.8.0
7f3cc76ad000-7f3cc76b5000 r--p 00000000 103:04 6192074                   /usr/lib/libopenjp2.so.2.4.0
7f3cc76b5000-7f3cc76fd000 r-xp 00008000 103:04 6192074                   /usr/lib/libopenjp2.so.2.4.0
7f3cc76fd000-7f3cc770c000 r--p 00050000 103:04 6192074                   /usr/lib/libopenjp2.so.2.4.0
7f3cc770c000-7f3cc770e000 r--p 0005e000 103:04 6192074                   /usr/lib/libopenjp2.so.2.4.0
7f3cc770e000-7f3cc770f000 rw-p 00060000 103:04 6192074                   /usr/lib/libopenjp2.so.2.4.0
7f3cc770f000-7f3cc7716000 r--p 00000000 103:04 6249810                   /usr/lib/libmp3lame.so.0.0.0
7f3cc7716000-7f3cc7745000 r-xp 00007000 103:04 6249810                   /usr/lib/libmp3lame.so.0.0.0
7f3cc7745000-7f3cc7757000 r--p 00036000 103:04 6249810                   /usr/lib/libmp3lame.so.0.0.0
7f3cc7757000-7f3cc7758000 ---p 00048000 103:04 6249810                   /usr/lib/libmp3lame.so.0.0.0
7f3cc7758000-7f3cc7759000 r--p 00048000 103:04 6249810                   /usr/lib/libmp3lame.so.0.0.0
7f3cc7759000-7f3cc775a000 rw-p 00049000 103:04 6249810                   /usr/lib/libmp3lame.so.0.0.0
7f3cc775a000-7f3cc7787000 rw-p 00000000 00:00 0 
7f3cc7787000-7f3cc779a000 r--p 00000000 103:04 6203170                   /usr/lib/libaom.so.2.0.0
7f3cc779a000-7f3cc7d0c000 r-xp 00013000 103:04 6203170                   /usr/lib/libaom.so.2.0.0
7f3cc7d0c000-7f3cc7dfa000 r--p 00585000 103:04 6203170                   /usr/lib/libaom.so.2.0.0
7f3cc7dfa000-7f3cc7e08000 r--p 00672000 103:04 6203170                   /usr/lib/libaom.so.2.0.0
7f3cc7e08000-7f3cc7e0e000 rw-p 00680000 103:04 6203170                   /usr/lib/libaom.so.2.0.0
7f3cc7e0e000-7f3cc7e5b000 rw-p 00000000 00:00 0 
7f3cc7e5b000-7f3cc7e5d000 r--p 00000000 103:04 6163869                   /usr/lib/libdav1d.so.4.0.2
7f3cc7e5d000-7f3cc7f23000 r-xp 00002000 103:04 6163869                   /usr/lib/libdav1d.so.4.0.2
7f3cc7f23000-7f3cc7f4a000 r--p 000c8000 103:04 6163869                   /usr/lib/libdav1d.so.4.0.2
7f3cc7f4a000-7f3cc7f4b000 ---p 000ef000 103:04 6163869                   /usr/lib/libdav1d.so.4.0.2
7f3cc7f4b000-7f3cc7f4c000 r--p 000ef000 103:04 6163869                   /usr/lib/libdav1d.so.4.0.2
7f3cc7f4c000-7f3cc7f4d000 rw-p 000f0000 103:04 6163869                   /usr/lib/libdav1d.so.4.0.2
7f3cc7f4d000-7f3cc7f90000 rw-p 00000000 00:00 0 
7f3cc7f90000-7f3cc7f93000 r--p 00000000 103:04 6194077                   /usr/lib/libwebp.so.7.1.0
7f3cc7f93000-7f3cc7fe9000 r-xp 00003000 103:04 6194077                   /usr/lib/libwebp.so.7.1.0
7f3cc7fe9000-7f3cc7ffc000 r--p 00059000 103:04 6194077                   /usr/lib/libwebp.so.7.1.0
7f3cc7ffc000-7f3cc7ffd000 r--p 0006b000 103:04 6194077                   /usr/lib/libwebp.so.7.1.0
7f3cc7ffd000-7f3cc7ffe000 rw-p 0006c000 103:04 6194077                   /usr/lib/libwebp.so.7.1.0
7f3cc7ffe000-7f3cc8000000 rw-p 00000000 00:00 0 
7f3cc8000000-7f3cc8021000 rw-p 00000000 00:00 0 
7f3cc8021000-7f3ccc000000 ---p 00000000 00:00 0 
7f3ccc000000-7f3ccc021000 rw-p 00000000 00:00 0 
7f3ccc021000-7f3cd0000000 ---p 00000000 00:00 0 
7f3cd0000000-7f3cd0021000 rw-p 00000000 00:00 0 
7f3cd0021000-7f3cd4000000 ---p 00000000 00:00 0 
7f3cd4000000-7f3cd40a5000 rw-p 00000000 00:00 0 
7f3cd40a5000-7f3cd8000000 ---p 00000000 00:00 0 
7f3cd8000000-7f3cd8002000 r--s 00000000 103:04 7148648                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/0435a9459eec2fe15f5b54a2a35f3d05299c0df4.qmlc
7f3cd8002000-7f3cd8003000 r-xp 00000000 00:01 8242                       /memfd:JITCode:QtQml (deleted)
7f3cd8003000-7f3cd8004000 r-xp 00000000 00:01 8241                       /memfd:JITCode:QtQml (deleted)
7f3cd8004000-7f3cd8006000 r--s 00000000 103:04 7148646                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/3284febc9dfbe96b74dd20ded470522943ab2dbd.qmlc
7f3cd8006000-7f3cd8008000 r--s 00000000 103:04 7148658                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/ef22720b2a2917e83574c509c059bd9eb7b57162.qmlc
7f3cd8008000-7f3cd8009000 r--p 00000000 103:04 6202936                   /usr/lib/libvdpau.so.1.0.0
7f3cd8009000-7f3cd800a000 r-xp 00001000 103:04 6202936                   /usr/lib/libvdpau.so.1.0.0
7f3cd800a000-7f3cd800b000 r--p 00002000 103:04 6202936                   /usr/lib/libvdpau.so.1.0.0
7f3cd800b000-7f3cd800c000 r--p 00002000 103:04 6202936                   /usr/lib/libvdpau.so.1.0.0
7f3cd800c000-7f3cd800d000 rw-p 00003000 103:04 6202936                   /usr/lib/libvdpau.so.1.0.0
7f3cd800d000-7f3cd800f000 r--p 00000000 103:04 6201934                   /usr/lib/libva-x11.so.2.1000.0
7f3cd800f000-7f3cd8012000 r-xp 00002000 103:04 6201934                   /usr/lib/libva-x11.so.2.1000.0
7f3cd8012000-7f3cd8013000 r--p 00005000 103:04 6201934                   /usr/lib/libva-x11.so.2.1000.0
7f3cd8013000-7f3cd8014000 r--p 00005000 103:04 6201934                   /usr/lib/libva-x11.so.2.1000.0
7f3cd8014000-7f3cd8015000 rw-p 00006000 103:04 6201934                   /usr/lib/libva-x11.so.2.1000.0
7f3cd8015000-7f3cd801a000 r--p 00000000 103:04 6194062                   /usr/lib/libvpx.so.6.3.0
7f3cd801a000-7f3cd82c1000 r-xp 00005000 103:04 6194062                   /usr/lib/libvpx.so.6.3.0
7f3cd82c1000-7f3cd830e000 r--p 002ac000 103:04 6194062                   /usr/lib/libvpx.so.6.3.0
7f3cd830e000-7f3cd830f000 ---p 002f9000 103:04 6194062                   /usr/lib/libvpx.so.6.3.0
7f3cd830f000-7f3cd8312000 r--p 002f9000 103:04 6194062                   /usr/lib/libvpx.so.6.3.0
7f3cd8312000-7f3cd8313000 rw-p 002fc000 103:04 6194062                   /usr/lib/libvpx.so.6.3.0
7f3cd8313000-7f3cd831a000 rw-p 00000000 00:00 0 
7f3cd831a000-7f3cd8328000 r--p 00000000 103:04 6206352                   /usr/lib/libssh.so.4.8.6
7f3cd8328000-7f3cd8367000 r-xp 0000e000 103:04 6206352                   /usr/lib/libssh.so.4.8.6
7f3cd8367000-7f3cd8382000 r--p 0004d000 103:04 6206352                   /usr/lib/libssh.so.4.8.6
7f3cd8382000-7f3cd8384000 r--p 00067000 103:04 6206352                   /usr/lib/libssh.so.4.8.6
7f3cd8384000-7f3cd8386000 rw-p 00069000 103:04 6206352                   /usr/lib/libssh.so.4.8.6
7f3cd8386000-7f3cd83a3000 r--p 00000000 103:04 6248181                   /usr/lib/libsrt.so.1.4.2
7f3cd83a3000-7f3cd8425000 r-xp 0001d000 103:04 6248181                   /usr/lib/libsrt.so.1.4.2
7f3cd8425000-7f3cd8441000 r--p 0009f000 103:04 6248181                   /usr/lib/libsrt.so.1.4.2
7f3cd8441000-7f3cd8444000 r--p 000ba000 103:04 6248181                   /usr/lib/libsrt.so.1.4.2
7f3cd8444000-7f3cd8445000 rw-p 000bd000 103:04 6248181                   /usr/lib/libsrt.so.1.4.2
7f3cd8445000-7f3cd8447000 rw-p 00000000 00:00 0 
7f3cd8447000-7f3cd844e000 r--p 00000000 103:04 6247811                   /usr/lib/libmodplug.so.1.0.0
7f3cd844e000-7f3cd8487000 r-xp 00007000 103:04 6247811                   /usr/lib/libmodplug.so.1.0.0
7f3cd8487000-7f3cd8496000 r--p 00040000 103:04 6247811                   /usr/lib/libmodplug.so.1.0.0
7f3cd8496000-7f3cd8497000 ---p 0004f000 103:04 6247811                   /usr/lib/libmodplug.so.1.0.0
7f3cd8497000-7f3cd8498000 r--p 0004f000 103:04 6247811                   /usr/lib/libmodplug.so.1.0.0
7f3cd8498000-7f3cd8499000 rw-p 00050000 103:04 6247811                   /usr/lib/libmodplug.so.1.0.0
7f3cd8499000-7f3cd85d7000 rw-p 00000000 00:00 0 
7f3cd85d7000-7f3cd8605000 r--p 00000000 103:04 6192486                   /usr/lib/libxml2.so.2.9.10
7f3cd8605000-7f3cd86ee000 r-xp 0002e000 103:04 6192486                   /usr/lib/libxml2.so.2.9.10
7f3cd86ee000-7f3cd8739000 r--p 00117000 103:04 6192486                   /usr/lib/libxml2.so.2.9.10
7f3cd8739000-7f3cd8742000 r--p 00161000 103:04 6192486                   /usr/lib/libxml2.so.2.9.10
7f3cd8742000-7f3cd8743000 rw-p 0016a000 103:04 6192486                   /usr/lib/libxml2.so.2.9.10
7f3cd8743000-7f3cd8745000 rw-p 00000000 00:00 0 
7f3cd8745000-7f3cd8755000 r--p 00000000 103:04 6190851                   /usr/lib/libavutil.so.56.51.100
7f3cd8755000-7f3cd87bd000 r-xp 00010000 103:04 6190851                   /usr/lib/libavutil.so.56.51.100
7f3cd87bd000-7f3cd87d6000 r--p 00078000 103:04 6190851                   /usr/lib/libavutil.so.56.51.100
7f3cd87d6000-7f3cd87e2000 r--p 00090000 103:04 6190851                   /usr/lib/libavutil.so.56.51.100
7f3cd87e2000-7f3cd87e3000 rw-p 0009c000 103:04 6190851                   /usr/lib/libavutil.so.56.51.100
7f3cd87e3000-7f3cd89f2000 rw-p 00000000 00:00 0 
7f3cd89f2000-7f3cd8a6d000 r--p 00000000 103:04 6190835                   /usr/lib/libavcodec.so.58.91.100
7f3cd8a6d000-7f3cd9480000 r-xp 0007b000 103:04 6190835                   /usr/lib/libavcodec.so.58.91.100
7f3cd9480000-7f3cd97a4000 r--p 00a8e000 103:04 6190835                   /usr/lib/libavcodec.so.58.91.100
7f3cd97a4000-7f3cd97a5000 ---p 00db2000 103:04 6190835                   /usr/lib/libavcodec.so.58.91.100
7f3cd97a5000-7f3cd97f0000 r--p 00db2000 103:04 6190835                   /usr/lib/libavcodec.so.58.91.100
7f3cd97f0000-7f3cd981f000 rw-p 00dfd000 103:04 6190835                   /usr/lib/libavcodec.so.58.91.100
7f3cd981f000-7f3cd9ffc000 rw-p 00000000 00:00 0 
7f3cd9ffc000-7f3cd9ffd000 ---p 00000000 00:00 0 
7f3cd9ffd000-7f3cda7fd000 rw-p 00000000 00:00 0 
7f3cda7fd000-7f3cda7fe000 ---p 00000000 00:00 0 
7f3cda7fe000-7f3cdaffe000 rw-p 00000000 00:00 0 
7f3cdaffe000-7f3cdafff000 ---p 00000000 00:00 0 
7f3cdafff000-7f3cdb7ff000 rw-p 00000000 00:00 0 
7f3cdb7ff000-7f3cdb800000 ---p 00000000 00:00 0 
7f3cdb800000-7f3cdc000000 rw-p 00000000 00:00 0 
7f3cdc000000-7f3cdc021000 rw-p 00000000 00:00 0 
7f3cdc021000-7f3ce0000000 ---p 00000000 00:00 0 
7f3ce0000000-7f3ce04a5000 rw-p 00000000 00:00 0 
7f3ce04a5000-7f3ce4000000 ---p 00000000 00:00 0 
7f3ce4000000-7f3ce4003000 r--s 00000000 103:04 7148644                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/96d4f30dfcadbda886f9274fe316bd75ae1e19f0.qmlc
7f3ce4003000-7f3ce4004000 r--p 00000000 103:04 6184903                   /usr/lib/libva-drm.so.2.1000.0
7f3ce4004000-7f3ce4005000 r-xp 00001000 103:04 6184903                   /usr/lib/libva-drm.so.2.1000.0
7f3ce4005000-7f3ce4006000 r--p 00002000 103:04 6184903                   /usr/lib/libva-drm.so.2.1000.0
7f3ce4006000-7f3ce4007000 r--p 00002000 103:04 6184903                   /usr/lib/libva-drm.so.2.1000.0
7f3ce4007000-7f3ce4008000 rw-p 00003000 103:04 6184903                   /usr/lib/libva-drm.so.2.1000.0
7f3ce4008000-7f3ce400c000 r--p 00000000 103:04 6214656                   /usr/lib/libmfx.so.1.34
7f3ce400c000-7f3ce4011000 r-xp 00004000 103:04 6214656                   /usr/lib/libmfx.so.1.34
7f3ce4011000-7f3ce4014000 r--p 00009000 103:04 6214656                   /usr/lib/libmfx.so.1.34
7f3ce4014000-7f3ce4015000 r--p 0000b000 103:04 6214656                   /usr/lib/libmfx.so.1.34
7f3ce4015000-7f3ce4016000 rw-p 0000c000 103:04 6214656                   /usr/lib/libmfx.so.1.34
7f3ce4016000-7f3ce4017000 r--p 00000000 103:04 6204211                   /usr/lib/libopencore-amrnb.so.0.0.3
7f3ce4017000-7f3ce4033000 r-xp 00001000 103:04 6204211                   /usr/lib/libopencore-amrnb.so.0.0.3
7f3ce4033000-7f3ce4040000 r--p 0001d000 103:04 6204211                   /usr/lib/libopencore-amrnb.so.0.0.3
7f3ce4040000-7f3ce4041000 r--p 00029000 103:04 6204211                   /usr/lib/libopencore-amrnb.so.0.0.3
7f3ce4041000-7f3ce4042000 rw-p 0002a000 103:04 6204211                   /usr/lib/libopencore-amrnb.so.0.0.3
7f3ce4042000-7f3ce4068000 r--p 00000000 103:04 6200326                   /usr/lib/libfreeimage-3.18.0.so
7f3ce4068000-7f3ce40d9000 r-xp 00026000 103:04 6200326                   /usr/lib/libfreeimage-3.18.0.so
7f3ce40d9000-7f3ce40f9000 r--p 00097000 103:04 6200326                   /usr/lib/libfreeimage-3.18.0.so
7f3ce40f9000-7f3ce40fd000 r--p 000b6000 103:04 6200326                   /usr/lib/libfreeimage-3.18.0.so
7f3ce40fd000-7f3ce4107000 rw-p 000ba000 103:04 6200326                   /usr/lib/libfreeimage-3.18.0.so
7f3ce4107000-7f3ce4142000 r--p 00000000 103:04 6190845                   /usr/lib/libavformat.so.58.45.100
7f3ce4142000-7f3ce42eb000 r-xp 0003b000 103:04 6190845                   /usr/lib/libavformat.so.58.45.100
7f3ce42eb000-7f3ce435a000 r--p 001e4000 103:04 6190845                   /usr/lib/libavformat.so.58.45.100
7f3ce435a000-7f3ce4379000 r--p 00252000 103:04 6190845                   /usr/lib/libavformat.so.58.45.100
7f3ce4379000-7f3ce4391000 rw-p 00271000 103:04 6190845                   /usr/lib/libavformat.so.58.45.100
7f3ce4391000-7f3ce4392000 ---p 00000000 00:00 0 
7f3ce4392000-7f3ce4b92000 rw-p 00000000 00:00 0 
7f3ce4b92000-7f3ce4b93000 ---p 00000000 00:00 0 
7f3ce4b93000-7f3ce5393000 rw-p 00000000 00:00 0 
7f3ce5393000-7f3ce5394000 ---p 00000000 00:00 0 
7f3ce5394000-7f3ce5b94000 rw-p 00000000 00:00 0 
7f3ce5b94000-7f3ce7150000 r-xp 00000000 103:04 6192498                   /usr/lib/libnvidia-glcore.so.455.45.01
7f3ce7150000-7f3ce7171000 rwxp 015bc000 103:04 6192498                   /usr/lib/libnvidia-glcore.so.455.45.01
7f3ce7171000-7f3ce7683000 r-xp 015dd000 103:04 6192498                   /usr/lib/libnvidia-glcore.so.455.45.01
7f3ce7683000-7f3ce7883000 ---p 01aef000 103:04 6192498                   /usr/lib/libnvidia-glcore.so.455.45.01
7f3ce7883000-7f3ce7f20000 rw-p 01aef000 103:04 6192498                   /usr/lib/libnvidia-glcore.so.455.45.01
7f3ce7f20000-7f3ce8000000 rw-p 00000000 00:00 0 
7f3ce8000000-7f3ce8057000 rw-p 00000000 00:00 0 
7f3ce8057000-7f3cec000000 ---p 00000000 00:00 0 
7f3cec000000-7f3cec002000 r--p 00000000 103:04 6194029                   /usr/lib/libtheoradec.so.1.1.4
7f3cec002000-7f3cec014000 r-xp 00002000 103:04 6194029                   /usr/lib/libtheoradec.so.1.1.4
7f3cec014000-7f3cec017000 r--p 00014000 103:04 6194029                   /usr/lib/libtheoradec.so.1.1.4
7f3cec017000-7f3cec018000 r--p 00016000 103:04 6194029                   /usr/lib/libtheoradec.so.1.1.4
7f3cec018000-7f3cec019000 rw-p 00017000 103:04 6194029                   /usr/lib/libtheoradec.so.1.1.4
7f3cec019000-7f3cec01b000 r--p 00000000 103:04 6185001                   /usr/lib/libgsm.so.1.0.13
7f3cec01b000-7f3cec024000 r-xp 00002000 103:04 6185001                   /usr/lib/libgsm.so.1.0.13
7f3cec024000-7f3cec025000 r--p 0000b000 103:04 6185001                   /usr/lib/libgsm.so.1.0.13
7f3cec025000-7f3cec026000 ---p 0000c000 103:04 6185001                   /usr/lib/libgsm.so.1.0.13
7f3cec026000-7f3cec027000 r--p 0000c000 103:04 6185001                   /usr/lib/libgsm.so.1.0.13
7f3cec027000-7f3cec028000 rw-p 0000d000 103:04 6185001                   /usr/lib/libgsm.so.1.0.13
7f3cec028000-7f3cec029000 r--p 00000000 103:04 6247919                   /usr/lib/libopencore-amrwb.so.0.0.3
7f3cec029000-7f3cec034000 r-xp 00001000 103:04 6247919                   /usr/lib/libopencore-amrwb.so.0.0.3
7f3cec034000-7f3cec03c000 r--p 0000c000 103:04 6247919                   /usr/lib/libopencore-amrwb.so.0.0.3
7f3cec03c000-7f3cec03d000 r--p 00013000 103:04 6247919                   /usr/lib/libopencore-amrwb.so.0.0.3
7f3cec03d000-7f3cec03e000 rw-p 00014000 103:04 6247919                   /usr/lib/libopencore-amrwb.so.0.0.3
7f3cec03e000-7f3cec040000 r--p 00000000 103:04 6194088                   /usr/lib/libwebpmux.so.3.0.5
7f3cec040000-7f3cec046000 r-xp 00002000 103:04 6194088                   /usr/lib/libwebpmux.so.3.0.5
7f3cec046000-7f3cec048000 r--p 00008000 103:04 6194088                   /usr/lib/libwebpmux.so.3.0.5
7f3cec048000-7f3cec049000 r--p 00009000 103:04 6194088                   /usr/lib/libwebpmux.so.3.0.5
7f3cec049000-7f3cec04a000 rw-p 0000a000 103:04 6194088                   /usr/lib/libwebpmux.so.3.0.5
7f3cec04a000-7f3cec04d000 r--p 00000000 103:04 6190859                   /usr/lib/libswresample.so.3.7.100
7f3cec04d000-7f3cec061000 r-xp 00003000 103:04 6190859                   /usr/lib/libswresample.so.3.7.100
7f3cec061000-7f3cec066000 r--p 00017000 103:04 6190859                   /usr/lib/libswresample.so.3.7.100
7f3cec066000-7f3cec068000 r--p 0001b000 103:04 6190859                   /usr/lib/libswresample.so.3.7.100
7f3cec068000-7f3cec069000 rw-p 0001d000 103:04 6190859                   /usr/lib/libswresample.so.3.7.100
7f3cec069000-7f3cec06e000 r--p 00000000 103:04 6193985                   /usr/lib/libbluray.so.2.3.0
7f3cec06e000-7f3cec0a3000 r-xp 00005000 103:04 6193985                   /usr/lib/libbluray.so.2.3.0
7f3cec0a3000-7f3cec0b6000 r--p 0003a000 103:04 6193985                   /usr/lib/libbluray.so.2.3.0
7f3cec0b6000-7f3cec0b8000 r--p 0004c000 103:04 6193985                   /usr/lib/libbluray.so.2.3.0
7f3cec0b8000-7f3cec0b9000 rw-p 0004e000 103:04 6193985                   /usr/lib/libbluray.so.2.3.0
7f3cec0b9000-7f3cec0c3000 r--p 00000000 103:04 6206884                   /usr/lib/libgts-0.7.so.5.0.1
7f3cec0c3000-7f3cec107000 r-xp 0000a000 103:04 6206884                   /usr/lib/libgts-0.7.so.5.0.1
7f3cec107000-7f3cec119000 r--p 0004e000 103:04 6206884                   /usr/lib/libgts-0.7.so.5.0.1
7f3cec119000-7f3cec11a000 r--p 0005f000 103:04 6206884                   /usr/lib/libgts-0.7.so.5.0.1
7f3cec11a000-7f3cec11b000 rw-p 00060000 103:04 6206884                   /usr/lib/libgts-0.7.so.5.0.1
7f3cec11b000-7f3cec11e000 r--p 00000000 103:04 6190862                   /usr/lib/libswscale.so.5.7.100
7f3cec11e000-7f3cec18f000 r-xp 00003000 103:04 6190862                   /usr/lib/libswscale.so.5.7.100
7f3cec18f000-7f3cec19f000 r--p 00074000 103:04 6190862                   /usr/lib/libswscale.so.5.7.100
7f3cec19f000-7f3cec1a0000 ---p 00084000 103:04 6190862                   /usr/lib/libswscale.so.5.7.100
7f3cec1a0000-7f3cec1a1000 r--p 00084000 103:04 6190862                   /usr/lib/libswscale.so.5.7.100
7f3cec1a1000-7f3cec1a2000 rw-p 00085000 103:04 6190862                   /usr/lib/libswscale.so.5.7.100
7f3cec1a2000-7f3cec1aa000 rw-p 00000000 00:00 0 
7f3cec1aa000-7f3cec1d7000 r--p 00000000 103:04 6194539                   /usr/lib/libignition-common3-graphics.so.3.9.0
7f3cec1d7000-7f3cec270000 r-xp 0002d000 103:04 6194539                   /usr/lib/libignition-common3-graphics.so.3.9.0
7f3cec270000-7f3cec298000 r--p 000c6000 103:04 6194539                   /usr/lib/libignition-common3-graphics.so.3.9.0
7f3cec298000-7f3cec299000 ---p 000ee000 103:04 6194539                   /usr/lib/libignition-common3-graphics.so.3.9.0
7f3cec299000-7f3cec29c000 r--p 000ee000 103:04 6194539                   /usr/lib/libignition-common3-graphics.so.3.9.0
7f3cec29c000-7f3cec29d000 rw-p 000f1000 103:04 6194539                   /usr/lib/libignition-common3-graphics.so.3.9.0
7f3cec29d000-7f3cec29e000 rw-p 00000000 00:00 0 
7f3cec29e000-7f3cec2a2000 r--p 00000000 103:04 6194533                   /usr/lib/libignition-common3-av.so.3.9.0
7f3cec2a2000-7f3cec2a7000 r-xp 00004000 103:04 6194533                   /usr/lib/libignition-common3-av.so.3.9.0
7f3cec2a7000-7f3cec2a9000 r--p 00009000 103:04 6194533                   /usr/lib/libignition-common3-av.so.3.9.0
7f3cec2a9000-7f3cec2aa000 r--p 0000a000 103:04 6194533                   /usr/lib/libignition-common3-av.so.3.9.0
7f3cec2aa000-7f3cec2ab000 rw-p 0000b000 103:04 6194533                   /usr/lib/libignition-common3-av.so.3.9.0
7f3cec2ab000-7f3cec2ad000 rw-p 00000000 00:00 0 
7f3cec2ad000-7f3cec2db000 r--p 00000000 103:04 6240155                   /usr/lib/libignition-rendering4.so.4.1.0
7f3cec2db000-7f3cec31d000 r-xp 0002e000 103:04 6240155                   /usr/lib/libignition-rendering4.so.4.1.0
7f3cec31d000-7f3cec336000 r--p 00070000 103:04 6240155                   /usr/lib/libignition-rendering4.so.4.1.0
7f3cec336000-7f3cec33b000 r--p 00088000 103:04 6240155                   /usr/lib/libignition-rendering4.so.4.1.0
7f3cec33b000-7f3cec33c000 rw-p 0008d000 103:04 6240155                   /usr/lib/libignition-rendering4.so.4.1.0
7f3cec33c000-7f3cec396000 r--p 00000000 103:04 6222087                   /usr/lib/libignition-gazebo4-rendering.so.4.1.0
7f3cec396000-7f3cec40f000 r-xp 0005a000 103:04 6222087                   /usr/lib/libignition-gazebo4-rendering.so.4.1.0
7f3cec40f000-7f3cec433000 r--p 000d3000 103:04 6222087                   /usr/lib/libignition-gazebo4-rendering.so.4.1.0
7f3cec433000-7f3cec434000 ---p 000f7000 103:04 6222087                   /usr/lib/libignition-gazebo4-rendering.so.4.1.0
7f3cec434000-7f3cec43a000 r--p 000f7000 103:04 6222087                   /usr/lib/libignition-gazebo4-rendering.so.4.1.0
7f3cec43a000-7f3cec43b000 rw-p 000fd000 103:04 6222087                   /usr/lib/libignition-gazebo4-rendering.so.4.1.0
7f3cec43b000-7f3cec43c000 rw-p 00000000 00:00 0 
7f3cec43c000-7f3cec471000 r--p 00000000 103:04 6554875                   /usr/lib/ign-gazebo-4/plugins/gui/libGzScene3D.so
7f3cec471000-7f3cec4b3000 r-xp 00035000 103:04 6554875                   /usr/lib/ign-gazebo-4/plugins/gui/libGzScene3D.so
7f3cec4b3000-7f3cec4c6000 r--p 00077000 103:04 6554875                   /usr/lib/ign-gazebo-4/plugins/gui/libGzScene3D.so
7f3cec4c6000-7f3cec4c7000 ---p 0008a000 103:04 6554875                   /usr/lib/ign-gazebo-4/plugins/gui/libGzScene3D.so
7f3cec4c7000-7f3cec4cc000 r--p 0008a000 103:04 6554875                   /usr/lib/ign-gazebo-4/plugins/gui/libGzScene3D.so
7f3cec4cc000-7f3cec4cd000 rw-p 0008f000 103:04 6554875                   /usr/lib/ign-gazebo-4/plugins/gui/libGzScene3D.so
7f3cec4cd000-7f3cec4ce000 rw-p 00000000 00:01 7245                       /memfd:unknown-usage:QtQml (deleted)
7f3cec4ce000-7f3cec4cf000 rw-p 00000000 00:01 7244                       /memfd:unknown-usage:QtQml (deleted)
7f3cec4cf000-7f3cec4d0000 rw-p 00000000 00:01 7243                       /memfd:unknown-usage:QtQml (deleted)
7f3cec4d0000-7f3cec4d1000 r-xp 00000000 00:01 7242                       /memfd:JITCode:QtQml (deleted)
7f3cec4d1000-7f3cec4d2000 r-xp 00000000 00:01 7241                       /memfd:JITCode:QtQml (deleted)
7f3cec4d2000-7f3cec4d3000 r-xp 00000000 00:01 7240                       /memfd:JITCode:QtQml (deleted)
7f3cec4d3000-7f3cec4d4000 r-xp 00000000 00:01 7239                       /memfd:JITCode:QtQml (deleted)
7f3cec4d4000-7f3cec4d7000 r--s 00000000 103:04 7148641                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/6810438fd08a99266e19b20a5b9bee8bd06f3513.qmlc
7f3cec4d7000-7f3cec4da000 r--s 00000000 103:04 7148642                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/0783079cd48c8d47366204092c3d3392832d34a2.qmlc
7f3cec4da000-7f3cec4e0000 r--s 00000000 103:04 7144774                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/60c9053864f56027de3e793e7dafd8f337e1f0dc.qmlc
7f3cec4e0000-7f3cec4e3000 r--p 00000000 103:04 6163967                   /usr/lib/libnss_files-2.32.so
7f3cec4e3000-7f3cec4ea000 r-xp 00003000 103:04 6163967                   /usr/lib/libnss_files-2.32.so
7f3cec4ea000-7f3cec4ec000 r--p 0000a000 103:04 6163967                   /usr/lib/libnss_files-2.32.so
7f3cec4ec000-7f3cec4ed000 r--p 0000b000 103:04 6163967                   /usr/lib/libnss_files-2.32.so
7f3cec4ed000-7f3cec4ee000 rw-p 0000c000 103:04 6163967                   /usr/lib/libnss_files-2.32.so
7f3cec4ee000-7f3cec4f4000 rw-p 00000000 00:00 0 
7f3cec4f4000-7f3cec4f7000 r-xp 00000000 00:01 8240                       /memfd:JITCode:QtQml (deleted)
7f3cec4f7000-7f3cec4f8000 r-xp 00000000 00:01 8239                       /memfd:JITCode:QtQml (deleted)
7f3cec4f8000-7f3cec4f9000 r-xp 00000000 00:01 7238                       /memfd:JITCode:QtQml (deleted)
7f3cec4f9000-7f3cec4fa000 rw-p 00000000 00:01 7237                       /memfd:unknown-usage:QtQml (deleted)
7f3cec4fa000-7f3cec4fb000 r-xp 00000000 00:01 7236                       /memfd:JITCode:QtQml (deleted)
7f3cec4fb000-7f3cec4fc000 r-xp 00000000 00:01 7235                       /memfd:JITCode:QtQml (deleted)
7f3cec4fc000-7f3cec4fd000 r-xp 00000000 00:01 7234                       /memfd:JITCode:QtQml (deleted)
7f3cec4fd000-7f3cec500000 r-xp 00000000 00:01 7233                       /memfd:JITCode:QtQml (deleted)
7f3cec500000-7f3cec501000 r-xp 00000000 00:01 7232                       /memfd:JITCode:QtQml (deleted)
7f3cec501000-7f3cec502000 rw-p 00000000 00:01 7231                       /memfd:unknown-usage:QtQml (deleted)
7f3cec502000-7f3cec503000 r-xp 00000000 00:01 7230                       /memfd:JITCode:QtQml (deleted)
7f3cec503000-7f3cec504000 r-xp 00000000 00:01 7229                       /memfd:JITCode:QtQml (deleted)
7f3cec504000-7f3cec51d000 r--p 00000000 103:04 6194473                   /usr/lib/libQt5Svg.so.5.15.2
7f3cec51d000-7f3cec54b000 r-xp 00019000 103:04 6194473                   /usr/lib/libQt5Svg.so.5.15.2
7f3cec54b000-7f3cec556000 r--p 00047000 103:04 6194473                   /usr/lib/libQt5Svg.so.5.15.2
7f3cec556000-7f3cec557000 ---p 00052000 103:04 6194473                   /usr/lib/libQt5Svg.so.5.15.2
7f3cec557000-7f3cec55a000 r--p 00052000 103:04 6194473                   /usr/lib/libQt5Svg.so.5.15.2
7f3cec55a000-7f3cec55b000 rw-p 00055000 103:04 6194473                   /usr/lib/libQt5Svg.so.5.15.2
7f3cec55b000-7f3cec55e000 r--p 00000000 103:04 1182030                   /usr/lib/qt/plugins/imageformats/libqsvg.so
7f3cec55e000-7f3cec560000 r-xp 00003000 103:04 1182030                   /usr/lib/qt/plugins/imageformats/libqsvg.so
7f3cec560000-7f3cec561000 r--p 00005000 103:04 1182030                   /usr/lib/qt/plugins/imageformats/libqsvg.so
7f3cec561000-7f3cec562000 r--p 00005000 103:04 1182030                   /usr/lib/qt/plugins/imageformats/libqsvg.so
7f3cec562000-7f3cec563000 rw-p 00006000 103:04 1182030                   /usr/lib/qt/plugins/imageformats/libqsvg.so
7f3cec563000-7f3cec567000 r--p 00000000 103:04 6186524                   /usr/lib/libjpeg.so.8.2.2
7f3cec567000-7f3cec5aa000 r-xp 00004000 103:04 6186524                   /usr/lib/libjpeg.so.8.2.2
7f3cec5aa000-7f3cec5e4000 r--p 00047000 103:04 6186524                   /usr/lib/libjpeg.so.8.2.2
7f3cec5e4000-7f3cec5e5000 ---p 00081000 103:04 6186524                   /usr/lib/libjpeg.so.8.2.2
7f3cec5e5000-7f3cec5e6000 r--p 00081000 103:04 6186524                   /usr/lib/libjpeg.so.8.2.2
7f3cec5e6000-7f3cec5e7000 rw-p 00082000 103:04 6186524                   /usr/lib/libjpeg.so.8.2.2
7f3cec5e7000-7f3cec5eb000 r--p 00000000 103:04 1181905                   /usr/lib/qt/plugins/imageformats/libqjpeg.so
7f3cec5eb000-7f3cec5ef000 r-xp 00004000 103:04 1181905                   /usr/lib/qt/plugins/imageformats/libqjpeg.so
7f3cec5ef000-7f3cec5f0000 r--p 00008000 103:04 1181905                   /usr/lib/qt/plugins/imageformats/libqjpeg.so
7f3cec5f0000-7f3cec5f1000 ---p 00009000 103:04 1181905                   /usr/lib/qt/plugins/imageformats/libqjpeg.so
7f3cec5f1000-7f3cec5f2000 r--p 00009000 103:04 1181905                   /usr/lib/qt/plugins/imageformats/libqjpeg.so
7f3cec5f2000-7f3cec5f3000 rw-p 0000a000 103:04 1181905                   /usr/lib/qt/plugins/imageformats/libqjpeg.so
7f3cec5f3000-7f3cec5f6000 r--p 00000000 103:04 1181904                   /usr/lib/qt/plugins/imageformats/libqico.so
7f3cec5f6000-7f3cec5f9000 r-xp 00003000 103:04 1181904                   /usr/lib/qt/plugins/imageformats/libqico.so
7f3cec5f9000-7f3cec5fa000 r--p 00006000 103:04 1181904                   /usr/lib/qt/plugins/imageformats/libqico.so
7f3cec5fa000-7f3cec5fb000 ---p 00007000 103:04 1181904                   /usr/lib/qt/plugins/imageformats/libqico.so
7f3cec5fb000-7f3cec5fc000 r--p 00007000 103:04 1181904                   /usr/lib/qt/plugins/imageformats/libqico.so
7f3cec5fc000-7f3cec5fd000 rw-p 00008000 103:04 1181904                   /usr/lib/qt/plugins/imageformats/libqico.so
7f3cec5fd000-7f3cec6aa000 r--p 00000000 103:04 7349741                   /usr/share/fonts/TTF/DejaVuSans-Bold.ttf
7f3cec6aa000-7f3cec763000 r--p 00000000 103:04 7419920                   /usr/share/fonts/TTF/DejaVuSans.ttf
7f3cec763000-7f3cec764000 r--p 00000000 103:04 6186778                   /usr/lib/libxcb-present.so.0.0.0
7f3cec764000-7f3cec765000 r-xp 00001000 103:04 6186778                   /usr/lib/libxcb-present.so.0.0.0
7f3cec765000-7f3cec766000 r--p 00002000 103:04 6186778                   /usr/lib/libxcb-present.so.0.0.0
7f3cec766000-7f3cec767000 r--p 00002000 103:04 6186778                   /usr/lib/libxcb-present.so.0.0.0
7f3cec767000-7f3cec768000 rw-p 00003000 103:04 6186778                   /usr/lib/libxcb-present.so.0.0.0
7f3cec768000-7f3cec76a000 r--p 00000000 103:04 6186769                   /usr/lib/libxcb-dri3.so.0.0.0
7f3cec76a000-7f3cec76b000 r-xp 00002000 103:04 6186769                   /usr/lib/libxcb-dri3.so.0.0.0
7f3cec76b000-7f3cec76c000 r--p 00003000 103:04 6186769                   /usr/lib/libxcb-dri3.so.0.0.0
7f3cec76c000-7f3cec76d000 r--p 00003000 103:04 6186769                   /usr/lib/libxcb-dri3.so.0.0.0
7f3cec76d000-7f3cec76e000 rw-p 00004000 103:04 6186769                   /usr/lib/libxcb-dri3.so.0.0.0
7f3cec76e000-7f3cec7ee000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec7ee000-7f3cec7f2000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec7f2000-7f3cec8f2000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec8f2000-7f3cec905000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec905000-7f3cec906000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cec906000-7f3cec908000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec908000-7f3cec90c000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec90c000-7f3cec90d000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cec90d000-7f3cec94d000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec94d000-7f3cec96d000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec96d000-7f3cec96e000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cec96e000-7f3cec9ae000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec9ae000-7f3cec9ce000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3cec9ce000-7f3cec9cf000 rw-s 00000000 00:05 818                        /dev/nvidia0
7f3cec9cf000-7f3ceca0f000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3ceca0f000-7f3ceca11000 r--p 00000000 103:04 1181903                   /usr/lib/qt/plugins/imageformats/libqgif.so
7f3ceca11000-7f3ceca15000 r-xp 00002000 103:04 1181903                   /usr/lib/qt/plugins/imageformats/libqgif.so
7f3ceca15000-7f3ceca16000 r--p 00006000 103:04 1181903                   /usr/lib/qt/plugins/imageformats/libqgif.so
7f3ceca16000-7f3ceca17000 r--p 00006000 103:04 1181903                   /usr/lib/qt/plugins/imageformats/libqgif.so
7f3ceca17000-7f3ceca18000 rw-p 00007000 103:04 1181903                   /usr/lib/qt/plugins/imageformats/libqgif.so
7f3ceca18000-7f3ceca19000 r-xp 00000000 00:01 7228                       /memfd:JITCode:QtQml (deleted)
7f3ceca19000-7f3ceca1a000 r-xp 00000000 00:01 7227                       /memfd:JITCode:QtQml (deleted)
7f3ceca1a000-7f3ceca1b000 r-xp 00000000 00:01 7226                       /memfd:JITCode:QtQml (deleted)
7f3ceca1b000-7f3ceca1c000 r-xp 00000000 00:01 7225                       /memfd:JITCode:QtQml (deleted)
7f3ceca1c000-7f3ceca2c000 rwxp 00000000 00:00 0 
7f3ceca2c000-7f3ceca2d000 r-xp 00000000 00:01 7224                       /memfd:JITCode:QtQml (deleted)
7f3ceca2d000-7f3ceca2e000 rw-p 00000000 00:01 7223                       /memfd:unknown-usage:QtQml (deleted)
7f3ceca2e000-7f3ceca2f000 rw-p 00000000 00:01 7222                       /memfd:unknown-usage:QtQml (deleted)
7f3ceca2f000-7f3ceca30000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3ceca30000-7f3ceca31000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3ceca31000-7f3ceca32000 rw-s 00000000 00:05 817                        /dev/nvidiactl
7f3ceca32000-7f3cecbd7000 rw-s 00000000 00:01 2049                       /memfd:/.nvidia_drv.XXXXXX (deleted)
7f3cecbd7000-7f3cecbdc000 r--p 00000000 103:04 6190248                   /usr/lib/libdrm.so.2.4.0
7f3cecbdc000-7f3cecbe6000 r-xp 00005000 103:04 6190248                   /usr/lib/libdrm.so.2.4.0
7f3cecbe6000-7f3cecbea000 r--p 0000f000 103:04 6190248                   /usr/lib/libdrm.so.2.4.0
7f3cecbea000-7f3cecbeb000 r--p 00012000 103:04 6190248                   /usr/lib/libdrm.so.2.4.0
7f3cecbeb000-7f3cecbec000 rw-p 00013000 103:04 6190248                   /usr/lib/libdrm.so.2.4.0
7f3cecbec000-7f3cecbf0000 r--p 00000000 103:04 6189956                   /usr/lib/libXext.so.6.4.0
7f3cecbf0000-7f3cecbfb000 r-xp 00004000 103:04 6189956                   /usr/lib/libXext.so.6.4.0
7f3cecbfb000-7f3cecbff000 r--p 0000f000 103:04 6189956                   /usr/lib/libXext.so.6.4.0
7f3cecbff000-7f3cecc00000 r--p 00012000 103:04 6189956                   /usr/lib/libXext.so.6.4.0
7f3cecc00000-7f3cecc01000 rw-p 00013000 103:04 6189956                   /usr/lib/libXext.so.6.4.0
7f3cecc01000-7f3cecc04000 r-xp 00000000 103:04 6192524                   /usr/lib/libnvidia-tls.so.455.45.01
7f3cecc04000-7f3cece04000 ---p 00003000 103:04 6192524                   /usr/lib/libnvidia-tls.so.455.45.01
7f3cece04000-7f3cece05000 rw-p 00003000 103:04 6192524                   /usr/lib/libnvidia-tls.so.455.45.01
7f3cece05000-7f3ceceb0000 r-xp 00000000 103:04 6190621                   /usr/lib/libGLX_nvidia.so.455.45.01
7f3ceceb0000-7f3cecee5000 rwxp 000ab000 103:04 6190621                   /usr/lib/libGLX_nvidia.so.455.45.01
7f3cecee5000-7f3cecef4000 r-xp 000e0000 103:04 6190621                   /usr/lib/libGLX_nvidia.so.455.45.01
7f3cecef4000-7f3ced0f3000 ---p 000ef000 103:04 6190621                   /usr/lib/libGLX_nvidia.so.455.45.01
7f3ced0f3000-7f3ced117000 rw-p 000ee000 103:04 6190621                   /usr/lib/libGLX_nvidia.so.455.45.01
7f3ced117000-7f3ced119000 rw-p 00000000 00:00 0 
7f3ced119000-7f3ced125000 r--p 00000000 103:04 6186773                   /usr/lib/libxcb-glx.so.0.0.0
7f3ced125000-7f3ced12e000 r-xp 0000c000 103:04 6186773                   /usr/lib/libxcb-glx.so.0.0.0
7f3ced12e000-7f3ced133000 r--p 00015000 103:04 6186773                   /usr/lib/libxcb-glx.so.0.0.0
7f3ced133000-7f3ced134000 ---p 0001a000 103:04 6186773                   /usr/lib/libxcb-glx.so.0.0.0
7f3ced134000-7f3ced136000 r--p 0001a000 103:04 6186773                   /usr/lib/libxcb-glx.so.0.0.0
7f3ced136000-7f3ced137000 rw-p 0001c000 103:04 6186773                   /usr/lib/libxcb-glx.so.0.0.0
7f3ced137000-7f3ced13e000 r--p 00000000 103:04 1181925                   /usr/lib/qt/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f3ced13e000-7f3ced144000 r-xp 00007000 103:04 1181925                   /usr/lib/qt/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f3ced144000-7f3ced146000 r--p 0000d000 103:04 1181925                   /usr/lib/qt/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f3ced146000-7f3ced147000 ---p 0000f000 103:04 1181925                   /usr/lib/qt/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f3ced147000-7f3ced148000 r--p 0000f000 103:04 1181925                   /usr/lib/qt/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f3ced148000-7f3ced149000 rw-p 00010000 103:04 1181925                   /usr/lib/qt/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f3ced149000-7f3ced14c000 r--s 00000000 103:04 7148634                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/078787b89de49a54828bbbbf1f8168b96214b8ef.qmlc
7f3ced14c000-7f3ced14e000 r--s 00000000 103:04 7149359                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/ce436a7ecd4a737efb448683be5179cabe4c8b8e.qmlc
7f3ced14e000-7f3ced14f000 r--s 00000000 103:04 7148631                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/d5628ea4f39c27552c09519693a0d3af14c5af7d.qmlc
7f3ced14f000-7f3ced150000 r--s 00000000 103:04 2492950                   /usr/lib/qt/qml/QtQuick/Dialogs/WidgetFileDialog.qmlc
7f3ced150000-7f3ced153000 r--s 00000000 103:04 7148636                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/98bec59dde0a3d1f59cd2d9690970a82f1e0cd58.qmlc
7f3ced153000-7f3ced156000 r--s 00000000 103:04 7148632                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/26cb28a05fc3c3275865de08a07c9bae9e2e2a0b.qmlc
7f3ced156000-7f3ced15a000 r--s 00000000 103:04 7148633                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/d480a2afe217de91212a943da4e50c8d21196f64.qmlc
7f3ced15a000-7f3ced15c000 r--s 00000000 103:04 7148637                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/504ddf8f665915e2e3d4e032d368d31016d3d7c2.qmlc
7f3ced15c000-7f3ced163000 r--s 00000000 103:04 7148638                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/90f37e9051bc1a50c0dabd12812f3f9c2ba80163.qmlc
7f3ced163000-7f3ced16f000 r--p 00000000 103:04 2493052                   /usr/lib/qt/qml/QtQuick/PrivateWidgets/libwidgetsplugin.so
7f3ced16f000-7f3ced17d000 r-xp 0000c000 103:04 2493052                   /usr/lib/qt/qml/QtQuick/PrivateWidgets/libwidgetsplugin.so
7f3ced17d000-7f3ced185000 r--p 0001a000 103:04 2493052                   /usr/lib/qt/qml/QtQuick/PrivateWidgets/libwidgetsplugin.so
7f3ced185000-7f3ced186000 ---p 00022000 103:04 2493052                   /usr/lib/qt/qml/QtQuick/PrivateWidgets/libwidgetsplugin.so
7f3ced186000-7f3ced188000 r--p 00022000 103:04 2493052                   /usr/lib/qt/qml/QtQuick/PrivateWidgets/libwidgetsplugin.so
7f3ced188000-7f3ced189000 rw-p 00024000 103:04 2493052                   /usr/lib/qt/qml/QtQuick/PrivateWidgets/libwidgetsplugin.so
7f3ced189000-7f3ced18e000 r--s 00000000 103:04 7148716                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/fb5eeb1a6b248cc33ca9b0734e796faec7ce0712.qmlc
7f3ced18e000-7f3ced191000 r--s 00000000 103:04 7146183                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/3c385a03648679cccf6a3bca2117a48ab01cb6f9.qmlc
7f3ced191000-7f3ced193000 r--s 00000000 103:04 7148628                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/9a6be4bcf9a60d55197f55a5e66c64c4ed4f84f9.qmlc
7f3ced193000-7f3ced196000 r--s 00000000 103:04 7148630                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/3f4c52fb9a343b7b5efd1cbbb23b57678c652778.qmlc
7f3ced196000-7f3ced198000 r--s 00000000 103:04 7144769                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/1cb2ce0279fb4b41cf7fb5548bab80fb03168e6d.qmlc
7f3ced198000-7f3ced19b000 r--s 00000000 103:04 7144775                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/02867dd532a76ba84f9839b5f1d42285efc3cea7.qmlc
7f3ced19b000-7f3ced19d000 r--s 00000000 103:04 7144766                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/e17de5148f8d571a14952099575fcde9e245f37e.qmlc
7f3ced19d000-7f3ced1a0000 r--s 00000000 103:04 7144768                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/1feb09a45d326620c372a534add9f5d2c7dca7a2.qmlc
7f3ced1a0000-7f3ced1a3000 r--s 00000000 103:04 7144776                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/11772106b32a3e407c77508e64be37b149d57014.qmlc
7f3ced1a3000-7f3ced1d1000 r--p 00000000 103:04 2493494                   /usr/lib/qt/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so
7f3ced1d1000-7f3ced1fd000 r-xp 0002e000 103:04 2493494                   /usr/lib/qt/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so
7f3ced1fd000-7f3ced20c000 r--p 0005a000 103:04 2493494                   /usr/lib/qt/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so
7f3ced20c000-7f3ced216000 r--p 00068000 103:04 2493494                   /usr/lib/qt/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so
7f3ced216000-7f3ced217000 rw-p 00072000 103:04 2493494                   /usr/lib/qt/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so
7f3ced217000-7f3ced22d000 r--p 00000000 103:04 2492928                   /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
7f3ced22d000-7f3ced264000 r-xp 00016000 103:04 2492928                   /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
7f3ced264000-7f3ced27e000 r--p 0004d000 103:04 2492928                   /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
7f3ced27e000-7f3ced283000 r--p 00066000 103:04 2492928                   /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
7f3ced283000-7f3ced284000 rw-p 0006b000 103:04 2492928                   /usr/lib/qt/qml/QtQuick/Controls/libqtquickcontrolsplugin.so
7f3ced284000-7f3ced33d000 r--p 00000000 103:04 7419920                   /usr/share/fonts/TTF/DejaVuSans.ttf
7f3ced33d000-7f3ced42e000 r--s 00000000 103:04 6820313                   /home/acxz/.cache/fontconfig/923e285e415b1073c8df160bee08820f-le64.cache-7
7f3ced42e000-7f3ced42f000 r--s 00000000 103:04 2492947                   /usr/lib/qt/qml/QtQuick/Dialogs/WidgetColorDialog.qmlc
7f3ced42f000-7f3ced430000 r--s 00000000 103:04 7144767                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/ccc91ebccc9f8e6216daa16efa6e65de562c2c48.qmlc
7f3ced430000-7f3ced432000 r--s 00000000 103:04 7144777                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/ade26df0decaced74419bf07b4b0b194e0562ae8.qmlc
7f3ced432000-7f3ced434000 r--s 00000000 103:04 7148635                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/542526a9ba2d8a2b303e3bf4320991b3cfbc4596.qmlc
7f3ced434000-7f3ced436000 r--s 00000000 103:04 7144773                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/a7859523c9c9ef707d272880f90d332eda852d4b.qmlc
7f3ced436000-7f3ced437000 r--s 00000000 103:04 7142883                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/4f45f5de8f55aaf8ec2168cd13b1bd8af024ea7a.qmlc
7f3ced437000-7f3ced438000 r--s 00000000 103:04 7144770                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/3a89b93c9799f4690392293645fe927d2cb4f618.qmlc
7f3ced438000-7f3ced439000 r--s 00000000 103:04 2492689                   /usr/lib/qt/qml/QtQuick/Controls/Private/TextSingleton.qmlc
7f3ced439000-7f3ced43a000 r--s 00000000 103:04 2492676                   /usr/lib/qt/qml/QtQuick/Controls/Private/SystemPaletteSingleton.qmlc
7f3ced43a000-7f3ced440000 r--p 00000000 103:04 2753119                   /usr/lib/qt/qml/QtQuick/Window.2/libwindowplugin.so
7f3ced440000-7f3ced444000 r-xp 00006000 103:04 2753119                   /usr/lib/qt/qml/QtQuick/Window.2/libwindowplugin.so
7f3ced444000-7f3ced446000 r--p 0000a000 103:04 2753119                   /usr/lib/qt/qml/QtQuick/Window.2/libwindowplugin.so
7f3ced446000-7f3ced447000 ---p 0000c000 103:04 2753119                   /usr/lib/qt/qml/QtQuick/Window.2/libwindowplugin.so
7f3ced447000-7f3ced448000 r--p 0000c000 103:04 2753119                   /usr/lib/qt/qml/QtQuick/Window.2/libwindowplugin.so
7f3ced448000-7f3ced449000 rw-p 0000d000 103:04 2753119                   /usr/lib/qt/qml/QtQuick/Window.2/libwindowplugin.so
7f3ced449000-7f3ced44a000 r--s 00000000 103:04 2492670                   /usr/lib/qt/qml/QtQuick/Controls/Private/StackView.jsc
7f3ced44a000-7f3ced44b000 r--s 00000000 103:04 2492696                   /usr/lib/qt/qml/QtQuick/Controls/Private/style.jsc
7f3ced44b000-7f3ced44c000 r--s 00000000 103:04 2490665                   /usr/lib/qt/qml/QtQuick/Controls/Private/CalendarUtils.jsc
7f3ced44c000-7f3ced454000 r--s 00000000 103:04 2492709                   /usr/lib/qt/qml/QtQuick/Controls/SplitView.qmlc
7f3ced454000-7f3ced458000 r--s 00000000 103:04 7144772                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/42eddf477446a29654878b4c6db9bc40a417ab5a.qmlc
7f3ced458000-7f3ced464000 r--p 00000000 103:04 2490379                   /usr/lib/qt/qml/QtQuick/Layouts/libqquicklayoutsplugin.so
7f3ced464000-7f3ced473000 r-xp 0000c000 103:04 2490379                   /usr/lib/qt/qml/QtQuick/Layouts/libqquicklayoutsplugin.so
7f3ced473000-7f3ced47a000 r--p 0001b000 103:04 2490379                   /usr/lib/qt/qml/QtQuick/Layouts/libqquicklayoutsplugin.so
7f3ced47a000-7f3ced47b000 ---p 00022000 103:04 2490379                   /usr/lib/qt/qml/QtQuick/Layouts/libqquicklayoutsplugin.so
7f3ced47b000-7f3ced47e000 r--p 00022000 103:04 2490379                   /usr/lib/qt/qml/QtQuick/Layouts/libqquicklayoutsplugin.so
7f3ced47e000-7f3ced47f000 rw-p 00025000 103:04 2490379                   /usr/lib/qt/qml/QtQuick/Layouts/libqquicklayoutsplugin.so
7f3ced47f000-7f3ced489000 r--p 00000000 103:04 2492966                   /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
7f3ced489000-7f3ced49d000 r-xp 0000a000 103:04 2492966                   /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
7f3ced49d000-7f3ced4a7000 r--p 0001e000 103:04 2492966                   /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
7f3ced4a7000-7f3ced4aa000 r--p 00027000 103:04 2492966                   /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
7f3ced4aa000-7f3ced4ab000 rw-p 0002a000 103:04 2492966                   /usr/lib/qt/qml/QtQuick/Dialogs/libdialogplugin.so
7f3ced4ab000-7f3ced4b4000 r--s 00000000 103:04 6107209                   /var/cache/fontconfig/8087dfd67547a1134e1b315c0e6294c3-le64.cache-7
7f3ced4b4000-7f3ced4cb000 r--s 00000000 103:04 6107208                   /var/cache/fontconfig/ffabee0e3ed22a06206923f7fac5e1c0-le64.cache-7
7f3ced4cb000-7f3ced4d4000 r--s 00000000 103:04 6107207                   /var/cache/fontconfig/9f18a0df8bc37d83c3ea2376c06ff3af-le64.cache-7
7f3ced4d4000-7f3ced4df000 r--s 00000000 103:04 6107206                   /var/cache/fontconfig/25af1fc25f11a29b4bde933093acd51c-le64.cache-7
7f3ced4df000-7f3ced502000 r--s 00000000 103:04 6820354                   /home/acxz/.cache/fontconfig/f2e43df3287529323e79e7929dc44cc9-le64.cache-7
7f3ced502000-7f3ced505000 r--s 00000000 103:04 7144771                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/7972a0510eddb3cb58eda6008fc1713882c30279.qmlc
7f3ced505000-7f3ced510000 r--s 00000000 103:04 6107205                   /var/cache/fontconfig/2b34ab0a2048ea31d208a7dc116fb2f3-le64.cache-7
7f3ced510000-7f3ced51b000 r--s 00000000 103:04 6107204                   /var/cache/fontconfig/742beb53257c10cf578c07a0f3b00110-le64.cache-7
7f3ced51b000-7f3ced526000 r--s 00000000 103:04 6029591                   /var/cache/fontconfig/cb60976e0ef8d2b17a86838bea532586-le64.cache-7
7f3ced526000-7f3ced535000 r--s 00000000 103:04 6107157                   /var/cache/fontconfig/8d4af663993b81a124ee82e610bb31f9-le64.cache-7
7f3ced535000-7f3ced53b000 r--s 00000000 103:04 6113203                   /var/cache/fontconfig/b67b32625a2bb51b023d3814a918f351-le64.cache-7
7f3ced53b000-7f3ced54a000 r--s 00000000 103:04 6110477                   /var/cache/fontconfig/491f45a0a771fef1c10b9b647a97fb82-le64.cache-7
7f3ced54a000-7f3ced55e000 r--s 00000000 103:04 6107201                   /var/cache/fontconfig/614d1caaa4d7914789410f6367de37ca-le64.cache-7
7f3ced55e000-7f3ced563000 r--s 00000000 103:04 6113065                   /var/cache/fontconfig/6ba42ae0000f58711b5caaf10d690066-le64.cache-7
7f3ced563000-7f3ced56a000 r--s 00000000 103:04 6102767                   /var/cache/fontconfig/fb42211fc6e0c1a73c189e83d3791827-le64.cache-7
7f3ced56a000-7f3ced577000 r--s 00000000 103:04 6111209                   /var/cache/fontconfig/210c0516121708a580e22e6b1f9a103a-le64.cache-7
7f3ced577000-7f3ced584000 r--s 00000000 103:04 6112661                   /var/cache/fontconfig/f6b893a7224233d96cb72fd88691c0b4-le64.cache-7
7f3ced584000-7f3ced587000 r--s 00000000 103:04 6102694                   /var/cache/fontconfig/f349e9996a5320f6dd491cedd2b1f964-le64.cache-7
7f3ced587000-7f3ced61f000 r--s 00000000 103:04 6109268                   /var/cache/fontconfig/df311e82a1a24c41a75c2c930223552e-le64.cache-7
7f3ced61f000-7f3ced628000 r--p 00000000 103:04 2493250                   /usr/lib/qt/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.so
7f3ced628000-7f3ced634000 r-xp 00009000 103:04 2493250                   /usr/lib/qt/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.so
7f3ced634000-7f3ced6d9000 r--p 00015000 103:04 2493250                   /usr/lib/qt/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.so
7f3ced6d9000-7f3ced6dc000 r--p 000b9000 103:04 2493250                   /usr/lib/qt/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.so
7f3ced6dc000-7f3ced6dd000 rw-p 000bc000 103:04 2493250                   /usr/lib/qt/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.so
7f3ced6dd000-7f3ced6f3000 r--p 00000000 103:04 6214101                   /usr/lib/libQt5QuickControls2.so.5.15.2
7f3ced6f3000-7f3ced704000 r-xp 00016000 103:04 6214101                   /usr/lib/libQt5QuickControls2.so.5.15.2
7f3ced704000-7f3ced70c000 r--p 00027000 103:04 6214101                   /usr/lib/libQt5QuickControls2.so.5.15.2
7f3ced70c000-7f3ced70f000 r--p 0002e000 103:04 6214101                   /usr/lib/libQt5QuickControls2.so.5.15.2
7f3ced70f000-7f3ced710000 rw-p 00031000 103:04 6214101                   /usr/lib/libQt5QuickControls2.so.5.15.2
7f3ced710000-7f3ced792000 r--p 00000000 103:04 6214106                   /usr/lib/libQt5QuickTemplates2.so.5.15.2
7f3ced792000-7f3ced836000 r-xp 00082000 103:04 6214106                   /usr/lib/libQt5QuickTemplates2.so.5.15.2
7f3ced836000-7f3ced886000 r--p 00126000 103:04 6214106                   /usr/lib/libQt5QuickTemplates2.so.5.15.2
7f3ced886000-7f3ced887000 ---p 00176000 103:04 6214106                   /usr/lib/libQt5QuickTemplates2.so.5.15.2
7f3ced887000-7f3ced89b000 r--p 00176000 103:04 6214106                   /usr/lib/libQt5QuickTemplates2.so.5.15.2
7f3ced89b000-7f3ced89c000 rw-p 0018a000 103:04 6214106                   /usr/lib/libQt5QuickTemplates2.so.5.15.2
7f3ced89c000-7f3ced8ab000 r--p 00000000 103:04 2493491                   /usr/lib/qt/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.so
7f3ced8ab000-7f3ced8bb000 r-xp 0000f000 103:04 2493491                   /usr/lib/qt/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.so
7f3ced8bb000-7f3ced942000 r--p 0001f000 103:04 2493491                   /usr/lib/qt/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.so
7f3ced942000-7f3ced946000 r--p 000a5000 103:04 2493491                   /usr/lib/qt/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.so
7f3ced946000-7f3ced947000 rw-p 000a9000 103:04 2493491                   /usr/lib/qt/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.so
7f3ced947000-7f3ced94c000 r--p 00000000 103:04 6192151                   /usr/lib/libQt5QmlWorkerScript.so.5.15.2
7f3ced94c000-7f3ced952000 r-xp 00005000 103:04 6192151                   /usr/lib/libQt5QmlWorkerScript.so.5.15.2
7f3ced952000-7f3ced955000 r--p 0000b000 103:04 6192151                   /usr/lib/libQt5QmlWorkerScript.so.5.15.2
7f3ced955000-7f3ced956000 r--p 0000d000 103:04 6192151                   /usr/lib/libQt5QmlWorkerScript.so.5.15.2
7f3ced956000-7f3ced957000 rw-p 0000e000 103:04 6192151                   /usr/lib/libQt5QmlWorkerScript.so.5.15.2
7f3ced957000-7f3ced959000 r--p 00000000 103:04 2490373                   /usr/lib/qt/qml/QtQuick.2/libqtquick2plugin.so
7f3ced959000-7f3ced95a000 r-xp 00002000 103:04 2490373                   /usr/lib/qt/qml/QtQuick.2/libqtquick2plugin.so
7f3ced95a000-7f3ced95b000 r--p 00003000 103:04 2490373                   /usr/lib/qt/qml/QtQuick.2/libqtquick2plugin.so
7f3ced95b000-7f3ced95c000 r--p 00003000 103:04 2490373                   /usr/lib/qt/qml/QtQuick.2/libqtquick2plugin.so
7f3ced95c000-7f3ced95d000 rw-p 00004000 103:04 2490373                   /usr/lib/qt/qml/QtQuick.2/libqtquick2plugin.so
7f3ced95d000-7f3ced964000 r--s 00000000 103:04 7148700                   /home/acxz/.cache/ign-gazebo-gui/qmlcache/5b2121aef63192755e7fa30131090501014c6cc0.qmlc
7f3ced964000-7f3ced970000 ---p 00000000 00:01 8238                       /memfd:JSGCHeap:QtQml (deleted)
7f3ced970000-7f3cedd20000 rw-p 0000c000 00:01 8238                       /memfd:JSGCHeap:QtQml (deleted)
7f3cedd20000-7f3cedd64000 ---p 003bc000 00:01 8238                       /memfd:JSGCHeap:QtQml (deleted)
7f3cedd64000-7f3cedd65000 ---p 00000000 00:00 0 
7f3cedd65000-7f3cedf63000 rw-p 00001000 00:01 8237                       /memfd:JSVMStack:QtQml (deleted)
7f3cedf63000-7f3cedf65000 ---p 00000000 00:00 0 
7f3cedf65000-7f3cee3a3000 rw-p 00001000 00:01 8236                       /memfd:JSVMStack:QtQml (deleted)
7f3cee3a3000-7f3cee3a5000 ---p 00000000 00:00 0 
7f3cee3a5000-7f3ceeba5000 rw-p 00000000 00:00 0 
7f3ceeba5000-7f3ceeba8000 r--p 00000000 103:04 1181906                   /usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7f3ceeba8000-7f3ceeba9000 r-xp 00003000 103:04 1181906                   /usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7f3ceeba9000-7f3ceebaa000 r--p 00004000 103:04 1181906                   /usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7f3ceebaa000-7f3ceebab000 r--p 00004000 103:04 1181906                   /usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7f3ceebab000-7f3ceebac000 rw-p 00005000 103:04 1181906                   /usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7f3ceebac000-7f3ceebae000 r--p 00000000 103:04 6208545                   /usr/lib/libXfixes.so.3.1.0
7f3ceebae000-7f3ceebb1000 r-xp 00002000 103:04 6208545                   /usr/lib/libXfixes.so.3.1.0
7f3ceebb1000-7f3ceebb2000 r--p 00005000 103:04 6208545                   /usr/lib/libXfixes.so.3.1.0
7f3ceebb2000-7f3ceebb3000 ---p 00006000 103:04 6208545                   /usr/lib/libXfixes.so.3.1.0
7f3ceebb3000-7f3ceebb4000 r--p 00006000 103:04 6208545                   /usr/lib/libXfixes.so.3.1.0
7f3ceebb4000-7f3ceebb5000 rw-p 00007000 103:04 6208545                   /usr/lib/libXfixes.so.3.1.0
7f3ceebb5000-7f3ceebb7000 r--p 00000000 103:04 6190768                   /usr/lib/libXrender.so.1.3.0
7f3ceebb7000-7f3ceebbe000 r-xp 00002000 103:04 6190768                   /usr/lib/libXrender.so.1.3.0
7f3ceebbe000-7f3ceebc0000 r--p 00009000 103:04 6190768                   /usr/lib/libXrender.so.1.3.0
7f3ceebc0000-7f3ceebc1000 r--p 0000a000 103:04 6190768                   /usr/lib/libXrender.so.1.3.0
7f3ceebc1000-7f3ceebc2000 rw-p 0000b000 103:04 6190768                   /usr/lib/libXrender.so.1.3.0
7f3ceebc2000-7f3ceebc5000 r--p 00000000 103:04 6192179                   /usr/lib/libXcursor.so.1.0.2
7f3ceebc5000-7f3ceebca000 r-xp 00003000 103:04 6192179                   /usr/lib/libXcursor.so.1.0.2
7f3ceebca000-7f3ceebcc000 r--p 00008000 103:04 6192179                   /usr/lib/libXcursor.so.1.0.2
7f3ceebcc000-7f3ceebcd000 r--p 00009000 103:04 6192179                   /usr/lib/libXcursor.so.1.0.2
7f3ceebcd000-7f3ceebce000 rw-p 0000a000 103:04 6192179                   /usr/lib/libXcursor.so.1.0.2
7f3ceebce000-7f3ceebcf000 ---p 00000000 00:00 0 
7f3ceebcf000-7f3cef3cf000 rw-p 00000000 00:00 0 
7f3cef3cf000-7f3cef3d2000 r--p 00000000 103:04 6190704                   /usr/lib/libxcb-util.so.1.0.0
7f3cef3d2000-7f3cef3d3000 r-xp 00003000 103:04 6190704                   /usr/lib/libxcb-util.so.1.0.0
7f3cef3d3000-7f3cef3d4000 r--p 00004000 103:04 6190704                   /usr/lib/libxcb-util.so.1.0.0
7f3cef3d4000-7f3cef3d5000 ---p 00005000 103:04 6190704                   /usr/lib/libxcb-util.so.1.0.0
7f3cef3d5000-7f3cef3d6000 r--p 00005000 103:04 6190704                   /usr/lib/libxcb-util.so.1.0.0
7f3cef3d6000-7f3cef3d7000 rw-p 00006000 103:04 6190704                   /usr/lib/libxcb-util.so.1.0.0
7f3cef3d7000-7f3cef3e5000 r--p 00000000 103:04 6174414                   /usr/lib/libdbus-1.so.3.19.13
7f3cef3e5000-7f3cef414000 r-xp 0000e000 103:04 6174414                   /usr/lib/libdbus-1.so.3.19.13
7f3cef414000-7f3cef429000 r--p 0003d000 103:04 6174414                   /usr/lib/libdbus-1.so.3.19.13
7f3cef429000-7f3cef42b000 r--p 00051000 103:04 6174414                   /usr/lib/libdbus-1.so.3.19.13
7f3cef42b000-7f3cef42c000 rw-p 00053000 103:04 6174414                   /usr/lib/libdbus-1.so.3.19.13
7f3cef42c000-7f3cef430000 r--p 00000000 103:04 6194065                   /usr/lib/libexpat.so.1.6.12
7f3cef430000-7f3cef44d000 r-xp 00004000 103:04 6194065                   /usr/lib/libexpat.so.1.6.12
7f3cef44d000-7f3cef457000 r--p 00021000 103:04 6194065                   /usr/lib/libexpat.so.1.6.12
7f3cef457000-7f3cef458000 ---p 0002b000 103:04 6194065                   /usr/lib/libexpat.so.1.6.12
7f3cef458000-7f3cef45a000 r--p 0002b000 103:04 6194065                   /usr/lib/libexpat.so.1.6.12
7f3cef45a000-7f3cef45b000 rw-p 0002d000 103:04 6194065                   /usr/lib/libexpat.so.1.6.12
7f3cef45b000-7f3cef460000 r--p 00000000 103:04 6213031                   /usr/lib/libxkbcommon.so.0.0.0
7f3cef460000-7f3cef47f000 r-xp 00005000 103:04 6213031                   /usr/lib/libxkbcommon.so.0.0.0
7f3cef47f000-7f3cef49d000 r--p 00024000 103:04 6213031                   /usr/lib/libxkbcommon.so.0.0.0
7f3cef49d000-7f3cef49f000 r--p 00041000 103:04 6213031                   /usr/lib/libxkbcommon.so.0.0.0
7f3cef49f000-7f3cef4a0000 rw-p 00043000 103:04 6213031                   /usr/lib/libxkbcommon.so.0.0.0
7f3cef4a0000-7f3cef4a3000 r--p 00000000 103:04 6213270                   /usr/lib/libxkbcommon-x11.so.0.0.0
7f3cef4a3000-7f3cef4a6000 r-xp 00003000 103:04 6213270                   /usr/lib/libxkbcommon-x11.so.0.0.0
7f3cef4a6000-7f3cef4a7000 r--p 00006000 103:04 6213270                   /usr/lib/libxkbcommon-x11.so.0.0.0
7f3cef4a7000-7f3cef4a8000 ---p 00007000 103:04 6213270                   /usr/lib/libxkbcommon-x11.so.0.0.0
7f3cef4a8000-7f3cef4a9000 r--p 00007000 103:04 6213270                   /usr/lib/libxkbcommon-x11.so.0.0.0
7f3cef4a9000-7f3cef4aa000 rw-p 00008000 103:04 6213270                   /usr/lib/libxkbcommon-x11.so.0.0.0
7f3cef4aa000-7f3cef4af000 r--p 00000000 103:04 6247789                   /usr/lib/libICE.so.6.3.0
7f3cef4af000-7f3cef4bd000 r-xp 00005000 103:04 6247789                   /usr/lib/libICE.so.6.3.0
7f3cef4bd000-7f3cef4c2000 r--p 00013000 103:04 6247789                   /usr/lib/libICE.so.6.3.0
7f3cef4c2000-7f3cef4c3000 r--p 00017000 103:04 6247789                   /usr/lib/libICE.so.6.3.0
7f3cef4c3000-7f3cef4c4000 rw-p 00018000 103:04 6247789                   /usr/lib/libICE.so.6.3.0
7f3cef4c4000-7f3cef4c7000 rw-p 00000000 00:00 0 
7f3cef4c7000-7f3cef4c9000 r--p 00000000 103:04 6191384                   /usr/lib/libSM.so.6.0.1
7f3cef4c9000-7f3cef4cd000 r-xp 00002000 103:04 6191384                   /usr/lib/libSM.so.6.0.1
7f3cef4cd000-7f3cef4ce000 r--p 00006000 103:04 6191384                   /usr/lib/libSM.so.6.0.1
7f3cef4ce000-7f3cef4cf000 ---p 00007000 103:04 6191384                   /usr/lib/libSM.so.6.0.1
7f3cef4cf000-7f3cef4d0000 r--p 00007000 103:04 6191384                   /usr/lib/libSM.so.6.0.1
7f3cef4d0000-7f3cef4d1000 rw-p 00008000 103:04 6191384                   /usr/lib/libSM.so.6.0.1
7f3cef4d1000-7f3cef4e0000 r--p 00000000 103:04 6186821                   /usr/lib/libxcb-xinput.so.0.1.0
7f3cef4e0000-7f3cef4ec000 r-xp 0000f000 103:04 6186821                   /usr/lib/libxcb-xinput.so.0.1.0
7f3cef4ec000-7f3cef4f2000 r--p 0001b000 103:04 6186821                   /usr/lib/libxcb-xinput.so.0.1.0
7f3cef4f2000-7f3cef4f3000 ---p 00021000 103:04 6186821                   /usr/lib/libxcb-xinput.so.0.1.0
7f3cef4f3000-7f3cef4f5000 r--p 00021000 103:04 6186821                   /usr/lib/libxcb-xinput.so.0.1.0
7f3cef4f5000-7f3cef4f6000 rw-p 00023000 103:04 6186821                   /usr/lib/libxcb-xinput.so.0.1.0
7f3cef4f6000-7f3cef501000 r--p 00000000 103:04 6186824                   /usr/lib/libxcb-xkb.so.1.0.0
7f3cef501000-7f3cef50d000 r-xp 0000b000 103:04 6186824                   /usr/lib/libxcb-xkb.so.1.0.0
7f3cef50d000-7f3cef512000 r--p 00017000 103:04 6186824                   /usr/lib/libxcb-xkb.so.1.0.0
7f3cef512000-7f3cef513000 r--p 0001b000 103:04 6186824                   /usr/lib/libxcb-xkb.so.1.0.0
7f3cef513000-7f3cef514000 rw-p 0001c000 103:04 6186824                   /usr/lib/libxcb-xkb.so.1.0.0
7f3cef514000-7f3cef515000 r--p 00000000 103:04 6186818                   /usr/lib/libxcb-xinerama.so.0.0.0
7f3cef515000-7f3cef516000 r-xp 00001000 103:04 6186818                   /usr/lib/libxcb-xinerama.so.0.0.0
7f3cef516000-7f3cef517000 r--p 00002000 103:04 6186818                   /usr/lib/libxcb-xinerama.so.0.0.0
7f3cef517000-7f3cef518000 r--p 00002000 103:04 6186818                   /usr/lib/libxcb-xinerama.so.0.0.0
7f3cef518000-7f3cef519000 rw-p 00003000 103:04 6186818                   /usr/lib/libxcb-xinerama.so.0.0.0
7f3cef519000-7f3cef51c000 r--p 00000000 103:04 6186815                   /usr/lib/libxcb-xfixes.so.0.0.0
7f3cef51c000-7f3cef51f000 r-xp 00003000 103:04 6186815                   /usr/lib/libxcb-xfixes.so.0.0.0
7f3cef51f000-7f3cef520000 r--p 00006000 103:04 6186815                   /usr/lib/libxcb-xfixes.so.0.0.0
7f3cef520000-7f3cef521000 ---p 00007000 103:04 6186815                   /usr/lib/libxcb-xfixes.so.0.0.0
7f3cef521000-7f3cef522000 r--p 00007000 103:04 6186815                   /usr/lib/libxcb-xfixes.so.0.0.0
7f3cef522000-7f3cef523000 rw-p 00008000 103:04 6186815                   /usr/lib/libxcb-xfixes.so.0.0.0
7f3cef523000-7f3cef526000 r--p 00000000 103:04 6186808                   /usr/lib/libxcb-sync.so.1.0.0
7f3cef526000-7f3cef529000 r-xp 00003000 103:04 6186808                   /usr/lib/libxcb-sync.so.1.0.0
7f3cef529000-7f3cef52a000 r--p 00006000 103:04 6186808                   /usr/lib/libxcb-sync.so.1.0.0
7f3cef52a000-7f3cef52b000 ---p 00007000 103:04 6186808                   /usr/lib/libxcb-sync.so.1.0.0
7f3cef52b000-7f3cef52c000 r--p 00007000 103:04 6186808                   /usr/lib/libxcb-sync.so.1.0.0
7f3cef52c000-7f3cef52d000 rw-p 00008000 103:04 6186808                   /usr/lib/libxcb-sync.so.1.0.0
7f3cef52d000-7f3cef52e000 r--p 00000000 103:04 6186800                   /usr/lib/libxcb-shape.so.0.0.0
7f3cef52e000-7f3cef52f000 r-xp 00001000 103:04 6186800                   /usr/lib/libxcb-shape.so.0.0.0
7f3cef52f000-7f3cef530000 r--p 00002000 103:04 6186800                   /usr/lib/libxcb-shape.so.0.0.0
7f3cef530000-7f3cef531000 r--p 00002000 103:04 6186800                   /usr/lib/libxcb-shape.so.0.0.0
7f3cef531000-7f3cef532000 rw-p 00003000 103:04 6186800                   /usr/lib/libxcb-shape.so.0.0.0
7f3cef532000-7f3cef538000 r--p 00000000 103:04 6186788                   /usr/lib/libxcb-render.so.0.0.0
7f3cef538000-7f3cef53d000 r-xp 00006000 103:04 6186788                   /usr/lib/libxcb-render.so.0.0.0
7f3cef53d000-7f3cef53f000 r--p 0000b000 103:04 6186788                   /usr/lib/libxcb-render.so.0.0.0
7f3cef53f000-7f3cef540000 ---p 0000d000 103:04 6186788                   /usr/lib/libxcb-render.so.0.0.0
7f3cef540000-7f3cef541000 r--p 0000d000 103:04 6186788                   /usr/lib/libxcb-render.so.0.0.0
7f3cef541000-7f3cef542000 rw-p 0000e000 103:04 6186788                   /usr/lib/libxcb-render.so.0.0.0
7f3cef542000-7f3cef544000 r--p 00000000 103:04 6191328                   /usr/lib/libxcb-render-util.so.0.0.0
7f3cef544000-7f3cef545000 r-xp 00002000 103:04 6191328                   /usr/lib/libxcb-render-util.so.0.0.0
7f3cef545000-7f3cef546000 r--p 00003000 103:04 6191328                   /usr/lib/libxcb-render-util.so.0.0.0
7f3cef546000-7f3cef547000 r--p 00003000 103:04 6191328                   /usr/lib/libxcb-render-util.so.0.0.0
7f3cef547000-7f3cef548000 rw-p 00004000 103:04 6191328                   /usr/lib/libxcb-render-util.so.0.0.0
7f3cef548000-7f3cef54f000 r--p 00000000 103:04 6186781                   /usr/lib/libxcb-randr.so.0.1.0
7f3cef54f000-7f3cef554000 r-xp 00007000 103:04 6186781                   /usr/lib/libxcb-randr.so.0.1.0
7f3cef554000-7f3cef557000 r--p 0000c000 103:04 6186781                   /usr/lib/libxcb-randr.so.0.1.0
7f3cef557000-7f3cef558000 ---p 0000f000 103:04 6186781                   /usr/lib/libxcb-randr.so.0.1.0
7f3cef558000-7f3cef559000 r--p 0000f000 103:04 6186781                   /usr/lib/libxcb-randr.so.0.1.0
7f3cef559000-7f3cef55a000 rw-p 00010000 103:04 6186781                   /usr/lib/libxcb-randr.so.0.1.0
7f3cef55a000-7f3cef55b000 r--p 00000000 103:04 6190666                   /usr/lib/libxcb-keysyms.so.1.0.0
7f3cef55b000-7f3cef55c000 r-xp 00001000 103:04 6190666                   /usr/lib/libxcb-keysyms.so.1.0.0
7f3cef55c000-7f3cef55d000 r--p 00002000 103:04 6190666                   /usr/lib/libxcb-keysyms.so.1.0.0
7f3cef55d000-7f3cef55e000 r--p 00002000 103:04 6190666                   /usr/lib/libxcb-keysyms.so.1.0.0
7f3cef55e000-7f3cef55f000 rw-p 00003000 103:04 6190666                   /usr/lib/libxcb-keysyms.so.1.0.0
7f3cef55f000-7f3cef560000 r--p 00000000 103:04 6186803                   /usr/lib/libxcb-shm.so.0.0.0
7f3cef560000-7f3cef561000 r-xp 00001000 103:04 6186803                   /usr/lib/libxcb-shm.so.0.0.0
7f3cef561000-7f3cef562000 r--p 00002000 103:04 6186803                   /usr/lib/libxcb-shm.so.0.0.0
7f3cef562000-7f3cef563000 r--p 00002000 103:04 6186803                   /usr/lib/libxcb-shm.so.0.0.0
7f3cef563000-7f3cef564000 rw-p 00003000 103:04 6186803                   /usr/lib/libxcb-shm.so.0.0.0
7f3cef564000-7f3cef565000 r--p 00000000 103:04 6191332                   /usr/lib/libxcb-image.so.0.0.0
7f3cef565000-7f3cef567000 r-xp 00001000 103:04 6191332                   /usr/lib/libxcb-image.so.0.0.0
7f3cef567000-7f3cef568000 r--p 00003000 103:04 6191332                   /usr/lib/libxcb-image.so.0.0.0
7f3cef568000-7f3cef569000 r--p 00003000 103:04 6191332                   /usr/lib/libxcb-image.so.0.0.0
7f3cef569000-7f3cef56a000 rw-p 00004000 103:04 6191332                   /usr/lib/libxcb-image.so.0.0.0
7f3cef56a000-7f3cef56c000 r--p 00000000 103:04 6190676                   /usr/lib/libxcb-icccm.so.4.0.0
7f3cef56c000-7f3cef56d000 r-xp 00002000 103:04 6190676                   /usr/lib/libxcb-icccm.so.4.0.0
7f3cef56d000-7f3cef56e000 r--p 00003000 103:04 6190676                   /usr/lib/libxcb-icccm.so.4.0.0
7f3cef56e000-7f3cef56f000 r--p 00003000 103:04 6190676                   /usr/lib/libxcb-icccm.so.4.0.0
7f3cef56f000-7f3cef570000 rw-p 00004000 103:04 6190676                   /usr/lib/libxcb-icccm.so.4.0.0
7f3cef570000-7f3cef571000 r--p 00000000 103:04 6189122                   /usr/lib/libX11-xcb.so.1.0.0
7f3cef571000-7f3cef572000 r-xp 00001000 103:04 6189122                   /usr/lib/libX11-xcb.so.1.0.0
7f3cef572000-7f3cef573000 r--p 00002000 103:04 6189122                   /usr/lib/libX11-xcb.so.1.0.0
7f3cef573000-7f3cef574000 r--p 00002000 103:04 6189122                   /usr/lib/libX11-xcb.so.1.0.0
7f3cef574000-7f3cef575000 rw-p 00003000 103:04 6189122                   /usr/lib/libX11-xcb.so.1.0.0
7f3cef575000-7f3cef58a000 r--p 00000000 103:04 6185207                   /usr/lib/libQt5DBus.so.5.15.2
7f3cef58a000-7f3cef5df000 r-xp 00015000 103:04 6185207                   /usr/lib/libQt5DBus.so.5.15.2
7f3cef5df000-7f3cef5f8000 r--p 0006a000 103:04 6185207                   /usr/lib/libQt5DBus.so.5.15.2
7f3cef5f8000-7f3cef5fa000 r--p 00082000 103:04 6185207                   /usr/lib/libQt5DBus.so.5.15.2
7f3cef5fa000-7f3cef5fb000 rw-p 00084000 103:04 6185207                   /usr/lib/libQt5DBus.so.5.15.2
7f3cef5fb000-7f3cef603000 r--p 00000000 103:04 6190786                   /usr/lib/libfontconfig.so.1.12.0
7f3cef603000-7f3cef62a000 r-xp 00008000 103:04 6190786                   /usr/lib/libfontconfig.so.1.12.0
7f3cef62a000-7f3cef642000 r--p 0002f000 103:04 6190786                   /usr/lib/libfontconfig.so.1.12.0
7f3cef642000-7f3cef643000 ---p 00047000 103:04 6190786                   /usr/lib/libfontconfig.so.1.12.0
7f3cef643000-7f3cef645000 r--p 00047000 103:04 6190786                   /usr/lib/libfontconfig.so.1.12.0
7f3cef645000-7f3cef646000 rw-p 00049000 103:04 6190786                   /usr/lib/libfontconfig.so.1.12.0
7f3cef646000-7f3cef67a000 r--p 00000000 103:04 6190099                   /usr/lib/libQt5XcbQpa.so.5.15.2
7f3cef67a000-7f3cef70e000 r-xp 00034000 103:04 6190099                   /usr/lib/libQt5XcbQpa.so.5.15.2
7f3cef70e000-7f3cef76e000 r--p 000c8000 103:04 6190099                   /usr/lib/libQt5XcbQpa.so.5.15.2
7f3cef76e000-7f3cef76f000 ---p 00128000 103:04 6190099                   /usr/lib/libQt5XcbQpa.so.5.15.2
7f3cef76f000-7f3cef776000 r--p 00128000 103:04 6190099                   /usr/lib/libQt5XcbQpa.so.5.15.2
7f3cef776000-7f3cef777000 rw-p 0012f000 103:04 6190099                   /usr/lib/libQt5XcbQpa.so.5.15.2
7f3cef777000-7f3cef778000 rw-p 00000000 00:00 0 
7f3cef778000-7f3cef77a000 r--p 00000000 103:04 1181914                   /usr/lib/qt/plugins/platforms/libqxcb.so
7f3cef77a000-7f3cef77b000 r-xp 00002000 103:04 1181914                   /usr/lib/qt/plugins/platforms/libqxcb.so
7f3cef77b000-7f3cef77c000 r--p 00003000 103:04 1181914                   /usr/lib/qt/plugins/platforms/libqxcb.so
7f3cef77c000-7f3cef77d000 r--p 00003000 103:04 1181914                   /usr/lib/qt/plugins/platforms/libqxcb.so
7f3cef77d000-7f3cef77e000 rw-p 00004000 103:04 1181914                   /usr/lib/qt/plugins/platforms/libqxcb.so
7f3cef77e000-7f3cef780000 r--p 00000000 103:04 6246733                   /usr/lib/libXdmcp.so.6.0.0
7f3cef780000-7f3cef782000 r-xp 00002000 103:04 6246733                   /usr/lib/libXdmcp.so.6.0.0
7f3cef782000-7f3cef784000 r--p 00004000 103:04 6246733                   /usr/lib/libXdmcp.so.6.0.0
7f3cef784000-7f3cef785000 r--p 00005000 103:04 6246733                   /usr/lib/libXdmcp.so.6.0.0
7f3cef785000-7f3cef786000 rw-p 00006000 103:04 6246733                   /usr/lib/libXdmcp.so.6.0.0
7f3cef786000-7f3cef787000 r--p 00000000 103:04 6186746                   /usr/lib/libXau.so.6.0.0
7f3cef787000-7f3cef788000 r-xp 00001000 103:04 6186746                   /usr/lib/libXau.so.6.0.0
7f3cef788000-7f3cef789000 r--p 00002000 103:04 6186746                   /usr/lib/libXau.so.6.0.0
7f3cef789000-7f3cef78a000 r--p 00002000 103:04 6186746                   /usr/lib/libXau.so.6.0.0
7f3cef78a000-7f3cef78b000 rw-p 00003000 103:04 6186746                   /usr/lib/libXau.so.6.0.0
7f3cef78b000-7f3cef797000 r--p 00000000 103:04 6186837                   /usr/lib/libxcb.so.1.1.0
7f3cef797000-7f3cef7aa000 r-xp 0000c000 103:04 6186837                   /usr/lib/libxcb.so.1.1.0
7f3cef7aa000-7f3cef7b3000 r--p 0001f000 103:04 6186837                   /usr/lib/libxcb.so.1.1.0
7f3cef7b3000-7f3cef7b4000 r--p 00027000 103:04 6186837                   /usr/lib/libxcb.so.1.1.0
7f3cef7b4000-7f3cef7b5000 rw-p 00028000 103:04 6186837                   /usr/lib/libxcb.so.1.1.0
7f3cef7b5000-7f3cef7d1000 r--p 00000000 103:04 6189144                   /usr/lib/libX11.so.6.4.0
7f3cef7d1000-7f3cef85b000 r-xp 0001c000 103:04 6189144                   /usr/lib/libX11.so.6.4.0
7f3cef85b000-7f3cef8ef000 r--p 000a6000 103:04 6189144                   /usr/lib/libX11.so.6.4.0
7f3cef8ef000-7f3cef8f2000 r--p 00139000 103:04 6189144                   /usr/lib/libX11.so.6.4.0
7f3cef8f2000-7f3cef8f6000 rw-p 0013c000 103:04 6189144                   /usr/lib/libX11.so.6.4.0
7f3cef8f6000-7f3cef8f9000 r--p 00000000 103:04 6202853                   /usr/lib/libgraphite2.so.3.2.1
7f3cef8f9000-7f3cef913000 r-xp 00003000 103:04 6202853                   /usr/lib/libgraphite2.so.3.2.1
7f3cef913000-7f3cef918000 r--p 0001d000 103:04 6202853                   /usr/lib/libgraphite2.so.3.2.1
7f3cef918000-7f3cef91a000 r--p 00021000 103:04 6202853                   /usr/lib/libgraphite2.so.3.2.1
7f3cef91a000-7f3cef91b000 rw-p 00023000 103:04 6202853                   /usr/lib/libgraphite2.so.3.2.1
7f3cef91b000-7f3cef928000 r--p 00000000 103:04 6237713                   /usr/lib/libfreetype.so.6.17.4
7f3cef928000-7f3cef9ae000 r-xp 0000d000 103:04 6237713                   /usr/lib/libfreetype.so.6.17.4
7f3cef9ae000-7f3cef9e6000 r--p 00093000 103:04 6237713                   /usr/lib/libfreetype.so.6.17.4
7f3cef9e6000-7f3cef9e7000 ---p 000cb000 103:04 6237713                   /usr/lib/libfreetype.so.6.17.4
7f3cef9e7000-7f3cef9ee000 r--p 000cb000 103:04 6237713                   /usr/lib/libfreetype.so.6.17.4
7f3cef9ee000-7f3cef9ef000 rw-p 000d2000 103:04 6237713                   /usr/lib/libfreetype.so.6.17.4
7f3cef9ef000-7f3cef9f2000 r--p 00000000 103:04 6205352                   /usr/lib/libGLX.so.0.0.0
7f3cef9f2000-7f3cefa0c000 r-xp 00003000 103:04 6205352                   /usr/lib/libGLX.so.0.0.0
7f3cefa0c000-7f3cefa0f000 r--p 0001d000 103:04 6205352                   /usr/lib/libGLX.so.0.0.0
7f3cefa0f000-7f3cefa10000 ---p 00020000 103:04 6205352                   /usr/lib/libGLX.so.0.0.0
7f3cefa10000-7f3cefa11000 r--p 00020000 103:04 6205352                   /usr/lib/libGLX.so.0.0.0
7f3cefa11000-7f3cefa12000 rw-p 00021000 103:04 6205352                   /usr/lib/libGLX.so.0.0.0
7f3cefa12000-7f3cefa22000 rw-p 00000000 00:00 0 
7f3cefa22000-7f3cefa62000 r--p 00000000 103:04 6214763                   /usr/lib/libGLdispatch.so.0.0.0
7f3cefa62000-7f3cefa64000 r-xp 00040000 103:04 6214763                   /usr/lib/libGLdispatch.so.0.0.0
7f3cefa64000-7f3cefa9f000 r-xp 00042000 103:04 6214763                   /usr/lib/libGLdispatch.so.0.0.0
7f3cefa9f000-7f3cefaa0000 r-xp 0007d000 103:04 6214763                   /usr/lib/libGLdispatch.so.0.0.0
7f3cefaa0000-7f3cefab3000 r--p 0007e000 103:04 6214763                   /usr/lib/libGLdispatch.so.0.0.0
7f3cefab3000-7f3cefab4000 ---p 00091000 103:04 6214763                   /usr/lib/libGLdispatch.so.0.0.0
7f3cefab4000-7f3cefad0000 r--p 00091000 103:04 6214763                   /usr/lib/libGLdispatch.so.0.0.0
7f3cefad0000-7f3cefad1000 rw-p 000ad000 103:04 6214763                   /usr/lib/libGLdispatch.so.0.0.0
7f3cefad1000-7f3cefad9000 rw-p 00000000 00:00 0 
7f3cefad9000-7f3cefade000 r--p 00000000 103:04 6173509                   /usr/lib/libgpg-error.so.0.31.1
7f3cefade000-7f3cefaf3000 r-xp 00005000 103:04 6173509                   /usr/lib/libgpg-error.so.0.31.1
7f3cefaf3000-7f3cefafd000 r--p 0001a000 103:04 6173509                   /usr/lib/libgpg-error.so.0.31.1
7f3cefafd000-7f3cefafe000 ---p 00024000 103:04 6173509                   /usr/lib/libgpg-error.so.0.31.1
7f3cefafe000-7f3cefaff000 r--p 00024000 103:04 6173509                   /usr/lib/libgpg-error.so.0.31.1
7f3cefaff000-7f3cefb00000 rw-p 00025000 103:04 6173509                   /usr/lib/libgpg-error.so.0.31.1
7f3cefb00000-7f3cefb04000 r--p 00000000 103:04 6163981                   /usr/lib/libresolv-2.32.so
7f3cefb04000-7f3cefb12000 r-xp 00004000 103:04 6163981                   /usr/lib/libresolv-2.32.so
7f3cefb12000-7f3cefb15000 r--p 00012000 103:04 6163981                   /usr/lib/libresolv-2.32.so
7f3cefb15000-7f3cefb16000 ---p 00015000 103:04 6163981                   /usr/lib/libresolv-2.32.so
7f3cefb16000-7f3cefb17000 r--p 00015000 103:04 6163981                   /usr/lib/libresolv-2.32.so
7f3cefb17000-7f3cefb18000 rw-p 00016000 103:04 6163981                   /usr/lib/libresolv-2.32.so
7f3cefb18000-7f3cefb1a000 rw-p 00000000 00:00 0 
7f3cefb1a000-7f3cefb1c000 r--p 00000000 103:04 6174078                   /usr/lib/libkeyutils.so.1.10
7f3cefb1c000-7f3cefb1e000 r-xp 00002000 103:04 6174078                   /usr/lib/libkeyutils.so.1.10
7f3cefb1e000-7f3cefb1f000 r--p 00004000 103:04 6174078                   /usr/lib/libkeyutils.so.1.10
7f3cefb1f000-7f3cefb20000 r--p 00004000 103:04 6174078                   /usr/lib/libkeyutils.so.1.10
7f3cefb20000-7f3cefb21000 rw-p 00005000 103:04 6174078                   /usr/lib/libkeyutils.so.1.10
7f3cefb21000-7f3cefb24000 r--p 00000000 103:04 6174210                   /usr/lib/libkrb5support.so.0.1
7f3cefb24000-7f3cefb2b000 r-xp 00003000 103:04 6174210                   /usr/lib/libkrb5support.so.0.1
7f3cefb2b000-7f3cefb2e000 r--p 0000a000 103:04 6174210                   /usr/lib/libkrb5support.so.0.1
7f3cefb2e000-7f3cefb2f000 r--p 0000c000 103:04 6174210                   /usr/lib/libkrb5support.so.0.1
7f3cefb2f000-7f3cefb30000 rw-p 0000d000 103:04 6174210                   /usr/lib/libkrb5support.so.0.1
7f3cefb30000-7f3cefb39000 r--p 00000000 103:04 6182621                   /usr/lib/libhogweed.so.6.0
7f3cefb39000-7f3cefb4b000 r-xp 00009000 103:04 6182621                   /usr/lib/libhogweed.so.6.0
7f3cefb4b000-7f3cefb75000 r--p 0001b000 103:04 6182621                   /usr/lib/libhogweed.so.6.0
7f3cefb75000-7f3cefb77000 r--p 00044000 103:04 6182621                   /usr/lib/libhogweed.so.6.0
7f3cefb77000-7f3cefb78000 rw-p 00046000 103:04 6182621                   /usr/lib/libhogweed.so.6.0
7f3cefb78000-7f3cefb7b000 r--p 00000000 103:04 6181832                   /usr/lib/libtasn1.so.6.6.0
7f3cefb7b000-7f3cefb87000 r-xp 00003000 103:04 6181832                   /usr/lib/libtasn1.so.6.6.0
7f3cefb87000-7f3cefb8b000 r--p 0000f000 103:04 6181832                   /usr/lib/libtasn1.so.6.6.0
7f3cefb8b000-7f3cefb8c000 ---p 00013000 103:04 6181832                   /usr/lib/libtasn1.so.6.6.0
7f3cefb8c000-7f3cefb8d000 r--p 00013000 103:04 6181832                   /usr/lib/libtasn1.so.6.6.0
7f3cefb8d000-7f3cefb8e000 rw-p 00014000 103:04 6181832                   /usr/lib/libtasn1.so.6.6.0
7f3cefb8e000-7f3cefb9f000 r--p 00000000 103:04 6202869                   /usr/lib/libunistring.so.2.1.0
7f3cefb9f000-7f3cefbd4000 r-xp 00011000 103:04 6202869                   /usr/lib/libunistring.so.2.1.0
7f3cefbd4000-7f3cefd0b000 r--p 00046000 103:04 6202869                   /usr/lib/libunistring.so.2.1.0
7f3cefd0b000-7f3cefd0f000 r--p 0017c000 103:04 6202869                   /usr/lib/libunistring.so.2.1.0
7f3cefd0f000-7f3cefd10000 rw-p 00180000 103:04 6202869                   /usr/lib/libunistring.so.2.1.0
7f3cefd10000-7f3cefd39000 r--p 00000000 103:04 6201145                   /usr/lib/libp11-kit.so.0.3.0
7f3cefd39000-7f3cefdd7000 r-xp 00029000 103:04 6201145                   /usr/lib/libp11-kit.so.0.3.0
7f3cefdd7000-7f3cefe31000 r--p 000c7000 103:04 6201145                   /usr/lib/libp11-kit.so.0.3.0
7f3cefe31000-7f3cefe3b000 r--p 00120000 103:04 6201145                   /usr/lib/libp11-kit.so.0.3.0
7f3cefe3b000-7f3cefe45000 rw-p 0012a000 103:04 6201145                   /usr/lib/libp11-kit.so.0.3.0
7f3cefe45000-7f3cefe4d000 r--p 00000000 103:04 6200307                   /usr/lib/libtinyxml.so.0.2.6.2
7f3cefe4d000-7f3cefe56000 r-xp 00008000 103:04 6200307                   /usr/lib/libtinyxml.so.0.2.6.2
7f3cefe56000-7f3cefe5b000 r--p 00011000 103:04 6200307                   /usr/lib/libtinyxml.so.0.2.6.2
7f3cefe5b000-7f3cefe5c000 ---p 00016000 103:04 6200307                   /usr/lib/libtinyxml.so.0.2.6.2
7f3cefe5c000-7f3cefe5d000 r--p 00016000 103:04 6200307                   /usr/lib/libtinyxml.so.0.2.6.2
7f3cefe5d000-7f3cefe5e000 rw-p 00017000 103:04 6200307                   /usr/lib/libtinyxml.so.0.2.6.2
7f3cefe5e000-7f3cefe62000 r--p 00000000 103:04 6200495                   /usr/lib/libpgm-5.3.so.0.0.128
7f3cefe62000-7f3cefe8b000 r-xp 00004000 103:04 6200495                   /usr/lib/libpgm-5.3.so.0.0.128
7f3cefe8b000-7f3cefea8000 r--p 0002d000 103:04 6200495                   /usr/lib/libpgm-5.3.so.0.0.128
7f3cefea8000-7f3cefea9000 ---p 0004a000 103:04 6200495                   /usr/lib/libpgm-5.3.so.0.0.128
7f3cefea9000-7f3cefeaa000 r--p 0004a000 103:04 6200495                   /usr/lib/libpgm-5.3.so.0.0.128
7f3cefeaa000-7f3cefeab000 rw-p 0004b000 103:04 6200495                   /usr/lib/libpgm-5.3.so.0.0.128
7f3cefeab000-7f3cefeaf000 rw-p 00000000 00:00 0 
7f3cefeaf000-7f3cefebc000 r--p 00000000 103:04 6195283                   /usr/lib/libsodium.so.23.3.0
7f3cefebc000-7f3cefef5000 r-xp 0000d000 103:04 6195283                   /usr/lib/libsodium.so.23.3.0
7f3cefef5000-7f3ceff07000 r--p 00046000 103:04 6195283                   /usr/lib/libsodium.so.23.3.0
7f3ceff07000-7f3ceff08000 r--p 00057000 103:04 6195283                   /usr/lib/libsodium.so.23.3.0
7f3ceff08000-7f3ceff09000 rw-p 00058000 103:04 6195283                   /usr/lib/libsodium.so.23.3.0
7f3ceff09000-7f3ceff0a000 r--p 00000000 103:04 6186278                   /usr/lib/libmd4c.so.0.4.7
7f3ceff0a000-7f3ceff18000 r-xp 00001000 103:04 6186278                   /usr/lib/libmd4c.so.0.4.7
7f3ceff18000-7f3ceff1b000 r--p 0000f000 103:04 6186278                   /usr/lib/libmd4c.so.0.4.7
7f3ceff1b000-7f3ceff1c000 ---p 00012000 103:04 6186278                   /usr/lib/libmd4c.so.0.4.7
7f3ceff1c000-7f3ceff1d000 r--p 00012000 103:04 6186278                   /usr/lib/libmd4c.so.0.4.7
7f3ceff1d000-7f3ceff1e000 rw-p 00013000 103:04 6186278                   /usr/lib/libmd4c.so.0.4.7
7f3ceff1e000-7f3ceff28000 r--p 00000000 103:04 6227047                   /usr/lib/libharfbuzz.so.0.20704.0
7f3ceff28000-7f3ceffbc000 r-xp 0000a000 103:04 6227047                   /usr/lib/libharfbuzz.so.0.20704.0
7f3ceffbc000-7f3ceffef000 r--p 0009e000 103:04 6227047                   /usr/lib/libharfbuzz.so.0.20704.0
7f3ceffef000-7f3cefff0000 ---p 000d1000 103:04 6227047                   /usr/lib/libharfbuzz.so.0.20704.0
7f3cefff0000-7f3cefff1000 r--p 000d1000 103:04 6227047                   /usr/lib/libharfbuzz.so.0.20704.0
7f3cefff1000-7f3cefff2000 rw-p 000d2000 103:04 6227047                   /usr/lib/libharfbuzz.so.0.20704.0
7f3cefff2000-7f3cefff8000 r--p 00000000 103:04 6186666                   /usr/lib/libpng16.so.16.37.0
7f3cefff8000-7f3cf001c000 r-xp 00006000 103:04 6186666                   /usr/lib/libpng16.so.16.37.0
7f3cf001c000-7f3cf0027000 r--p 0002a000 103:04 6186666                   /usr/lib/libpng16.so.16.37.0
7f3cf0027000-7f3cf0028000 r--p 00034000 103:04 6186666                   /usr/lib/libpng16.so.16.37.0
7f3cf0028000-7f3cf0029000 rw-p 00035000 103:04 6186666                   /usr/lib/libpng16.so.16.37.0
7f3cf0029000-7f3cf006b000 r--p 00000000 103:04 6190503                   /usr/lib/libGL.so.1.7.0
7f3cf006b000-7f3cf006e000 r-xp 00042000 103:04 6190503                   /usr/lib/libGL.so.1.7.0
7f3cf006e000-7f3cf0089000 r-xp 00045000 103:04 6190503                   /usr/lib/libGL.so.1.7.0
7f3cf0089000-7f3cf008a000 r-xp 00060000 103:04 6190503                   /usr/lib/libGL.so.1.7.0
7f3cf008a000-7f3cf009f000 r--p 00061000 103:04 6190503                   /usr/lib/libGL.so.1.7.0
7f3cf009f000-7f3cf00ad000 r--p 00075000 103:04 6190503                   /usr/lib/libGL.so.1.7.0
7f3cf00ad000-7f3cf00ae000 rw-p 00083000 103:04 6190503                   /usr/lib/libGL.so.1.7.0
7f3cf00ae000-7f3cf00af000 rw-p 00000000 00:00 0 
7f3cf00af000-7f3cf00b1000 r--p 00000000 103:04 6176989                   /usr/lib/libpcre.so.1.2.12
7f3cf00b1000-7f3cf0101000 r-xp 00002000 103:04 6176989                   /usr/lib/libpcre.so.1.2.12
7f3cf0101000-7f3cf011f000 r--p 00052000 103:04 6176989                   /usr/lib/libpcre.so.1.2.12
7f3cf011f000-7f3cf0120000 r--p 0006f000 103:04 6176989                   /usr/lib/libpcre.so.1.2.12
7f3cf0120000-7f3cf0121000 rw-p 00070000 103:04 6176989                   /usr/lib/libpcre.so.1.2.12
7f3cf0121000-7f3cf1c61000 r--p 00000000 103:04 6177239                   /usr/lib/libicudata.so.68.2
7f3cf1c61000-7f3cf1c62000 r--p 01b3f000 103:04 6177239                   /usr/lib/libicudata.so.68.2
7f3cf1c62000-7f3cf1c6e000 r--p 00000000 103:04 6173548                   /usr/lib/libgcrypt.so.20.2.8
7f3cf1c6e000-7f3cf1d3f000 r-xp 0000c000 103:04 6173548                   /usr/lib/libgcrypt.so.20.2.8
7f3cf1d3f000-7f3cf1d7b000 r--p 000dd000 103:04 6173548                   /usr/lib/libgcrypt.so.20.2.8
7f3cf1d7b000-7f3cf1d7c000 ---p 00119000 103:04 6173548                   /usr/lib/libgcrypt.so.20.2.8
7f3cf1d7c000-7f3cf1d7e000 r--p 00119000 103:04 6173548                   /usr/lib/libgcrypt.so.20.2.8
7f3cf1d7e000-7f3cf1d83000 rw-p 0011b000 103:04 6173548                   /usr/lib/libgcrypt.so.20.2.8
7f3cf1d83000-7f3cf1d86000 r--p 00000000 103:04 6181887                   /usr/lib/liblz4.so.1.9.3
7f3cf1d86000-7f3cf1da1000 r-xp 00003000 103:04 6181887                   /usr/lib/liblz4.so.1.9.3
7f3cf1da1000-7f3cf1da4000 r--p 0001e000 103:04 6181887                   /usr/lib/liblz4.so.1.9.3
7f3cf1da4000-7f3cf1da5000 r--p 00020000 103:04 6181887                   /usr/lib/liblz4.so.1.9.3
7f3cf1da5000-7f3cf1da6000 rw-p 00021000 103:04 6181887                   /usr/lib/liblz4.so.1.9.3
7f3cf1da6000-7f3cf1da8000 r--p 00000000 103:04 6173795                   /usr/lib/libcom_err.so.2.1
7f3cf1da8000-7f3cf1da9000 r-xp 00002000 103:04 6173795                   /usr/lib/libcom_err.so.2.1
7f3cf1da9000-7f3cf1daa000 r--p 00003000 103:04 6173795                   /usr/lib/libcom_err.so.2.1
7f3cf1daa000-7f3cf1dab000 r--p 00003000 103:04 6173795                   /usr/lib/libcom_err.so.2.1
7f3cf1dab000-7f3cf1dac000 rw-p 00004000 103:04 6173795                   /usr/lib/libcom_err.so.2.1
7f3cf1dac000-7f3cf1db1000 r--p 00000000 103:04 6174177                   /usr/lib/libk5crypto.so.3.1
7f3cf1db1000-7f3cf1dcd000 r-xp 00005000 103:04 6174177                   /usr/lib/libk5crypto.so.3.1
7f3cf1dcd000-7f3cf1dda000 r--p 00021000 103:04 6174177                   /usr/lib/libk5crypto.so.3.1
7f3cf1dda000-7f3cf1ddc000 r--p 0002d000 103:04 6174177                   /usr/lib/libk5crypto.so.3.1
7f3cf1ddc000-7f3cf1ddd000 rw-p 0002f000 103:04 6174177                   /usr/lib/libk5crypto.so.3.1
7f3cf1ddd000-7f3cf1e00000 r--p 00000000 103:04 6174206                   /usr/lib/libkrb5.so.3.3
7f3cf1e00000-7f3cf1e69000 r-xp 00023000 103:04 6174206                   /usr/lib/libkrb5.so.3.3
7f3cf1e69000-7f3cf1eb2000 r--p 0008c000 103:04 6174206                   /usr/lib/libkrb5.so.3.3
7f3cf1eb2000-7f3cf1ec1000 r--p 000d4000 103:04 6174206                   /usr/lib/libkrb5.so.3.3
7f3cf1ec1000-7f3cf1ec3000 rw-p 000e3000 103:04 6174206                   /usr/lib/libkrb5.so.3.3
7f3cf1ec3000-7f3cf1ecf000 r--p 00000000 103:04 6174165                   /usr/lib/libgssapi_krb5.so.2.2
7f3cf1ecf000-7f3cf1f07000 r-xp 0000c000 103:04 6174165                   /usr/lib/libgssapi_krb5.so.2.2
7f3cf1f07000-7f3cf1f14000 r--p 00044000 103:04 6174165                   /usr/lib/libgssapi_krb5.so.2.2
7f3cf1f14000-7f3cf1f15000 ---p 00051000 103:04 6174165                   /usr/lib/libgssapi_krb5.so.2.2
7f3cf1f15000-7f3cf1f17000 r--p 00051000 103:04 6174165                   /usr/lib/libgssapi_krb5.so.2.2
7f3cf1f17000-7f3cf1f18000 rw-p 00053000 103:04 6174165                   /usr/lib/libgssapi_krb5.so.2.2
7f3cf1f18000-7f3cf1f8e000 r--p 00000000 103:04 6169351                   /usr/lib/libcrypto.so.1.1
7f3cf1f8e000-7f3cf2133000 r-xp 00076000 103:04 6169351                   /usr/lib/libcrypto.so.1.1
7f3cf2133000-7f3cf21c4000 r--p 0021b000 103:04 6169351                   /usr/lib/libcrypto.so.1.1
7f3cf21c4000-7f3cf21f0000 r--p 002ab000 103:04 6169351                   /usr/lib/libcrypto.so.1.1
7f3cf21f0000-7f3cf21f2000 rw-p 002d7000 103:04 6169351                   /usr/lib/libcrypto.so.1.1
7f3cf21f2000-7f3cf21f6000 rw-p 00000000 00:00 0 
7f3cf21f6000-7f3cf2213000 r--p 00000000 103:04 6169354                   /usr/lib/libssl.so.1.1
7f3cf2213000-7f3cf2260000 r-xp 0001d000 103:04 6169354                   /usr/lib/libssl.so.1.1
7f3cf2260000-7f3cf227a000 r--p 0006a000 103:04 6169354                   /usr/lib/libssl.so.1.1
7f3cf227a000-7f3cf2283000 r--p 00083000 103:04 6169354                   /usr/lib/libssl.so.1.1
7f3cf2283000-7f3cf2287000 rw-p 0008c000 103:04 6169354                   /usr/lib/libssl.so.1.1
7f3cf2287000-7f3cf2289000 r--p 00000000 103:04 6182088                   /usr/lib/libpsl.so.5.3.3
7f3cf2289000-7f3cf228b000 r-xp 00002000 103:04 6182088                   /usr/lib/libpsl.so.5.3.3
7f3cf228b000-7f3cf2298000 r--p 00004000 103:04 6182088                   /usr/lib/libpsl.so.5.3.3
7f3cf2298000-7f3cf2299000 r--p 00010000 103:04 6182088                   /usr/lib/libpsl.so.5.3.3
7f3cf2299000-7f3cf229a000 rw-p 00011000 103:04 6182088                   /usr/lib/libpsl.so.5.3.3
7f3cf229a000-7f3cf22a1000 r--p 00000000 103:04 6181913                   /usr/lib/libssh2.so.1.0.1
7f3cf22a1000-7f3cf22ca000 r-xp 00007000 103:04 6181913                   /usr/lib/libssh2.so.1.0.1
7f3cf22ca000-7f3cf22d7000 r--p 00030000 103:04 6181913                   /usr/lib/libssh2.so.1.0.1
7f3cf22d7000-7f3cf22d9000 r--p 0003c000 103:04 6181913                   /usr/lib/libssh2.so.1.0.1
7f3cf22d9000-7f3cf22da000 rw-p 0003e000 103:04 6181913                   /usr/lib/libssh2.so.1.0.1
7f3cf22da000-7f3cf22dc000 r--p 00000000 103:04 6175077                   /usr/lib/libidn2.so.0.3.7
7f3cf22dc000-7f3cf22e0000 r-xp 00002000 103:04 6175077                   /usr/lib/libidn2.so.0.3.7
7f3cf22e0000-7f3cf22f9000 r--p 00006000 103:04 6175077                   /usr/lib/libidn2.so.0.3.7
7f3cf22f9000-7f3cf22fa000 r--p 0001e000 103:04 6175077                   /usr/lib/libidn2.so.0.3.7
7f3cf22fa000-7f3cf22fb000 rw-p 0001f000 103:04 6175077                   /usr/lib/libidn2.so.0.3.7
7f3cf22fb000-7f3cf2300000 r--p 00000000 103:04 6203397                   /usr/lib/libnghttp2.so.14.20.0
7f3cf2300000-7f3cf2315000 r-xp 00005000 103:04 6203397                   /usr/lib/libnghttp2.so.14.20.0
7f3cf2315000-7f3cf2322000 r--p 0001a000 103:04 6203397                   /usr/lib/libnghttp2.so.14.20.0
7f3cf2322000-7f3cf2323000 ---p 00027000 103:04 6203397                   /usr/lib/libnghttp2.so.14.20.0
7f3cf2323000-7f3cf2326000 r--p 00027000 103:04 6203397                   /usr/lib/libnghttp2.so.14.20.0
7f3cf2326000-7f3cf2327000 rw-p 0002a000 103:04 6203397                   /usr/lib/libnghttp2.so.14.20.0
7f3cf2327000-7f3cf2332000 r--p 00000000 103:04 6205085                   /usr/lib/libnettle.so.8.0
7f3cf2332000-7f3cf2350000 r-xp 0000b000 103:04 6205085                   /usr/lib/libnettle.so.8.0
7f3cf2350000-7f3cf2361000 r--p 00029000 103:04 6205085                   /usr/lib/libnettle.so.8.0
7f3cf2361000-7f3cf2362000 ---p 0003a000 103:04 6205085                   /usr/lib/libnettle.so.8.0
7f3cf2362000-7f3cf2364000 r--p 0003a000 103:04 6205085                   /usr/lib/libnettle.so.8.0
7f3cf2364000-7f3cf2365000 rw-p 0003c000 103:04 6205085                   /usr/lib/libnettle.so.8.0
7f3cf2365000-7f3cf2399000 r--p 00000000 103:04 6177204                   /usr/lib/libgnutls.so.30.29.0
7f3cf2399000-7f3cf24ba000 r-xp 00034000 103:04 6177204                   /usr/lib/libgnutls.so.30.29.0
7f3cf24ba000-7f3cf2553000 r--p 00155000 103:04 6177204                   /usr/lib/libgnutls.so.30.29.0
7f3cf2553000-7f3cf2564000 r--p 001ed000 103:04 6177204                   /usr/lib/libgnutls.so.30.29.0
7f3cf2564000-7f3cf2566000 rw-p 001fe000 103:04 6177204                   /usr/lib/libgnutls.so.30.29.0
7f3cf2566000-7f3cf2568000 rw-p 00000000 00:00 0 
7f3cf2568000-7f3cf256b000 r--p 00000000 103:04 6173593                   /usr/lib/liblzma.so.5.2.5
7f3cf256b000-7f3cf2582000 r-xp 00003000 103:04 6173593                   /usr/lib/liblzma.so.5.2.5
7f3cf2582000-7f3cf258d000 r--p 0001a000 103:04 6173593                   /usr/lib/liblzma.so.5.2.5
7f3cf258d000-7f3cf258e000 ---p 00025000 103:04 6173593                   /usr/lib/liblzma.so.5.2.5
7f3cf258e000-7f3cf258f000 r--p 00025000 103:04 6173593                   /usr/lib/liblzma.so.5.2.5
7f3cf258f000-7f3cf2590000 rw-p 00026000 103:04 6173593                   /usr/lib/liblzma.so.5.2.5
7f3cf2590000-7f3cf2592000 r--p 00000000 103:04 6167561                   /usr/lib/libbz2.so.1.0.8
7f3cf2592000-7f3cf259f000 r-xp 00002000 103:04 6167561                   /usr/lib/libbz2.so.1.0.8
7f3cf259f000-7f3cf25a1000 r--p 0000f000 103:04 6167561                   /usr/lib/libbz2.so.1.0.8
7f3cf25a1000-7f3cf25a2000 r--p 00010000 103:04 6167561                   /usr/lib/libbz2.so.1.0.8
7f3cf25a2000-7f3cf25a3000 rw-p 00011000 103:04 6167561                   /usr/lib/libbz2.so.1.0.8
7f3cf25a3000-7f3cf25a5000 r--p 00000000 103:04 6214235                   /usr/lib/libconsole_bridge.so.1.0
7f3cf25a5000-7f3cf25a7000 r-xp 00002000 103:04 6214235                   /usr/lib/libconsole_bridge.so.1.0
7f3cf25a7000-7f3cf25a8000 r--p 00004000 103:04 6214235                   /usr/lib/libconsole_bridge.so.1.0
7f3cf25a8000-7f3cf25a9000 r--p 00004000 103:04 6214235                   /usr/lib/libconsole_bridge.so.1.0
7f3cf25a9000-7f3cf25aa000 rw-p 00005000 103:04 6214235                   /usr/lib/libconsole_bridge.so.1.0
7f3cf25aa000-7f3cf25af000 r--p 00000000 103:04 6212441                   /usr/lib/liburdfdom_world.so.1.0
7f3cf25af000-7f3cf25c8000 r-xp 00005000 103:04 6212441                   /usr/lib/liburdfdom_world.so.1.0
7f3cf25c8000-7f3cf25cf000 r--p 0001e000 103:04 6212441                   /usr/lib/liburdfdom_world.so.1.0
7f3cf25cf000-7f3cf25d0000 ---p 00025000 103:04 6212441                   /usr/lib/liburdfdom_world.so.1.0
7f3cf25d0000-7f3cf25d1000 r--p 00025000 103:04 6212441                   /usr/lib/liburdfdom_world.so.1.0
7f3cf25d1000-7f3cf25d2000 rw-p 00026000 103:04 6212441                   /usr/lib/liburdfdom_world.so.1.0
7f3cf25d2000-7f3cf25d7000 r--p 00000000 103:04 6212435                   /usr/lib/liburdfdom_model.so.1.0
7f3cf25d7000-7f3cf25f0000 r-xp 00005000 103:04 6212435                   /usr/lib/liburdfdom_model.so.1.0
7f3cf25f0000-7f3cf25f7000 r--p 0001e000 103:04 6212435                   /usr/lib/liburdfdom_model.so.1.0
7f3cf25f7000-7f3cf25f8000 r--p 00024000 103:04 6212435                   /usr/lib/liburdfdom_model.so.1.0
7f3cf25f8000-7f3cf25f9000 rw-p 00025000 103:04 6212435                   /usr/lib/liburdfdom_model.so.1.0
7f3cf25f9000-7f3cf25fc000 r--p 00000000 103:04 6212437                   /usr/lib/liburdfdom_model_state.so.1.0
7f3cf25fc000-7f3cf2602000 r-xp 00003000 103:04 6212437                   /usr/lib/liburdfdom_model_state.so.1.0
7f3cf2602000-7f3cf2603000 r--p 00009000 103:04 6212437                   /usr/lib/liburdfdom_model_state.so.1.0
7f3cf2603000-7f3cf2604000 ---p 0000a000 103:04 6212437                   /usr/lib/liburdfdom_model_state.so.1.0
7f3cf2604000-7f3cf2605000 r--p 0000a000 103:04 6212437                   /usr/lib/liburdfdom_model_state.so.1.0
7f3cf2605000-7f3cf2606000 rw-p 0000b000 103:04 6212437                   /usr/lib/liburdfdom_model_state.so.1.0
7f3cf2606000-7f3cf2608000 r--p 00000000 103:04 6212439                   /usr/lib/liburdfdom_sensor.so.1.0
7f3cf2608000-7f3cf260d000 r-xp 00002000 103:04 6212439                   /usr/lib/liburdfdom_sensor.so.1.0
7f3cf260d000-7f3cf260e000 r--p 00007000 103:04 6212439                   /usr/lib/liburdfdom_sensor.so.1.0
7f3cf260e000-7f3cf260f000 ---p 00008000 103:04 6212439                   /usr/lib/liburdfdom_sensor.so.1.0
7f3cf260f000-7f3cf2610000 r--p 00008000 103:04 6212439                   /usr/lib/liburdfdom_sensor.so.1.0
7f3cf2610000-7f3cf2611000 rw-p 00009000 103:04 6212439                   /usr/lib/liburdfdom_sensor.so.1.0
7f3cf2611000-7f3cf2629000 r--p 00000000 103:04 6200504                   /usr/lib/libzmq.so.5.2.3
7f3cf2629000-7f3cf269b000 r-xp 00018000 103:04 6200504                   /usr/lib/libzmq.so.5.2.3
7f3cf269b000-7f3cf26bd000 r--p 0008a000 103:04 6200504                   /usr/lib/libzmq.so.5.2.3
7f3cf26bd000-7f3cf26be000 ---p 000ac000 103:04 6200504                   /usr/lib/libzmq.so.5.2.3
7f3cf26be000-7f3cf26c6000 r--p 000ac000 103:04 6200504                   /usr/lib/libzmq.so.5.2.3
7f3cf26c6000-7f3cf26c7000 rw-p 000b4000 103:04 6200504                   /usr/lib/libzmq.so.5.2.3
7f3cf26c7000-7f3cf2708000 r--p 00000000 103:04 6185247                   /usr/lib/libQt5Network.so.5.15.2
7f3cf2708000-7f3cf27ed000 r-xp 00041000 103:04 6185247                   /usr/lib/libQt5Network.so.5.15.2
7f3cf27ed000-7f3cf2840000 r--p 00126000 103:04 6185247                   /usr/lib/libQt5Network.so.5.15.2
7f3cf2840000-7f3cf2848000 r--p 00178000 103:04 6185247                   /usr/lib/libQt5Network.so.5.15.2
7f3cf2848000-7f3cf2849000 rw-p 00180000 103:04 6185247                   /usr/lib/libQt5Network.so.5.15.2
7f3cf2849000-7f3cf2863000 r--p 00000000 103:04 6192146                   /usr/lib/libQt5QmlModels.so.5.15.2
7f3cf2863000-7f3cf28ae000 r-xp 0001a000 103:04 6192146                   /usr/lib/libQt5QmlModels.so.5.15.2
7f3cf28ae000-7f3cf28c7000 r--p 00065000 103:04 6192146                   /usr/lib/libQt5QmlModels.so.5.15.2
7f3cf28c7000-7f3cf28cc000 r--p 0007d000 103:04 6192146                   /usr/lib/libQt5QmlModels.so.5.15.2
7f3cf28cc000-7f3cf28cd000 rw-p 00082000 103:04 6192146                   /usr/lib/libQt5QmlModels.so.5.15.2
7f3cf28cd000-7f3cf29af000 r--p 00000000 103:04 6185236                   /usr/lib/libQt5Gui.so.5.15.2
7f3cf29af000-7f3cf2e7e000 r-xp 000e2000 103:04 6185236                   /usr/lib/libQt5Gui.so.5.15.2
7f3cf2e7e000-7f3cf2f7a000 r--p 005b1000 103:04 6185236                   /usr/lib/libQt5Gui.so.5.15.2
7f3cf2f7a000-7f3cf2f7b000 ---p 006ad000 103:04 6185236                   /usr/lib/libQt5Gui.so.5.15.2
7f3cf2f7b000-7f3cf2f8e000 r--p 006ad000 103:04 6185236                   /usr/lib/libQt5Gui.so.5.15.2
7f3cf2f8e000-7f3cf2f90000 rw-p 006c0000 103:04 6185236                   /usr/lib/libQt5Gui.so.5.15.2
7f3cf2f90000-7f3cf2f9b000 rw-p 00000000 00:00 0 
7f3cf2f9b000-7f3cf2fb7000 r--p 00000000 103:04 6177208                   /usr/lib/libglib-2.0.so.0.6600.4
7f3cf2fb7000-7f3cf3043000 r-xp 0001c000 103:04 6177208                   /usr/lib/libglib-2.0.so.0.6600.4
7f3cf3043000-7f3cf30cb000 r--p 000a8000 103:04 6177208                   /usr/lib/libglib-2.0.so.0.6600.4
7f3cf30cb000-7f3cf30cc000 ---p 00130000 103:04 6177208                   /usr/lib/libglib-2.0.so.0.6600.4
7f3cf30cc000-7f3cf30cd000 r--p 00130000 103:04 6177208                   /usr/lib/libglib-2.0.so.0.6600.4
7f3cf30cd000-7f3cf30ce000 rw-p 00131000 103:04 6177208                   /usr/lib/libglib-2.0.so.0.6600.4
7f3cf30ce000-7f3cf30cf000 rw-p 00000000 00:00 0 
7f3cf30cf000-7f3cf30d4000 r--p 00000000 103:04 6191815                   /usr/lib/libzstd.so.1.4.5
7f3cf30d4000-7f3cf318d000 r-xp 00005000 103:04 6191815                   /usr/lib/libzstd.so.1.4.5
7f3cf318d000-7f3cf319f000 r--p 000be000 103:04 6191815                   /usr/lib/libzstd.so.1.4.5
7f3cf319f000-7f3cf31a0000 r--p 000cf000 103:04 6191815                   /usr/lib/libzstd.so.1.4.5
7f3cf31a0000-7f3cf31a1000 rw-p 000d0000 103:04 6191815                   /usr/lib/libzstd.so.1.4.5
7f3cf31a1000-7f3cf31a4000 r--p 00000000 103:04 6175564                   /usr/lib/libpcre2-16.so.0.10.1
7f3cf31a4000-7f3cf3202000 r-xp 00003000 103:04 6175564                   /usr/lib/libpcre2-16.so.0.10.1
7f3cf3202000-7f3cf322a000 r--p 00061000 103:04 6175564                   /usr/lib/libpcre2-16.so.0.10.1
7f3cf322a000-7f3cf322b000 r--p 00088000 103:04 6175564                   /usr/lib/libpcre2-16.so.0.10.1
7f3cf322b000-7f3cf322c000 rw-p 00089000 103:04 6175564                   /usr/lib/libpcre2-16.so.0.10.1
7f3cf322c000-7f3cf3291000 r--p 00000000 103:04 6177261                   /usr/lib/libicuuc.so.68.2
7f3cf3291000-7f3cf337d000 r-xp 00065000 103:04 6177261                   /usr/lib/libicuuc.so.68.2
7f3cf337d000-7f3cf3405000 r--p 00151000 103:04 6177261                   /usr/lib/libicuuc.so.68.2
7f3cf3405000-7f3cf3418000 r--p 001d8000 103:04 6177261                   /usr/lib/libicuuc.so.68.2
7f3cf3418000-7f3cf3419000 rw-p 001eb000 103:04 6177261                   /usr/lib/libicuuc.so.68.2
7f3cf3419000-7f3cf341b000 rw-p 00000000 00:00 0 
7f3cf341b000-7f3cf3508000 r--p 00000000 103:04 6177245                   /usr/lib/libicui18n.so.68.2
7f3cf3508000-7f3cf3699000 r-xp 000ed000 103:04 6177245                   /usr/lib/libicui18n.so.68.2
7f3cf3699000-7f3cf3727000 r--p 0027e000 103:04 6177245                   /usr/lib/libicui18n.so.68.2
7f3cf3727000-7f3cf3738000 r--p 0030b000 103:04 6177245                   /usr/lib/libicui18n.so.68.2
7f3cf3738000-7f3cf3739000 rw-p 0031c000 103:04 6177245                   /usr/lib/libicui18n.so.68.2
7f3cf3739000-7f3cf373a000 rw-p 00000000 00:00 0 
7f3cf373a000-7f3cf373d000 r--p 00000000 103:04 6249090                   /usr/lib/libdouble-conversion.so.3.1.5
7f3cf373d000-7f3cf3749000 r-xp 00003000 103:04 6249090                   /usr/lib/libdouble-conversion.so.3.1.5
7f3cf3749000-7f3cf374f000 r--p 0000f000 103:04 6249090                   /usr/lib/libdouble-conversion.so.3.1.5
7f3cf374f000-7f3cf3750000 r--p 00014000 103:04 6249090                   /usr/lib/libdouble-conversion.so.3.1.5
7f3cf3750000-7f3cf3751000 rw-p 00015000 103:04 6249090                   /usr/lib/libdouble-conversion.so.3.1.5
7f3cf3751000-7f3cf3764000 r--p 00000000 103:04 6176215                   /usr/lib/libsystemd.so.0.30.0
7f3cf3764000-7f3cf37db000 r-xp 00013000 103:04 6176215                   /usr/lib/libsystemd.so.0.30.0
7f3cf37db000-7f3cf3801000 r--p 0008a000 103:04 6176215                   /usr/lib/libsystemd.so.0.30.0
7f3cf3801000-7f3cf3805000 r--p 000af000 103:04 6176215                   /usr/lib/libsystemd.so.0.30.0
7f3cf3805000-7f3cf3806000 rw-p 000b3000 103:04 6176215                   /usr/lib/libsystemd.so.0.30.0
7f3cf3806000-7f3cf3807000 rw-p 00000000 00:00 0 
7f3cf3807000-7f3cf3809000 r--p 00000000 103:04 6209456                   /usr/lib/libuuid.so.1.3.0
7f3cf3809000-7f3cf380d000 r-xp 00002000 103:04 6209456                   /usr/lib/libuuid.so.1.3.0
7f3cf380d000-7f3cf380e000 r--p 00006000 103:04 6209456                   /usr/lib/libuuid.so.1.3.0
7f3cf380e000-7f3cf380f000 r--p 00006000 103:04 6209456                   /usr/lib/libuuid.so.1.3.0
7f3cf380f000-7f3cf3810000 rw-p 00007000 103:04 6209456                   /usr/lib/libuuid.so.1.3.0
7f3cf3810000-7f3cf381e000 r--p 00000000 103:04 6182123                   /usr/lib/libcurl.so.4.7.0
7f3cf381e000-7f3cf3884000 r-xp 0000e000 103:04 6182123                   /usr/lib/libcurl.so.4.7.0
7f3cf3884000-7f3cf38a1000 r--p 00074000 103:04 6182123                   /usr/lib/libcurl.so.4.7.0
7f3cf38a1000-7f3cf38a2000 ---p 00091000 103:04 6182123                   /usr/lib/libcurl.so.4.7.0
7f3cf38a2000-7f3cf38a5000 r--p 00091000 103:04 6182123                   /usr/lib/libcurl.so.4.7.0
7f3cf38a5000-7f3cf38a7000 rw-p 00094000 103:04 6182123                   /usr/lib/libcurl.so.4.7.0
7f3cf38a7000-7f3cf38a8000 rw-p 00000000 00:00 0 
7f3cf38a8000-7f3cf38ad000 r--p 00000000 103:04 6200538                   /usr/lib/libzip.so.5.3
7f3cf38ad000-7f3cf38bf000 r-xp 00005000 103:04 6200538                   /usr/lib/libzip.so.5.3
7f3cf38bf000-7f3cf38c4000 r--p 00017000 103:04 6200538                   /usr/lib/libzip.so.5.3
7f3cf38c4000-7f3cf38c5000 ---p 0001c000 103:04 6200538                   /usr/lib/libzip.so.5.3
7f3cf38c5000-7f3cf38c6000 r--p 0001c000 103:04 6200538                   /usr/lib/libzip.so.5.3
7f3cf38c6000-7f3cf38c7000 rw-p 0001d000 103:04 6200538                   /usr/lib/libzip.so.5.3
7f3cf38c7000-7f3cf38d4000 r--p 00000000 103:04 6224249                   /usr/lib/libjsoncpp.so.24
7f3cf38d4000-7f3cf38f1000 r-xp 0000d000 103:04 6224249                   /usr/lib/libjsoncpp.so.24
7f3cf38f1000-7f3cf38fc000 r--p 0002a000 103:04 6224249                   /usr/lib/libjsoncpp.so.24
7f3cf38fc000-7f3cf38fd000 ---p 00035000 103:04 6224249                   /usr/lib/libjsoncpp.so.24
7f3cf38fd000-7f3cf38fe000 r--p 00035000 103:04 6224249                   /usr/lib/libjsoncpp.so.24
7f3cf38fe000-7f3cf38ff000 rw-p 00036000 103:04 6224249                   /usr/lib/libjsoncpp.so.24
7f3cf38ff000-7f3cf390c000 r--p 00000000 103:04 6194536                   /usr/lib/libignition-common3-events.so.3.9.0
7f3cf390c000-7f3cf391f000 r-xp 0000d000 103:04 6194536                   /usr/lib/libignition-common3-events.so.3.9.0
7f3cf391f000-7f3cf3924000 r--p 00020000 103:04 6194536                   /usr/lib/libignition-common3-events.so.3.9.0
7f3cf3924000-7f3cf3925000 ---p 00025000 103:04 6194536                   /usr/lib/libignition-common3-events.so.3.9.0
7f3cf3925000-7f3cf3926000 r--p 00025000 103:04 6194536                   /usr/lib/libignition-common3-events.so.3.9.0
7f3cf3926000-7f3cf3927000 rw-p 00026000 103:04 6194536                   /usr/lib/libignition-common3-events.so.3.9.0
7f3cf3927000-7f3cf392b000 r--p 00000000 103:04 6207280                   /usr/lib/libignition-plugin1.so.1.1.0
7f3cf392b000-7f3cf3930000 r-xp 00004000 103:04 6207280                   /usr/lib/libignition-plugin1.so.1.1.0
7f3cf3930000-7f3cf3932000 r--p 00009000 103:04 6207280                   /usr/lib/libignition-plugin1.so.1.1.0
7f3cf3932000-7f3cf3933000 r--p 0000a000 103:04 6207280                   /usr/lib/libignition-plugin1.so.1.1.0
7f3cf3933000-7f3cf3934000 rw-p 0000b000 103:04 6207280                   /usr/lib/libignition-plugin1.so.1.1.0
7f3cf3934000-7f3cf393a000 r--p 00000000 103:04 6207277                   /usr/lib/libignition-plugin1-loader.so.1.1.0
7f3cf393a000-7f3cf3943000 r-xp 00006000 103:04 6207277                   /usr/lib/libignition-plugin1-loader.so.1.1.0
7f3cf3943000-7f3cf3946000 r--p 0000f000 103:04 6207277                   /usr/lib/libignition-plugin1-loader.so.1.1.0
7f3cf3946000-7f3cf3947000 r--p 00011000 103:04 6207277                   /usr/lib/libignition-plugin1-loader.so.1.1.0
7f3cf3947000-7f3cf3948000 rw-p 00012000 103:04 6207277                   /usr/lib/libignition-plugin1-loader.so.1.1.0
7f3cf3948000-7f3cf3a04000 r--p 00000000 103:04 6177710                   /usr/lib/libprotobuf.so.23.0.4
7f3cf3a04000-7f3cf3bcd000 r-xp 000bc000 103:04 6177710                   /usr/lib/libprotobuf.so.23.0.4
7f3cf3bcd000-7f3cf3c55000 r--p 00285000 103:04 6177710                   /usr/lib/libprotobuf.so.23.0.4
7f3cf3c55000-7f3cf3c56000 ---p 0030d000 103:04 6177710                   /usr/lib/libprotobuf.so.23.0.4
7f3cf3c56000-7f3cf3c63000 r--p 0030d000 103:04 6177710                   /usr/lib/libprotobuf.so.23.0.4
7f3cf3c63000-7f3cf3c64000 rw-p 0031a000 103:04 6177710                   /usr/lib/libprotobuf.so.23.0.4
7f3cf3c64000-7f3cf3c66000 rw-p 00000000 00:00 0 
7f3cf3c66000-7f3cf3c83000 r--p 00000000 103:04 6174004                   /usr/lib/libignition-math6.so.6.7.0
7f3cf3c83000-7f3cf3cbe000 r-xp 0001d000 103:04 6174004                   /usr/lib/libignition-math6.so.6.7.0
7f3cf3cbe000-7f3cf3cd6000 r--p 00058000 103:04 6174004                   /usr/lib/libignition-math6.so.6.7.0
7f3cf3cd6000-7f3cf3cd7000 ---p 00070000 103:04 6174004                   /usr/lib/libignition-math6.so.6.7.0
7f3cf3cd7000-7f3cf3cd9000 r--p 00070000 103:04 6174004                   /usr/lib/libignition-math6.so.6.7.0
7f3cf3cd9000-7f3cf3cda000 rw-p 00072000 103:04 6174004                   /usr/lib/libignition-math6.so.6.7.0
7f3cf3cda000-7f3cf3cdc000 rw-p 00000000 00:00 0 
7f3cf3cdc000-7f3cf3d14000 r--p 00000000 103:04 6194526                   /usr/lib/libsdformat10.so.10.1.0
7f3cf3d14000-7f3cf3e42000 r-xp 00038000 103:04 6194526                   /usr/lib/libsdformat10.so.10.1.0
7f3cf3e42000-7f3cf3f0a000 r--p 00166000 103:04 6194526                   /usr/lib/libsdformat10.so.10.1.0
7f3cf3f0a000-7f3cf3f0b000 ---p 0022e000 103:04 6194526                   /usr/lib/libsdformat10.so.10.1.0
7f3cf3f0b000-7f3cf3f0d000 r--p 0022e000 103:04 6194526                   /usr/lib/libsdformat10.so.10.1.0
7f3cf3f0d000-7f3cf3f10000 rw-p 00230000 103:04 6194526                   /usr/lib/libsdformat10.so.10.1.0
7f3cf3f10000-7f3cf3f11000 rw-p 00000000 00:00 0 
7f3cf3f11000-7f3cf402c000 r--p 00000000 103:04 6194553                   /usr/lib/libignition-msgs6.so.6.2.0
7f3cf402c000-7f3cf418e000 r-xp 0011b000 103:04 6194553                   /usr/lib/libignition-msgs6.so.6.2.0
7f3cf418e000-7f3cf4215000 r--p 0027d000 103:04 6194553                   /usr/lib/libignition-msgs6.so.6.2.0
7f3cf4215000-7f3cf422e000 r--p 00303000 103:04 6194553                   /usr/lib/libignition-msgs6.so.6.2.0
7f3cf422e000-7f3cf4237000 rw-p 0031c000 103:04 6194553                   /usr/lib/libignition-msgs6.so.6.2.0
7f3cf4237000-7f3cf423d000 rw-p 00000000 00:00 0 
7f3cf423d000-7f3cf426b000 r--p 00000000 103:04 6194607                   /usr/lib/libignition-transport9.so.9.0.0
7f3cf426b000-7f3cf42db000 r-xp 0002e000 103:04 6194607                   /usr/lib/libignition-transport9.so.9.0.0
7f3cf42db000-7f3cf42f7000 r--p 0009e000 103:04 6194607                   /usr/lib/libignition-transport9.so.9.0.0
7f3cf42f7000-7f3cf42f8000 ---p 000ba000 103:04 6194607                   /usr/lib/libignition-transport9.so.9.0.0
7f3cf42f8000-7f3cf42fb000 r--p 000ba000 103:04 6194607                   /usr/lib/libignition-transport9.so.9.0.0
7f3cf42fb000-7f3cf42fc000 rw-p 000bd000 103:04 6194607                   /usr/lib/libignition-transport9.so.9.0.0
7f3cf42fc000-7f3cf4304000 r--p 00000000 103:04 6195277                   /usr/lib/libtinyxml2.so.7.1.0
7f3cf4304000-7f3cf430d000 r-xp 00008000 103:04 6195277                   /usr/lib/libtinyxml2.so.7.1.0
7f3cf430d000-7f3cf4311000 r--p 00011000 103:04 6195277                   /usr/lib/libtinyxml2.so.7.1.0
7f3cf4311000-7f3cf4312000 ---p 00015000 103:04 6195277                   /usr/lib/libtinyxml2.so.7.1.0
7f3cf4312000-7f3cf4313000 r--p 00015000 103:04 6195277                   /usr/lib/libtinyxml2.so.7.1.0
7f3cf4313000-7f3cf4314000 rw-p 00016000 103:04 6195277                   /usr/lib/libtinyxml2.so.7.1.0
7f3cf4314000-7f3cf43b3000 r--p 00000000 103:04 6192137                   /usr/lib/libQt5Qml.so.5.15.2
7f3cf43b3000-7f3cf4685000 r-xp 0009f000 103:04 6192137                   /usr/lib/libQt5Qml.so.5.15.2
7f3cf4685000-7f3cf4754000 r--p 00371000 103:04 6192137                   /usr/lib/libQt5Qml.so.5.15.2
7f3cf4754000-7f3cf4755000 ---p 00440000 103:04 6192137                   /usr/lib/libQt5Qml.so.5.15.2
7f3cf4755000-7f3cf4770000 r--p 00440000 103:04 6192137                   /usr/lib/libQt5Qml.so.5.15.2
7f3cf4770000-7f3cf4771000 rw-p 0045b000 103:04 6192137                   /usr/lib/libQt5Qml.so.5.15.2
7f3cf4771000-7f3cf4773000 rw-p 00000000 00:00 0 
7f3cf4773000-7f3cf4885000 r--p 00000000 103:04 6192156                   /usr/lib/libQt5Quick.so.5.15.2
7f3cf4885000-7f3cf4b65000 r-xp 00112000 103:04 6192156                   /usr/lib/libQt5Quick.so.5.15.2
7f3cf4b65000-7f3cf4c85000 r--p 003f2000 103:04 6192156                   /usr/lib/libQt5Quick.so.5.15.2
7f3cf4c85000-7f3cf4c86000 ---p 00512000 103:04 6192156                   /usr/lib/libQt5Quick.so.5.15.2
7f3cf4c86000-7f3cf4cb3000 r--p 00512000 103:04 6192156                   /usr/lib/libQt5Quick.so.5.15.2
7f3cf4cb3000-7f3cf4cb4000 rw-p 0053f000 103:04 6192156                   /usr/lib/libQt5Quick.so.5.15.2
7f3cf4cb4000-7f3cf4cb5000 rw-p 00000000 00:00 0 
7f3cf4cb5000-7f3cf4e03000 r--p 00000000 103:04 6186813                   /usr/lib/libQt5Widgets.so.5.15.2
7f3cf4e03000-7f3cf51b3000 r-xp 0014e000 103:04 6186813                   /usr/lib/libQt5Widgets.so.5.15.2
7f3cf51b3000-7f3cf5316000 r--p 004fe000 103:04 6186813                   /usr/lib/libQt5Widgets.so.5.15.2
7f3cf5316000-7f3cf5317000 ---p 00661000 103:04 6186813                   /usr/lib/libQt5Widgets.so.5.15.2
7f3cf5317000-7f3cf5348000 r--p 00661000 103:04 6186813                   /usr/lib/libQt5Widgets.so.5.15.2
7f3cf5348000-7f3cf5349000 rw-p 00692000 103:04 6186813                   /usr/lib/libQt5Widgets.so.5.15.2
7f3cf5349000-7f3cf536c000 r--p 00000000 103:04 6222159                   /usr/lib/libignition-gui4.so.4.1.0
7f3cf536c000-7f3cf53b3000 r-xp 00023000 103:04 6222159                   /usr/lib/libignition-gui4.so.4.1.0
7f3cf53b3000-7f3cf53d2000 r--p 0006a000 103:04 6222159                   /usr/lib/libignition-gui4.so.4.1.0
7f3cf53d2000-7f3cf53d5000 r--p 00088000 103:04 6222159                   /usr/lib/libignition-gui4.so.4.1.0
7f3cf53d5000-7f3cf53d6000 rw-p 0008b000 103:04 6222159                   /usr/lib/libignition-gui4.so.4.1.0
7f3cf53d6000-7f3cf53d9000 r--p 00000000 103:04 6164586                   /usr/lib/libgcc_s.so.1
7f3cf53d9000-7f3cf53ea000 r-xp 00003000 103:04 6164586                   /usr/lib/libgcc_s.so.1
7f3cf53ea000-7f3cf53ee000 r--p 00014000 103:04 6164586                   /usr/lib/libgcc_s.so.1
7f3cf53ee000-7f3cf53ef000 r--p 00017000 103:04 6164586                   /usr/lib/libgcc_s.so.1
7f3cf53ef000-7f3cf53f0000 rw-p 00018000 103:04 6164586                   /usr/lib/libgcc_s.so.1
7f3cf53f0000-7f3cf5486000 r--p 00000000 103:04 6209517                   /usr/lib/libstdc++.so.6.0.28
7f3cf5486000-7f3cf5572000 r-xp 00096000 103:04 6209517                   /usr/lib/libstdc++.so.6.0.28
7f3cf5572000-7f3cf55bb000 r--p 00182000 103:04 6209517                   /usr/lib/libstdc++.so.6.0.28
7f3cf55bb000-7f3cf55bc000 ---p 001cb000 103:04 6209517                   /usr/lib/libstdc++.so.6.0.28
7f3cf55bc000-7f3cf55c9000 r--p 001cb000 103:04 6209517                   /usr/lib/libstdc++.so.6.0.28
7f3cf55c9000-7f3cf55ca000 rw-p 001d8000 103:04 6209517                   /usr/lib/libstdc++.so.6.0.28
7f3cf55ca000-7f3cf55cd000 rw-p 00000000 00:00 0 
7f3cf55cd000-7f3cf565c000 r--p 00000000 103:04 6184954                   /usr/lib/libQt5Core.so.5.15.2
7f3cf565c000-7f3cf5965000 r-xp 0008f000 103:04 6184954                   /usr/lib/libQt5Core.so.5.15.2
7f3cf5965000-7f3cf5b10000 r--p 00398000 103:04 6184954                   /usr/lib/libQt5Core.so.5.15.2
7f3cf5b10000-7f3cf5b1d000 r--p 00542000 103:04 6184954                   /usr/lib/libQt5Core.so.5.15.2
7f3cf5b1d000-7f3cf5b1e000 rw-p 0054f000 103:04 6184954                   /usr/lib/libQt5Core.so.5.15.2
7f3cf5b1e000-7f3cf5b22000 rw-p 00000000 00:00 0 
7f3cf5b22000-7f3cf5b36000 r--p 00000000 103:04 6194545                   /usr/lib/libignition-common3.so.3.9.0
7f3cf5b36000-7f3cf5b65000 r-xp 00014000 103:04 6194545                   /usr/lib/libignition-common3.so.3.9.0
7f3cf5b65000-7f3cf5b71000 r--p 00043000 103:04 6194545                   /usr/lib/libignition-common3.so.3.9.0
7f3cf5b71000-7f3cf5b73000 r--p 0004e000 103:04 6194545                   /usr/lib/libignition-common3.so.3.9.0
7f3cf5b73000-7f3cf5b74000 rw-p 00050000 103:04 6194545                   /usr/lib/libignition-common3.so.3.9.0
7f3cf5b74000-7f3cf5b95000 r--p 00000000 103:04 6240161                   /usr/lib/libignition-fuel_tools5.so.5.0.0
7f3cf5b95000-7f3cf5bf5000 r-xp 00021000 103:04 6240161                   /usr/lib/libignition-fuel_tools5.so.5.0.0
7f3cf5bf5000-7f3cf5c0a000 r--p 00081000 103:04 6240161                   /usr/lib/libignition-fuel_tools5.so.5.0.0
7f3cf5c0a000-7f3cf5c0d000 r--p 00095000 103:04 6240161                   /usr/lib/libignition-fuel_tools5.so.5.0.0
7f3cf5c0d000-7f3cf5c0e000 rw-p 00098000 103:04 6240161                   /usr/lib/libignition-fuel_tools5.so.5.0.0
7f3cf5c0e000-7f3cf5cf3000 r--p 00000000 103:04 6222117                   /usr/lib/libignition-gazebo4.so.4.1.0
7f3cf5cf3000-7f3cf5e1b000 r-xp 000e5000 103:04 6222117                   /usr/lib/libignition-gazebo4.so.4.1.0
7f3cf5e1b000-7f3cf5e80000 r--p 0020d000 103:04 6222117                   /usr/lib/libignition-gazebo4.so.4.1.0
7f3cf5e80000-7f3cf5e90000 r--p 00271000 103:04 6222117                   /usr/lib/libignition-gazebo4.so.4.1.0
7f3cf5e90000-7f3cf5e91000 rw-p 00281000 103:04 6222117                   /usr/lib/libignition-gazebo4.so.4.1.0
7f3cf5e91000-7f3cf5e93000 rw-p 00000000 00:00 0 
7f3cf5e93000-7f3cf5f58000 r--p 00000000 103:04 6222033                   /usr/lib/libignition-gazebo4-gui.so.4.1.0
7f3cf5f58000-7f3cf6017000 r-xp 000c5000 103:04 6222033                   /usr/lib/libignition-gazebo4-gui.so.4.1.0
7f3cf6017000-7f3cf6158000 r--p 00184000 103:04 6222033                   /usr/lib/libignition-gazebo4-gui.so.4.1.0
7f3cf6158000-7f3cf6159000 ---p 002c5000 103:04 6222033                   /usr/lib/libignition-gazebo4-gui.so.4.1.0
7f3cf6159000-7f3cf6166000 r--p 002c5000 103:04 6222033                   /usr/lib/libignition-gazebo4-gui.so.4.1.0
7f3cf6166000-7f3cf6167000 rw-p 002d2000 103:04 6222033                   /usr/lib/libignition-gazebo4-gui.so.4.1.0
7f3cf6167000-7f3cf6169000 rw-p 00000000 00:00 0 
7f3cf6169000-7f3cf6176000 r--p 00000000 103:04 6222036                   /usr/lib/libignition-gazebo4-ign.so.4.1.0
7f3cf6176000-7f3cf618c000 r-xp 0000d000 103:04 6222036                   /usr/lib/libignition-gazebo4-ign.so.4.1.0
7f3cf618c000-7f3cf6191000 r--p 00023000 103:04 6222036                   /usr/lib/libignition-gazebo4-ign.so.4.1.0
7f3cf6191000-7f3cf6192000 ---p 00028000 103:04 6222036                   /usr/lib/libignition-gazebo4-ign.so.4.1.0
7f3cf6192000-7f3cf6193000 r--p 00028000 103:04 6222036                   /usr/lib/libignition-gazebo4-ign.so.4.1.0
7f3cf6193000-7f3cf6194000 rw-p 00029000 103:04 6222036                   /usr/lib/libignition-gazebo4-ign.so.4.1.0
7f3cf6194000-7f3cf6195000 r--p 00000000 103:04 6224093                   /usr/lib/ruby/2.7.0/x86_64-linux/cgi/escape.so
7f3cf6195000-7f3cf6197000 r-xp 00001000 103:04 6224093                   /usr/lib/ruby/2.7.0/x86_64-linux/cgi/escape.so
7f3cf6197000-7f3cf6198000 r--p 00003000 103:04 6224093                   /usr/lib/ruby/2.7.0/x86_64-linux/cgi/escape.so
7f3cf6198000-7f3cf6199000 r--p 00003000 103:04 6224093                   /usr/lib/ruby/2.7.0/x86_64-linux/cgi/escape.so
7f3cf6199000-7f3cf619a000 rw-p 00004000 103:04 6224093                   /usr/lib/ruby/2.7.0/x86_64-linux/cgi/escape.so
7f3cf619a000-7f3cf619c000 r--p 00000000 103:04 6177115                   /usr/lib/libffi.so.7.1.0
7f3cf619c000-7f3cf61a2000 r-xp 00002000 103:04 6177115                   /usr/lib/libffi.so.7.1.0
7f3cf61a2000-7f3cf61a4000 r--p 00008000 103:04 6177115                   /usr/lib/libffi.so.7.1.0
7f3cf61a4000-7f3cf61a5000 r--p 00009000 103:04 6177115                   /usr/lib/libffi.so.7.1.0
7f3cf61a5000-7f3cf61a6000 rw-p 0000a000 103:04 6177115                   /usr/lib/libffi.so.7.1.0
7f3cf61a6000-7f3cf61a9000 r--p 00000000 103:04 6224169                   /usr/lib/ruby/2.7.0/x86_64-linux/fiddle.so
7f3cf61a9000-7f3cf61ae000 r-xp 00003000 103:04 6224169                   /usr/lib/ruby/2.7.0/x86_64-linux/fiddle.so
7f3cf61ae000-7f3cf61b0000 r--p 00008000 103:04 6224169                   /usr/lib/ruby/2.7.0/x86_64-linux/fiddle.so
7f3cf61b0000-7f3cf61b1000 r--p 00009000 103:04 6224169                   /usr/lib/ruby/2.7.0/x86_64-linux/fiddle.so
7f3cf61b1000-7f3cf61b2000 rw-p 0000a000 103:04 6224169                   /usr/lib/ruby/2.7.0/x86_64-linux/fiddle.so
7f3cf61b2000-7f3cf61b4000 r--p 00000000 103:04 6224191                   /usr/lib/ruby/2.7.0/x86_64-linux/strscan.so
7f3cf61b4000-7f3cf61b7000 r-xp 00002000 103:04 6224191                   /usr/lib/ruby/2.7.0/x86_64-linux/strscan.so
7f3cf61b7000-7f3cf61b8000 r--p 00005000 103:04 6224191                   /usr/lib/ruby/2.7.0/x86_64-linux/strscan.so
7f3cf61b8000-7f3cf61b9000 ---p 00006000 103:04 6224191                   /usr/lib/ruby/2.7.0/x86_64-linux/strscan.so
7f3cf61b9000-7f3cf61ba000 r--p 00006000 103:04 6224191                   /usr/lib/ruby/2.7.0/x86_64-linux/strscan.so
7f3cf61ba000-7f3cf61bb000 rw-p 00007000 103:04 6224191                   /usr/lib/ruby/2.7.0/x86_64-linux/strscan.so
7f3cf61bb000-7f3cf61bd000 r--p 00000000 103:04 6224190                   /usr/lib/ruby/2.7.0/x86_64-linux/stringio.so
7f3cf61bd000-7f3cf61c2000 r-xp 00002000 103:04 6224190                   /usr/lib/ruby/2.7.0/x86_64-linux/stringio.so
7f3cf61c2000-7f3cf61c4000 r--p 00007000 103:04 6224190                   /usr/lib/ruby/2.7.0/x86_64-linux/stringio.so
7f3cf61c4000-7f3cf61c5000 r--p 00008000 103:04 6224190                   /usr/lib/ruby/2.7.0/x86_64-linux/stringio.so
7f3cf61c5000-7f3cf61c6000 rw-p 00009000 103:04 6224190                   /usr/lib/ruby/2.7.0/x86_64-linux/stringio.so
7f3cf61c6000-7f3cf61c8000 r--p 00000000 103:04 6195189                   /usr/lib/libyaml-0.so.2.0.9
7f3cf61c8000-7f3cf61e2000 r-xp 00002000 103:04 6195189                   /usr/lib/libyaml-0.so.2.0.9
7f3cf61e2000-7f3cf61e6000 r--p 0001c000 103:04 6195189                   /usr/lib/libyaml-0.so.2.0.9
7f3cf61e6000-7f3cf61e7000 r--p 0001f000 103:04 6195189                   /usr/lib/libyaml-0.so.2.0.9
7f3cf61e7000-7f3cf61e8000 rw-p 00020000 103:04 6195189                   /usr/lib/libyaml-0.so.2.0.9
7f3cf61e8000-7f3cf61eb000 r--p 00000000 103:04 6224181                   /usr/lib/ruby/2.7.0/x86_64-linux/psych.so
7f3cf61eb000-7f3cf61ee000 r-xp 00003000 103:04 6224181                   /usr/lib/ruby/2.7.0/x86_64-linux/psych.so
7f3cf61ee000-7f3cf61ef000 r--p 00006000 103:04 6224181                   /usr/lib/ruby/2.7.0/x86_64-linux/psych.so
7f3cf61ef000-7f3cf61f0000 ---p 00007000 103:04 6224181                   /usr/lib/ruby/2.7.0/x86_64-linux/psych.so
7f3cf61f0000-7f3cf61f1000 r--p 00007000 103:04 6224181                   /usr/lib/ruby/2.7.0/x86_64-linux/psych.so
7f3cf61f1000-7f3cf61f2000 rw-p 00008000 103:04 6224181                   /usr/lib/ruby/2.7.0/x86_64-linux/psych.so
7f3cf61f2000-7f3cf61f3000 r--p 00000000 103:04 6224176                   /usr/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f3cf61f3000-7f3cf61f4000 r-xp 00001000 103:04 6224176                   /usr/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f3cf61f4000-7f3cf61f5000 r--p 00002000 103:04 6224176                   /usr/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f3cf61f5000-7f3cf61f6000 r--p 00002000 103:04 6224176                   /usr/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f3cf61f6000-7f3cf61f7000 rw-p 00003000 103:04 6224176                   /usr/lib/ruby/2.7.0/x86_64-linux/monitor.so
7f3cf61f7000-7f3cf61f8000 r--p 00000000 103:04 6224152                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f3cf61f8000-7f3cf61fa000 r-xp 00001000 103:04 6224152                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f3cf61fa000-7f3cf61fb000 r--p 00003000 103:04 6224152                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f3cf61fb000-7f3cf61fc000 r--p 00003000 103:04 6224152                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f3cf61fc000-7f3cf61fd000 rw-p 00004000 103:04 6224152                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
7f3cf61fd000-7f3cf61fe000 r--p 00000000 103:04 6224108                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f3cf61fe000-7f3cf61ff000 r-xp 00001000 103:04 6224108                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f3cf61ff000-7f3cf6200000 r--p 00002000 103:04 6224108                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f3cf6200000-7f3cf6201000 r--p 00002000 103:04 6224108                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f3cf6201000-7f3cf6202000 rw-p 00003000 103:04 6224108                   /usr/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
7f3cf6202000-7f3cf6203000 ---p 00000000 00:00 0 
7f3cf6203000-7f3cf62a4000 rw-p 00000000 00:00 0 
7f3cf62a4000-7f3cf62a5000 ---p 00000000 00:00 0 
7f3cf62a5000-7f3cf6346000 rw-p 00000000 00:00 0 
7f3cf6346000-7f3cf6347000 ---p 00000000 00:00 0 
7f3cf6347000-7f3cf63e8000 rw-p 00000000 00:00 0 
7f3cf63e8000-7f3cf63e9000 ---p 00000000 00:00 0 
7f3cf63e9000-7f3cf648a000 rw-p 00000000 00:00 0 
7f3cf648a000-7f3cf648b000 ---p 00000000 00:00 0 
7f3cf648b000-7f3cf652c000 rw-p 00000000 00:00 0 
7f3cf652c000-7f3cf652d000 ---p 00000000 00:00 0 
7f3cf652d000-7f3cf65ce000 rw-p 00000000 00:00 0 
7f3cf65ce000-7f3cf65cf000 ---p 00000000 00:00 0 
7f3cf65cf000-7f3cf6670000 rw-p 00000000 00:00 0 
7f3cf6670000-7f3cf6671000 ---p 00000000 00:00 0 
7f3cf6671000-7f3cf6712000 rw-p 00000000 00:00 0 
7f3cf6712000-7f3cf6713000 ---p 00000000 00:00 0 
7f3cf6713000-7f3cf67b4000 rw-p 00000000 00:00 0 
7f3cf67b4000-7f3cf67b5000 ---p 00000000 00:00 0 
7f3cf67b5000-7f3cf6856000 rw-p 00000000 00:00 0 
7f3cf6856000-7f3cf6857000 ---p 00000000 00:00 0 
7f3cf6857000-7f3cf68f8000 rw-p 00000000 00:00 0 
7f3cf68f8000-7f3cf68f9000 ---p 00000000 00:00 0 
7f3cf68f9000-7f3cf699a000 rw-p 00000000 00:00 0 
7f3cf699a000-7f3cf699b000 ---p 00000000 00:00 0 
7f3cf699b000-7f3cf6a3c000 rw-p 00000000 00:00 0 
7f3cf6a3c000-7f3cf6a3d000 ---p 00000000 00:00 0 
7f3cf6a3d000-7f3cf6ade000 rw-p 00000000 00:00 0 
7f3cf6ade000-7f3cf6adf000 ---p 00000000 00:00 0 
7f3cf6adf000-7f3cf6b80000 rw-p 00000000 00:00 0 
7f3cf6b80000-7f3cf6b81000 ---p 00000000 00:00 0 
7f3cf6b81000-7f3cf6c22000 rw-p 00000000 00:00 0 
7f3cf6c22000-7f3cf6c23000 ---p 00000000 00:00 0 
7f3cf6c23000-7f3cf6cc4000 rw-p 00000000 00:00 0 
7f3cf6cc4000-7f3cf6cc5000 ---p 00000000 00:00 0 
7f3cf6cc5000-7f3cf6d66000 rw-p 00000000 00:00 0 
7f3cf6d66000-7f3cf6d67000 ---p 00000000 00:00 0 
7f3cf6d67000-7f3cf6e08000 rw-p 00000000 00:00 0 
7f3cf6e08000-7f3cf6e09000 ---p 00000000 00:00 0 
7f3cf6e09000-7f3cf6eaa000 rw-p 00000000 00:00 0 
7f3cf6eaa000-7f3cf6eab000 ---p 00000000 00:00 0 
7f3cf6eab000-7f3cf6f4c000 rw-p 00000000 00:00 0 
7f3cf6f4c000-7f3cf6f4d000 ---p 00000000 00:00 0 
7f3cf6f4d000-7f3cf6fee000 rw-p 00000000 00:00 0 
7f3cf6fee000-7f3cf6fef000 ---p 00000000 00:00 0 
7f3cf6fef000-7f3cf7090000 rw-p 00000000 00:00 0 
7f3cf7090000-7f3cf7091000 ---p 00000000 00:00 0 
7f3cf7091000-7f3cf7132000 rw-p 00000000 00:00 0 
7f3cf7132000-7f3cf7133000 ---p 00000000 00:00 0 
7f3cf7133000-7f3cf71d4000 rw-p 00000000 00:00 0 
7f3cf71d4000-7f3cf71d5000 ---p 00000000 00:00 0 
7f3cf71d5000-7f3cf7276000 rw-p 00000000 00:00 0 
7f3cf7276000-7f3cf7277000 ---p 00000000 00:00 0 
7f3cf7277000-7f3cf7318000 rw-p 00000000 00:00 0 
7f3cf7318000-7f3cf7319000 ---p 00000000 00:00 0 
7f3cf7319000-7f3cf73ba000 rw-p 00000000 00:00 0 
7f3cf73ba000-7f3cf73bb000 ---p 00000000 00:00 0 
7f3cf73bb000-7f3cf745c000 rw-p 00000000 00:00 0 
7f3cf745c000-7f3cf745d000 ---p 00000000 00:00 0 
7f3cf745d000-7f3cf74fe000 rw-p 00000000 00:00 0 
7f3cf74fe000-7f3cf74ff000 ---p 00000000 00:00 0 
7f3cf74ff000-7f3cf75a0000 rw-p 00000000 00:00 0 
7f3cf75a0000-7f3cf75a1000 ---p 00000000 00:00 0 
7f3cf75a1000-7f3cf97ad000 rw-p 00000000 00:00 0 
7f3cf97ad000-7f3cf9a94000 r--p 00000000 103:04 6210751                   /usr/lib/locale/locale-archive
7f3cf9a94000-7f3cf9a96000 rw-p 00000000 00:00 0 
7f3cf9a96000-7f3cf9aa5000 r--p 00000000 103:04 6163927                   /usr/lib/libm-2.32.so
7f3cf9aa5000-7f3cf9b41000 r-xp 0000f000 103:04 6163927                   /usr/lib/libm-2.32.so
7f3cf9b41000-7f3cf9bda000 r--p 000ab000 103:04 6163927                   /usr/lib/libm-2.32.so
7f3cf9bda000-7f3cf9bdb000 r--p 00143000 103:04 6163927                   /usr/lib/libm-2.32.so
7f3cf9bdb000-7f3cf9bdc000 rw-p 00144000 103:04 6163927                   /usr/lib/libm-2.32.so
7f3cf9bdc000-7f3cf9bde000 r--p 00000000 103:04 6227090                   /usr/lib/libcrypt.so.2.0.0
7f3cf9bde000-7f3cf9bf0000 r-xp 00002000 103:04 6227090                   /usr/lib/libcrypt.so.2.0.0
7f3cf9bf0000-7f3cf9c09000 r--p 00014000 103:04 6227090                   /usr/lib/libcrypt.so.2.0.0
7f3cf9c09000-7f3cf9c0a000 r--p 0002c000 103:04 6227090                   /usr/lib/libcrypt.so.2.0.0
7f3cf9c0a000-7f3cf9c0b000 rw-p 0002d000 103:04 6227090                   /usr/lib/libcrypt.so.2.0.0
7f3cf9c0b000-7f3cf9c13000 rw-p 00000000 00:00 0 
7f3cf9c13000-7f3cf9c14000 r--p 00000000 103:04 6163906                   /usr/lib/libdl-2.32.so
7f3cf9c14000-7f3cf9c16000 r-xp 00001000 103:04 6163906                   /usr/lib/libdl-2.32.so
7f3cf9c16000-7f3cf9c17000 r--p 00003000 103:04 6163906                   /usr/lib/libdl-2.32.so
7f3cf9c17000-7f3cf9c18000 r--p 00003000 103:04 6163906                   /usr/lib/libdl-2.32.so
7f3cf9c18000-7f3cf9c19000 rw-p 00004000 103:04 6163906                   /usr/lib/libdl-2.32.so
7f3cf9c19000-7f3cf9c1b000 rw-p 00000000 00:00 0 
7f3cf9c1b000-7f3cf9c2c000 r--p 00000000 103:04 6167679                   /usr/lib/libgmp.so.10.4.1
7f3cf9c2c000-7f3cf9ca0000 r-xp 00011000 103:04 6167679                   /usr/lib/libgmp.so.10.4.1
7f3cf9ca0000-7f3cf9cb7000 r--p 00085000 103:04 6167679                   /usr/lib/libgmp.so.10.4.1
7f3cf9cb7000-7f3cf9cb8000 ---p 0009c000 103:04 6167679                   /usr/lib/libgmp.so.10.4.1
7f3cf9cb8000-7f3cf9cba000 r--p 0009c000 103:04 6167679                   /usr/lib/libgmp.so.10.4.1
7f3cf9cba000-7f3cf9cbb000 rw-p 0009e000 103:04 6167679                   /usr/lib/libgmp.so.10.4.1
7f3cf9cbb000-7f3cf9cbe000 r--p 00000000 103:04 6163985                   /usr/lib/librt-2.32.so
7f3cf9cbe000-7f3cf9cc2000 r-xp 00003000 103:04 6163985                   /usr/lib/librt-2.32.so
7f3cf9cc2000-7f3cf9cc4000 r--p 00007000 103:04 6163985                   /usr/lib/librt-2.32.so
7f3cf9cc4000-7f3cf9cc5000 r--p 00008000 103:04 6163985                   /usr/lib/librt-2.32.so
7f3cf9cc5000-7f3cf9cc6000 rw-p 00009000 103:04 6163985                   /usr/lib/librt-2.32.so
7f3cf9cc6000-7f3cf9ccd000 r--p 00000000 103:04 6163976                   /usr/lib/libpthread-2.32.so
7f3cf9ccd000-7f3cf9cdd000 r-xp 00007000 103:04 6163976                   /usr/lib/libpthread-2.32.so
7f3cf9cdd000-7f3cf9ce2000 r--p 00017000 103:04 6163976                   /usr/lib/libpthread-2.32.so
7f3cf9ce2000-7f3cf9ce3000 r--p 0001b000 103:04 6163976                   /usr/lib/libpthread-2.32.so
7f3cf9ce3000-7f3cf9ce4000 rw-p 0001c000 103:04 6163976                   /usr/lib/libpthread-2.32.so
7f3cf9ce4000-7f3cf9ce8000 rw-p 00000000 00:00 0 
7f3cf9ce8000-7f3cf9ceb000 r--p 00000000 103:04 6194523                   /usr/lib/libz.so.1.2.11
7f3cf9ceb000-7f3cf9cf9000 r-xp 00003000 103:04 6194523                   /usr/lib/libz.so.1.2.11
7f3cf9cf9000-7f3cf9cff000 r--p 00011000 103:04 6194523                   /usr/lib/libz.so.1.2.11
7f3cf9cff000-7f3cf9d00000 ---p 00017000 103:04 6194523                   /usr/lib/libz.so.1.2.11
7f3cf9d00000-7f3cf9d01000 r--p 00017000 103:04 6194523                   /usr/lib/libz.so.1.2.11
7f3cf9d01000-7f3cf9d02000 rw-p 00018000 103:04 6194523                   /usr/lib/libz.so.1.2.11
7f3cf9d02000-7f3cf9d28000 r--p 00000000 103:04 6163879                   /usr/lib/libc-2.32.so
7f3cf9d28000-7f3cf9e75000 r-xp 00026000 103:04 6163879                   /usr/lib/libc-2.32.so
7f3cf9e75000-7f3cf9ec1000 r--p 00173000 103:04 6163879                   /usr/lib/libc-2.32.so
7f3cf9ec1000-7f3cf9ec4000 r--p 001be000 103:04 6163879                   /usr/lib/libc-2.32.so
7f3cf9ec4000-7f3cf9ec7000 rw-p 001c1000 103:04 6163879                   /usr/lib/libc-2.32.so
7f3cf9ec7000-7f3cf9ecb000 rw-p 00000000 00:00 0 
7f3cf9ecb000-7f3cf9ef8000 r--p 00000000 103:04 6208497                   /usr/lib/libruby.so.2.7.2
7f3cf9ef8000-7f3cfa10f000 r-xp 0002d000 103:04 6208497                   /usr/lib/libruby.so.2.7.2
7f3cfa10f000-7f3cfa207000 r--p 00244000 103:04 6208497                   /usr/lib/libruby.so.2.7.2
7f3cfa207000-7f3cfa210000 r--p 0033b000 103:04 6208497                   /usr/lib/libruby.so.2.7.2
7f3cfa210000-7f3cfa211000 rw-p 00344000 103:04 6208497                   /usr/lib/libruby.so.2.7.2
7f3cfa211000-7f3cfa22d000 rw-p 00000000 00:00 0 
7f3cfa22d000-7f3cfa22f000 r--p 00000000 103:04 6163799                   /usr/lib/ld-2.32.so
7f3cfa22f000-7f3cfa250000 r-xp 00002000 103:04 6163799                   /usr/lib/ld-2.32.so
7f3cfa250000-7f3cfa259000 r--p 00023000 103:04 6163799                   /usr/lib/ld-2.32.so
7f3cfa259000-7f3cfa25a000 r--p 0002b000 103:04 6163799                   /usr/lib/ld-2.32.so
7f3cfa25a000-7f3cfa25c000 rw-p 0002c000 103:04 6163799                   /usr/lib/ld-2.32.so
7ffc94ab1000-7ffc952b0000 rw-p 00000000 00:00 0                          [stack]
7ffc953c2000-7ffc953c6000 r--p 00000000 00:00 0                          [vvar]
7ffc953c6000-7ffc953c8000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]
  ```

</details>

Sys info:
OS: Arch Linux
GCC: 10.2.0
Qt: 5.15.2
ruby: 2.7.2
protobuf: 3.12.4

### PR DESCRIPTION
**Pull request by acxz**
See: https://bugreports.qt.io/browse/QTBUG-89114

Resolves #526

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
Do you min to sign the commit https://github.com/ignitionrobotics/ign-gazebo/pull/527/checks?check_run_id=1632552957 ?

**Comment by acxz** [comment]
Sorry bout that,  signed

File: src/gui/plugins/scene3d/Scene3D.cc [hunk 1]
```diff
@@ -1970,8 +1970,9 @@ TextureNode::TextureNode(QQuickWindow *_window)
 #if QT_VERSION < QT_VERSION_CHECK(5, 14, 0)
   this->texture = this->window->createTextureFromId(0, QSize(1, 1));
 #else
+  int blank_id = 0;
```
Comment (chapulina) [inline src/gui/plugins/scene3d/Scene3D.cc:1973]: Nitpick: style is `camelCase`.

Also, we may want to match the `ign-gui` implementation from https://github.com/ignitionrobotics/ign-gui/pull/155/, so:

```suggestion
  void * nativeLayout;
```

File: src/gui/plugins/scene3d/Scene3D.cc [hunk 2]
```diff
@@ -1970,8 +1970,9 @@ TextureNode::TextureNode(QQuickWindow *_window)
...
   this->texture = this->window->createTextureFromNativeObject(
-      QQuickWindow::NativeObjectTexture, nullptr, 0, QSize(1, 1),
+      QQuickWindow::NativeObjectTexture, &blank_id, 0, QSize(1, 1),
```
Comment (chapulina) [inline src/gui/plugins/scene3d/Scene3D.cc:1975]:
```suggestion
      QQuickWindow::NativeObjectTexture, &nativeLayout, 0, QSize(1, 1),
```

**Review by chapulina — COMMENTED** [review]
Thanks, LGTM, mind just updating the style? It would also be good to match `ign-gui`.

File: src/gui/plugins/scene3d/Scene3D.cc (hunk 1 above)
Comment (acxz) [reply src/gui/plugins/scene3d/Scene3D.cc:1973]: ah mb for the formatting,

yeah I figured it would be a good idea to keep the same implementation.

**Comment by acxz** [comment]
@chapulina sounds good, also squashed your suggestions.
