### PR TITLE
SceneBroadcaster: Use double for state publish frequency instead of int

### LINKED ISSUE #1414: SceneBroadcaster's _hertz options crash with doubles
## Environment
* OS Version:  Ubuntu 20.02
* Source or binary build? either
  
  

## Description
* Expected behavior:  I can pass double values to `<state_hertz>` and `<dynamic_state_hertz>`, like `0.01`
* Actual behavior:  A crash

## Steps to reproduce

Load a world that has a `< 0` double value for the frequency, for example

```
      <plugin
        filename="ignition-gazebo-scene-broadcaster-system"
        name="ignition::gazebo::systems::SceneBroadcaster">
        <state_hertz>0.01</state_hertz>
      </plugin> 
```

## Output

Backtrace:

```
Thread 1 "INTEGRATION_sce" received signal SIGFPE, Arithmetic exception.                                                                 
0x00007fc1f83c4e04 in ignition::gazebo::v6::systems::SceneBroadcaster::Configure (this=0x563b60e176e0, _entity=<optimized out>, _sdf=..., 
    _ecm=...) at /usr/include/c++/9/chrono:331                                                                                              331               constexpr explicit duration(const _Rep2& __rep)                                                                           
(gdb) bt                                                                                                                                    
#0  0x00007fc1f83c4e04 in ignition::gazebo::v6::systems::SceneBroadcaster::Configure (this=0x563b60e176e0, _entity=<optimized out>, 
    _sdf=..., _ecm=...) at /usr/include/c++/9/chrono:331  
```

### PR DESCRIPTION
**Pull request by Thodoris1999**
…

# 🦟 Bug fix

Fixes #1414 

## Summary
Changed the `state_hertz` publishing frequency data type from `int` to `double`. Previously, worlds with those params set between 0 and 1 would crash due to being rounded to 0 and `state_hertz` being inverted. Note that dynamic_pose_hertz still gets rounded down to 0 as it is represented as `int` in `AdvertiseOptions`, but does not cause a crash.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

### CODE REVIEW

File: src/systems/scene_broadcaster/SceneBroadcaster.cc [hunk 1]
```diff
@@ -261,16 +261,17 @@ void SceneBroadcaster::Configure(
   auto readHertz = _sdf->Get<int>("dynamic_pose_hertz", 60);
   this->dataPtr->dyPoseHertz = readHertz.first;
 
-  auto stateHerz = _sdf->Get<int>("state_hertz", 60);
+  auto stateHertz = _sdf->Get<double>("state_hertz", 60);
+  if (stateHertz.first < 0.0)
+  {
+    ignerr << "SceneBroadcaster state_hertz must be non-negative\n";
```
Comment (chapulina) [inline src/systems/scene_broadcaster/SceneBroadcaster.cc:267]: How about also checking whether it's zero to avoid the division by zero?

And if this check fails, we shouldn't just print an error, but also make sure that the computations below don't end up in undefined behaviour. We could for example set the value to 1 and mention this in the error message.

**Review by chapulina — CHANGES_REQUESTED** [review]
Thanks for the PR, the fix works for me!

Would you be able to add a test to `test/integration/scene_broadcaster_system.cc`? It will be tricky to check for precise publish times since the plugin uses the system clock, so I think the test could at least check that there's no crash.

File: src/systems/scene_broadcaster/SceneBroadcaster.cc (hunk 1 above)
Comment (Thodoris1999) [reply src/systems/scene_broadcaster/SceneBroadcaster.cc:267]: I see, I missed that

**Comment by Thodoris1999** [comment]
I am a little new to this, is there an example for a test for crashing?

**Comment by Thodoris1999** [comment]
I think I can make [death tests](https://google.github.io/googletest/advanced.html#death-tests) to check for crashes, is it ok? I am asking because I have not seen it in any other one of gazebo's test suites.

**Comment by chapulina** [comment]
> I think I can make [death tests](https://google.github.io/googletest/advanced.html#death-tests) to check for crashes, is it ok? I am asking because I have not seen it in any other one of gazebo's test suites.

Oh I don't think we need to go that far. Just exercising that code path and having the test run successfully should be enough to make sure there's no crash. This way, if someone reverts the changes from this PR in the future, the test will crash and we'll notice the regression.

Thanks!

**Comment by Thodoris1999** [comment]
I added a test with a simple SDF file. It passes with the current fix but if applied before the patch it crashes with `Floating point exception (core dumped)` as expected.

**Review by chapulina — APPROVED** [review]
Thanks for iterating!
